import {escapeText as esc,readingTime,icon} from './reading-content.mjs';
const safeUrl=value=>{try{const u=new URL(value);return u.protocol==='https:'?u:null;}catch{return null;}};
export async function mountNews(root,{request,bindReader,readerMarkup,friendlyError}){
 const life=new AbortController();let disposed=false,ticket=0,reading=null,all=false,limit=12,query='';
 root.innerHTML='<header class="at-report-head"><div><h1 class="reader-news-title">消息导读</h1><p class="muted">先读监管、机构参与和行业动向，再按主题查找完整材料。</p></div><button class="btn" id="at-events-refresh">刷新</button></header><p id="at-events-feedback" role="status"></p><div class="event-discovery-controls"><label>查找已保存消息<input type="search" id="at-events-search" placeholder="输入中文主题或原文关键词" maxlength="200"></label><button class="btn" id="at-events-all">浏览全部材料</button><a class="btn" href="#/agent-events">事件解读 '+icon('arrow')+'</a></div><div id="at-events-body"></div><button class="btn" id="at-events-more" hidden>继续阅读</button>'+readerMarkup();
 const find=id=>root.querySelector('#'+id),feedback=text=>{if(!disposed)find('at-events-feedback').textContent=text;},cleanup=bindReader(root,feedback);
 function draw(){if(!reading)return;const value=reading,q=query.trim().toLocaleLowerCase(),matches=value.items.filter(item=>!q||[item.translation?.title,item.translation?.summary,item.title,item.summary].join(' ').toLocaleLowerCase().includes(q)),selected=all||q?matches:matches.filter(item=>item.translation?.featured).slice(0,3),items=selected.slice(0,limit);find('at-events-all').textContent=all?'返回导读':'浏览全部 '+value.items.length+' 则';find('at-events-more').hidden=items.length>=selected.length;
  const label={not_researched:'还没有保存的事件研究。',not_acquired:'这次研究尚未取得事件材料。',sources_unavailable:'来源读取失败，不能据此判断市场没有事件。',no_materials_found:'本次没有发现可列出的材料；不代表市场没有事件。',materials_found:''}[value.state];
  feedback(q?'找到 '+matches.length+' 则匹配消息。':all?'正在浏览本次保存的 '+value.items.length+' 则材料。':label||'从本次保存材料中选读 '+items.length+' 则行业消息。');
  find('at-events-body').innerHTML='<p class="muted event-coverage">材料观察到 '+readingTime(value.asOf)+' · 搜索覆盖本次保存的 '+value.items.length+' 则。<a href="#/records?kind=narrative">查找往期专题</a></p>'+(items.length?'<div class="at-event-list">'+items.map(item=>{
   const index=value.items.indexOf(item),t=item.translation,u=safeUrl(item.url),chinese=/\p{Script=Han}/u.test(item.title),title=t?.title||(chinese?item.title:'这则海外报道尚待中文整理'),summary=t?.summary||(t?.scope==='title'?'目前提供标题译文，尚未整理中文摘要。':chinese?item.summary:'原语言材料已保存，可展开核对。'),article=item.article;
   return '<details class="at-event-item" data-event-id="'+esc(item.id||index)+'"><summary><h3>'+esc(title)+'</h3><span class="at-event-meta">'+esc(u?.hostname||'来源见原件')+' · '+readingTime(item.publishedAt)+' · '+(t?t.scope==='title'?'标题译文':'摘要译文':chinese?'保存材料':'中文待整理')+'</span><span class="event-read-label">阅读消息 '+icon('arrow')+'</span></summary><div class="at-event-content"><p>'+esc(summary||'原条目没有提供摘要。')+'</p><p class="muted">'+(article?.ok?'已取得网页摘录，全文完整性尚未确认。':'当前以标题或摘要为依据，尚未核对完整正文。')+' 报道内容不等于已确认的市场影响。</p><p class="muted">报道时间 '+readingTime(item.publishedAt)+' · 事件发生时间 '+readingTime(item.occurredAt)+'</p><div class="at-toolbar"><button class="btn" data-evidence="'+esc(item.receiptId)+'" data-cycle="'+esc(value.cycleId)+'">'+icon('source')+'来源详情</button>'+(u?'<a class="btn" href="'+esc(u.href)+'" target="_blank" rel="noopener noreferrer">发布方原文 ↗</a>':'')+(article?'<button class="btn" data-evidence="'+esc(article.receiptId)+'" data-cycle="'+esc(value.cycleId)+'">网页摘录</button>':'')+'</div><details><summary>原语言标题与摘要</summary><h4 lang="en">'+esc(item.title)+'</h4><p lang="en">'+esc(item.summary||'原条目无摘要')+'</p></details><details><summary>这则消息与报告的关系</summary>'+relations(item,value)+'</details><button class="btn" data-current-event="'+index+'">以这则消息提出问题 '+icon('arrow')+'</button></div></details>';
  }).join('')+'</div>':'<section class="at-empty"><h3>'+(q?'没有匹配的消息':'暂时没有可选读消息')+'</h3><p>'+(q?'尝试更短的词，或清空搜索浏览本次材料。':'可以浏览全部材料，核对未整理或未取得的内容。')+'</p></section>')+'<details class="at-details"><summary>来源覆盖与读取情况</summary><p>这里只检索本次保存材料，不是全网新闻库。重复来源、摘要和网页摘录均不代表事实已独立核实。</p>'+value.sources.map(s=>'<p>'+esc(s.ok?s.usable?'已取得材料':'已读取，但材料有限':'读取失败：'+friendlyError(s.error))+'</p>').join('')+'</details>';
 }
 function relations(item,value){const ids=[item.receiptId,item.article?.receiptId].filter(Boolean),rows=[value.analyst,value.chief].filter(Boolean).filter(r=>r.report?.claims?.some(c=>(c.evidenceIds||[]).some(id=>ids.includes(id))));return rows.length?'<p>以下报告引用了同一份来源材料。一份来源可能包含多则消息，这不表示每则都被采纳，也不表示确认了因果。</p>'+rows.map(r=>'<button class="btn" data-report="'+esc(r.id)+'">'+(r.role==='chief'?'首席报告':'事件解读')+' · '+readingTime(r.asOf)+'</button>').join(''):'<p>没有找到当前返回报告对这份来源的明确引用，尚不能用它解释行情。</p>';}
 async function refresh(){const own=++ticket;feedback('正在读取保存的消息…');try{const value=await request('events',undefined,{signal:life.signal});if(disposed||own!==ticket)return;if(!Array.isArray(value.items)||!Array.isArray(value.sources)||!['not_researched','not_acquired','sources_unavailable','no_materials_found','materials_found'].includes(value.state))throw Error('消息资料不完整');reading=value;draw();}catch(error){if(!disposed&&own===ticket){reading=null;feedback('消息读取失败：'+friendlyError(error));find('at-events-body').innerHTML='<section class="at-empty"><h3>暂时无法打开消息</h3><p>请刷新重试；这不表示市场没有事件。</p></section>';find('at-events-more').hidden=true;}}}
 find('at-events-refresh').onclick=refresh;find('at-events-all').onclick=()=>{all=!all;limit=12;draw();};find('at-events-more').onclick=()=>{limit+=12;draw();};find('at-events-search').addEventListener('input',event=>{query=event.target.value;limit=12;draw();},{signal:life.signal});
 root.addEventListener('click',event=>{const b=event.target.closest('[data-current-event]'),item=b&&reading?.items?.[Number(b.dataset.currentEvent)];if(item)globalThis.UserWorkspace.begin({origin:'events',material:{kind:'discovered_event',title:item.translation?.title||item.title,materialRef:item.materialRef}});},{signal:life.signal});
 void refresh();return ()=>{disposed=true;++ticket;life.abort();cleanup();};
}
