// Reader editions are separate projections. Original reports and exports stay intact.
export const domainNames={env:'行情',flow:'盘口',deriv:'衍生品',macro:'宏观',events:'事件'};
export const escapeText=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function readingTime(value,{day=false}={}){if(typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)){const n=Date.parse(value+'T00:00:00Z');return Number.isFinite(n)&&new Date(n).toISOString().slice(0,10)===value?value.replaceAll('-','/')+' · 仅日期':'时间未知';}const n=typeof value==='number'?value:Date.parse(value);return Number.isFinite(n)?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',...(!day?{hour:'2-digit',minute:'2-digit',hour12:false}:{})}).format(n):'时间未知';}
export function plainText(value){return String(value??'').replace(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z/g,x=>readingTime(x)).replace(/\bOI\b/g,'未平仓量').replace(/\bDFII10\b/g,'美国十年期实际利率').replace(/\bDGS10\b/g,'美国十年期国债收益率').replace(/\bDTWEXBGS\b/g,'广义美元指数').replace(/\bUSDT\/BTC\b/g,'USDT/枚').replace(/闭合(15m|1h|4h)栏/g,(_,x)=>'已收盘'+({'15m':'15分钟','1h':'小时','4h':'4小时'}[x])+'K线').replace(/\b[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}\b/g,'（原件见来源详情）');}
export const icon=name=>'<svg class="reader-icon" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">'+({arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',book:'<path d="M12 5v15M3 4c4-1 7 0 9 2 2-2 5-3 9-2v15c-4-1-7 0-9 2-2-2-5-3-9-2Z"/>',source:'<path d="M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-2 2m2 6a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l2-2"/>',chart:'<path d="M4 3v17h17M7 14l4-4 4 2 6-7"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10h.01"/>'}[name]||'<circle cx="12" cy="12" r="8"/>')+'</svg>';
const cache=new Map();
export async function prepareReading(record,read){if(!record?.id||cache.has(record.id))return;try{const content=await read('reading/'+encodeURIComponent(record.id));if(content.reportId===record.id)cache.set(record.id,content);}catch{/* Reading originals remains available; no automatic model call. */}}
export function readingFor(record){return cache.get(record?.id)||null;}
export function reportTitle(record){return readingFor(record)?.edition?.title||plainText(record?.report?.summary?.split(/[。！？]/)[0]||'尚无市场解读');}
export function readingMarkdown(record,{source='service'}={}){
 const content=source==='service'?readingFor(record):null,e=content?.edition,r=record.report;
 const sections=e?.sections||[{heading:'市场变化',paragraphs:r.changes||[]}];
 return ['# '+(e?.title||plainText(r.summary)),'','中文阅读稿 · '+(e?'编辑版':'原报告整理版'),'观察到：'+readingTime(record.asOf)+'（北京时间）','完成于：'+readingTime(record.generatedAt),'所选报告：'+record.id,'来源研究：'+record.cycleId,'',e?.lead||plainText(r.summary),'',...(e?.highlights?.length?['## 本期要点','',...e.highlights.map(x=>'- '+x),'']:[]),...sections.flatMap(s=>['## '+s.heading,'',...s.paragraphs.map(plainText),'',...(s.claimIds?.length?['对应原报告主张：'+s.claimIds.join('、'),'']:[])]),...(content?.news||[]).flatMap(n=>['## '+n.translation.title,'',n.translation.summary||'仅标题译文','报道时间：'+readingTime(n.publishedAt)+'；来源：'+n.publisher,'原件：'+n.receiptId,'']),'## 限制与不同解释','',...(e?.risks||r.counterevidence||[]).map(plainText),'','## 接下来关注','',...(e?.watch||r.nextChecks||[]).map(x=>'- '+plainText(x)),'','本文件是所选原件的阅读稿，不替代包含全部论证和原始字段的JSON原件。',source==='service'?'本地原件链接：#/team-record?reportId='+encodeURIComponent(record.id):'本稿来自所选导入原件；没有替换成本机同名报告。'].join('\n\n');
}
const paragraph=text=>'<p>'+escapeText(plainText(text))+'</p>';
const bulletList=items=>'<ul>'+items.map(x=>'<li>'+escapeText(plainText(x))+'</li>').join('')+'</ul>';
const sourceButtons=(claimIds,record)=>{const claims=(record.report.claims||[]).filter(c=>claimIds.includes(c.id)),labels=readingFor(record)?.sourceLabels||{};return claims.map(c=>'<div class="reader-claim-sources"><p>'+escapeText(plainText(c.text))+'</p><div class="at-toolbar">'+(c.evidenceIds||[]).map(id=>'<button class="btn reader-source" data-evidence="'+escapeText(id)+'" data-cycle="'+escapeText(record.cycleId)+'" data-claim="'+escapeText(c.text)+'">'+icon('source')+escapeText(labels[id]||'查看原始依据')+'</button>').join('')+'</div></div>').join('');};
export function readingChart(chart,cycleId){if(!chart?.points?.length)return '';const pts=chart.points.filter(x=>Number.isFinite(x.time)&&Number.isFinite(x.value));if(pts.length<2)return '';const min=Math.min(...pts.map(x=>x.value)),max=Math.max(...pts.map(x=>x.value)),lo=Math.min(...pts.map(x=>x.time)),hi=Math.max(...pts.map(x=>x.time));if(hi===lo)return '';const y=v=>150-(v-min)/(max-min||1)*120,x=t=>50+(t-lo)/(hi-lo)*580;let d='';for(let i=0;i<pts.length;i++){const p=pts[i],gap=i&&chart.stepMs&&p.time-pts[i-1].time>chart.stepMs*1.5;d+=(i&&!gap?'L':'M')+x(p.time).toFixed(1)+' '+y(p.value).toFixed(1)+' ';}
 return '<figure class="reader-chart"><figcaption><strong>'+icon('chart')+'当时的价格轨迹</strong><span>'+escapeText(chart.label)+' · 收盘价</span></figcaption><svg viewBox="0 0 660 190" role="img" aria-label="'+escapeText(chart.label+'，从'+readingTime(lo)+'到'+readingTime(hi)+'，'+pts.length+'个已保存观察，单位USDT/枚')+'"><path class="chart-grid" d="M50 30H630M50 90H630M50 150H630"/><text x="2" y="34">'+Math.round(max).toLocaleString('zh-CN')+'</text><text x="2" y="154">'+Math.round(min).toLocaleString('zh-CN')+'</text><path class="chart-line" d="'+d+'"/><text x="50" y="182">'+escapeText(readingTime(lo))+'</text><text x="630" y="182" text-anchor="end">'+escapeText(readingTime(hi))+'</text></svg><div class="reader-chart-mobile-range"><span>收盘范围 '+min.toLocaleString('zh-CN',{maximumFractionDigits:1})+' — '+max.toLocaleString('zh-CN',{maximumFractionDigits:1})+' USDT/枚</span><span>'+escapeText(readingTime(lo))+' — '+escapeText(readingTime(hi))+'</span></div><p>USDT/枚 · 北京时间 · '+(chart.complete?'所请求窗口已覆盖':'只展示保存样本，未覆盖完整请求窗口')+'。'+(chart.sampled?'原件为抽样端点，点间连线不代表完整走势。':'')+'</p><div class="at-toolbar"><button class="btn reader-source" data-evidence="'+escapeText(chart.receiptId)+'" data-cycle="'+escapeText(cycleId)+'">'+icon('source')+'查看这张图的资料</button><a class="btn reader-source" href="#/market?view=chart">查看当前市场 '+icon('arrow')+'</a></div></figure>';
}
export function articleReading(record,{chief=false,historical=false,rawMarkup='',domainMarkup='',source='service'}={}){
 const r=record.report,content=source==='service'?readingFor(record):null,edition=content?.edition,summary=plainText(r.summary),parts=summary.split(/(?<=[。！？])/).filter(Boolean),title=edition?.title||parts.shift()||'市场解读',lead=edition?.lead||parts.join('')||summary;
 const sections=edition?.sections||[{heading:'市场发生了哪些变化',paragraphs:r.changes||[],claimIds:[]}],risks=edition?.risks||r.counterevidence||[],watch=edition?.watch||r.nextChecks||[],type=record.task?.taskMode,label=chief?(type==='window'?'区间解读':type==='narrative'?'事件专题':'首席日报'):(domainNames[record.role]||'领域')+'解读';
 return `<article class="daily-article at-report ${chief?'at-chief-report':''}" data-testid="team-report" data-report-id="${escapeText(record.id)}"><header class="daily-heading"><div class="daily-kicker"><span>${icon('book')}${label}</span><time>${readingTime(record.asOf,{day:true})}</time><span>${historical?'当时版本':chief?'最近一期':'独立观点'}</span></div><h2>${escapeText(title)}</h2><p class="daily-lead at-thesis">${escapeText(lead)}</p><div class="daily-byline">${icon('clock')}观察到 ${readingTime(record.asOf)} · 北京时间 <details><summary>本期说明</summary><p>报告完成于 ${readingTime(record.generatedAt)}。${edition?'中文阅读稿根据这份原报告整理，不新增市场判断。':'按原报告摘要与变化整理；完整论证在文末保留。'} ${historical?'这是历史记录，不随实时数据更新。':''}</p>${type&&type!=='current'?'<p>观察范围：'+escapeText(record.task?.observation?readingTime(record.task.observation.from)+' — '+readingTime(record.task.observation.to):'指定事件材料')+'</p>':''}</details></div></header>
 ${!edition?'<p class="reader-format-note">'+(content?.editionState==='unavailable'?'中文编辑稿暂时无法核对。':'这份报告尚无中文编辑稿。')+'以下按原报告阅读，完整措辞和引用保留在文末。</p>':''}
 ${record.provenance?.mode&&record.provenance.mode!=='codex_cli'?'<p class="at-warning">测试或导入样本，不能作为当前市场解读。</p>':''}
 ${edition?.highlights?.length?'<aside class="daily-takeaways"><h3>本期要点</h3>'+bulletList(edition.highlights)+'</aside>':''}
 <nav class="daily-contents" aria-label="报告阅读目录"><button class="btn" data-reading-jump="changes">读解读</button><button class="btn" data-reading-jump="doubts">看限制与分歧</button><button class="btn" data-reading-jump="next">接下来关注</button></nav>
 <div class="daily-body"><section data-chapter="changes"><h3 tabindex="-1" class="sr-only">本期解读</h3>${sections.map((s,i)=>'<section class="daily-section"><span class="daily-section-number">'+String(i+1).padStart(2,'0')+'</span><h3>'+escapeText(s.heading)+'</h3>'+s.paragraphs.map(paragraph).join('')+(s.claimIds?.length?'<details class="reader-inline-sources"><summary>'+icon('source')+'这段解读的依据</summary><div class="at-toolbar">'+sourceButtons(s.claimIds,record)+'</div></details>':'')+(i===0?readingChart(content?.chart,record.cycleId):'')+'</section>').join('')}</section>
 ${content?.news?.length?'<section class="daily-section daily-news"><h3>本期行业背景</h3><p class="muted">来自这期研究的保存材料；报道内容尚不能证明行情因果。</p>'+content.news.map(n=>'<article><h4>'+escapeText(n.translation.title)+'</h4>'+paragraph(n.translation.summary||'已翻译标题，原条目没有可用摘要。')+'<p class="muted">'+escapeText(n.publisher)+' · '+readingTime(n.publishedAt)+' · '+escapeText(n.translation.scope==='title'?'仅标题译文':'摘要译文')+'</p><button class="btn reader-source" data-evidence="'+escapeText(n.receiptId)+'" data-cycle="'+escapeText(record.cycleId)+'">'+icon('source')+'报道来源与原文</button></article>').join('')+'</section>':''}
 <section class="daily-section daily-caution" data-chapter="doubts"><h3 tabindex="-1">哪些事还不能下结论</h3>${risks.map(paragraph).join('')}${r.disagreements?.length?'<h4>团队的不同看法</h4>'+r.disagreements.map(paragraph).join(''):''}</section>
 <section class="daily-section daily-watch" data-chapter="next"><h3 tabindex="-1">接下来关注什么</h3>${bulletList(watch)}</section>
 ${domainMarkup?'<section class="daily-section" data-chapter="domains"><h3 tabindex="-1">从不同角度继续读</h3>'+domainMarkup+'</section>':''}
 <details class="daily-original" data-chapter="evidence"><summary>${icon('source')}完整论证、引用与原始报告</summary><p class="muted">保留原分析的全部措辞、数字、比较范围和核查记录。</p>${rawMarkup}</details><footer class="daily-actions"><button class="btn" data-report="${escapeText(record.id)}">打开本篇与导出 ${icon('book')}</button>${source==='service'?'<a class="btn" href="#/team-record?reportId='+encodeURIComponent(record.id)+'">本篇本地链接 '+icon('source')+'</a>':''}</footer></div></article>`;
}
