import {nextSlots} from './schedule.mjs';
import {ROLES,conditionTiming,validateConfig} from './contract.mjs';
import {agentTaskRequest,acceptedTaskMatches,taskCapabilityIssue} from '../research-v2/desk-adapter.mjs';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const readable=x=>String(x??'').replace(/((?:回执|请求))[-a-f0-9]{36}/gi,'$1〔见引用依据〕').replace(/\b[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}\b/gi,'〔见研究记录〕').replace(/source_http_\d+/g,'上游响应异常').replaceAll('Codex 任务达到内部截止','研究达到时间上限');
const errorLabels={team_busy:'另一项研究正在进行，请等待完成或取消当前研究。',development_page_not_present:'研究连接尚未建立，请稍后再试。',request_id_conflict:'这次请求的范围与原请求不同，请重新核对后创建新研究。',invalid_question:'研究问题最多2000字。',unsupported_observation:'所选范围不受支持，未改用其他范围。',daily_call_budget:'今天的研究调用预算已用完，已有报告仍可阅读。',model_call_budget:'本轮研究调用预算已用完，已取得材料保留。',model_context_too_large:'本轮资料超出分析容量，首席未生成；已保留岗位报告与原始资料',tool_scope_denied:'工具权限与登记能力不一致，本次未取得资料',cleanup_uncertain:'上一轮退出尚未确认，暂不能开始新研究。',cleanup_inventory_unavailable:'缺少完整退出记录，继续保持暂停；请核对本机研究进程。',cleanup_inventory_incomplete:'退出记录不完整，继续保持暂停；请核对本机研究进程。',cleanup_identity_unavailable:'无法确认原进程身份，继续保持暂停。',previous_process_cleanup_required:'原研究进程仍在运行，继续保持暂停。',cleanup_recovery_not_applicable:'这次暂停需要处理保存或连接问题，不能通过退出核对解除。',storage_failed:'研究记录保存失败，请先检查存储后再开始。',auth:'研究连接需要重新登录，请进入设置检查连接。'};
Object.assign(errorLabels,{research_progress_without_current_evidence:'研究待办引用未通过本轮依据校验，未接受新报告',research_progress_baseline_mismatch:'研究待办的历史依据未对应明确的跨轮比较，未接受新报告',research_completion_without_evidence:'研究待办未提供完成依据，未接受新报告',tool_scope_denied:'取证请求与本岗位登记能力不一致，本次未取得资料'});
export const friendlyError=error=>{const raw=error?.message||error;if(/^Codex (?:调用失败或未完成|模型执行失败)/.test(raw||''))return '模型执行异常，本轮未取得新判断；原报告保留。';return raw==='user_cancelled'?'本轮主动停止':raw==='source_too_large'?'资料超出本次读取上限，未取得内容':raw==='development_interrupted_before_original'?'开发服务中断，本轮尚未保存原件或接受报告':raw==='development_process_interrupted'?'开发服务中断，本轮未完成；已保存的岗位和原件仍可查看':/^numeric_evidence_mismatch(?::|$)/.test(raw||'')?'报告中的数字与引用资料不一致，未接受新结论':raw==='numeric_claim_requires_reference'?'报告中的数量或时间标识缺少可核对依据，未接受新结论':raw==='research_progress_incomplete'?'上轮研究待办未逐项交代，未接受新报告':raw==='research_progress_parent_mismatch'?'研究待办与原任务不对应，未接受新报告':errorLabels[raw]||errorLabels[String(raw).split(':')[0]]||readable(raw||'研究服务暂时不可用。');};
const when=x=>x?new Date(x).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'未取得';
const labels={sufficient:'可用',limited:'覆盖有限',insufficient:'材料不足',accepted:'已更新',unchanged:'判断未变',failed:'失败',complete:'已完成',checked:'已核对无变化',running:'研究中',cancelled:'已取消',interrupted:'服务中断',skipped_busy:'忙时跳过',cleanup_uncertain:'进程清理待确认',storage_failed:'保存失败',incomplete:'本轮未完成',researching:'独立研究中',initial:'首次判断',maintain:'维持判断',revise:'修订判断',withdraw:'撤回判断'};
function dispositions(report,cycleId){const treatments={adopt:'采纳',reject:'未采纳',uncertain:'待核实',missing:'材料缺失'};return report.dispositions?.length?'<details class="at-details"><summary>首席如何处理各岗意见</summary>'+report.dispositions.map(d=>'<section class="at-claim"><strong>'+esc(ROLES[d.role]?.name||d.role)+' · '+esc(treatments[d.treatment]||d.treatment)+'</strong><p>'+esc(d.reason)+'</p><button class="btn" data-disposition="'+esc(d.role)+'" data-cycle="'+esc(cycleId)+'">查看当时岗位记录</button></section>').join('')+'</details>':'';}
const local=()=>/^(localhost|127\.0\.0\.1)$/.test(location.hostname);
export async function request(path,body){const r=await fetch('/api/local-agent-team/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(20000)});let value;try{value=await r.json();}catch{throw Object.assign(Error('研究服务暂时不可用，请稍后重试。'),r.ok?{}:{httpStatus:r.status});}if(!r.ok||value.error)throw Object.assign(Error(value.error||'本地请求失败'),{httpStatus:r.status});return value;}
let stream=null,tabId=null,lifecycleBound=false;
export function connectPresence(){if(!local()||stream)return;tabId=crypto.randomUUID();stream=new EventSource('/api/local-agent-team/presence?id='+tabId);const own=tabId;stream.onmessage=event=>{try{const data=JSON.parse(event.data);void request('presence',{id:own,nonce:data.nonce}).catch(()=>{});}catch{}};
  if(!lifecycleBound){lifecycleBound=true;const disconnect=()=>{stream?.close();stream=null;};window.addEventListener('pagehide',disconnect);document.addEventListener('freeze',disconnect);window.addEventListener('pageshow',()=>{if(!stream)connectPresence();});document.addEventListener('resume',()=>{if(!stream)connectPresence();});}}
function lists(values){return values?.length?'<ul class="at-list">'+values.map(x=>'<li>'+esc(readable(x))+'</li>').join('')+'</ul>':'<p class="muted">尚无可核查的内容。</p>';}
const taskNames={current:'当前市场更新',window:'指定窗口研究',narrative:'事件问题研究'};
const taskMode=row=>row?.task?.taskMode||row?.taskMode||'current';
const viewNames={chart:'价格与结构',orderflow:'成交足迹',heatmap:'已观察强平',derivatives:'杠杆与定价',macro:'宏观与资金',events:'事件资料'};
function providedTiming(m){if(m.content?.kind==='legacy_report_event'){const generated=m.content.originalReport?.generatedAt;return ' · 历史条目 · 原报告生成 '+(typeof generated==='string'&&Number.isFinite(Date.parse(generated))?when(generated):'未知')+' · 资料截至与公开时间未核实';}return m.content?.reportAsOf?' · 原报告截至 '+when(m.content.reportAsOf):'';}
export function taskCard(task,{compact=false}={}){
  if(!task)return '';
  const o=task.observation,provided=task.providedMaterials||[],refs=task.materialRefs||[];
  return `<section class="at-task-scope ${compact?'is-compact':''}" data-testid="task-scope"><strong>${esc(taskNames[task.taskMode]||'研究范围')}</strong>${o?`<p>${esc(o.symbol)} ${o.product==='spot'?'现货':'永续'} · Binance · ${esc(viewNames[o.view]||o.view)} · ${esc(o.timeframe)}${o.view==='orderflow'?' 阅读周期，取证保留原生5m':''}</p><p>${when(o.from)} — ${when(o.to)} <span class="muted">北京时间 · 起止均包含</span></p>`:''}${provided.map(m=>`<p>${esc(m.content?.title||m.content?.report?.title||m.id)}<small>用户提供原件 · 来源未独立核验${esc(providedTiming(m))}</small></p>`).join('')}${refs.length?`<p>指定原记录 ${refs.length} 项，保留所选版本。</p>`:''}<p class="muted">资料截止 ${when(task.dataCutoff)}${task.taskMode!=='current'?' · 结果单独保存':''}</p>${!compact?'<p class="muted">观察窗口说明研究哪一段市场；资料截止说明这次允许使用的资料时点。历史公开时点未知时保留未知。</p>':''}</section>`;
}
export function runCard(run){
  const row=run.row||run,roles=run.roles||{},status=row.terminal||row.status||'running';
  return `<section class="at-run" data-testid="task-record"><div class="at-report-head"><h2>当时的研究记录</h2><span class="at-status">${esc(labels[status]||status)}</span></div>${taskCard(row.task)}<p class="at-thesis">${esc(row.question||'核对当前市场变化')}</p><p class="muted">开始 ${when(row.startedAt||row.asOf)} · ${status==='interrupted'?'中断确认':['failed','cancelled','cleanup_uncertain','storage_failed'].includes(status)?'结束':'完成'} ${when(row.endedAt)}${row.reason?' · '+esc(friendlyError(row.reason)):''}</p><div class="at-toolbar">${row.accepted?.chief?`<button class="btn primary" data-report="${esc(row.accepted.chief)}">首席报告</button>`:''}</div>${conditionChecksCard(run.conditionChecks,row.id)}<h3>各领域当时的结果</h3>${Object.entries(ROLES).map(([role,info])=>{const r=roles[role],id=row.accepted?.[role]||r?.id,roleState=row.accepted?.[role]?'accepted':status!=='running'&&r?.status==='researching'?'incomplete':r?.status;return `<div class="at-run-role"><strong>${esc(info.name)}</strong><span>${esc(labels[roleState]||roleState||'未取得')}${r?.error?' · '+esc(friendlyError(r.error)):''}</span>${id?`<button class="btn" data-report="${esc(id)}">当时岗位报告</button>`:`<button class="btn" data-disposition="${esc(role)}" data-cycle="${esc(row.id)}">当时岗位结果</button>`}</div>`;}).join('')}<details class="at-details"><summary>本轮原始依据 · ${(run.receipts||[]).length} 项</summary>${(run.receipts||[]).map(r=>`<button class="btn at-receipt-link" data-evidence="${esc(r.id)}" data-cycle="${esc(row.id)}">${esc(ROLES[r.role]?.name||'资料')} · ${esc(materialName(r.request))} · ${esc(qualityNames[r.quality]||r.quality||'时效待核对')}</button>`).join('')}</details><details class="at-details"><summary>完整记录与运行明细</summary><pre>${esc(JSON.stringify(run,null,2))}</pre></details></section>`;
}
const fields={openInterest:'未平仓数量',sumOpenInterest:'历史持仓数量',sumOpenInterestValue:'持仓名义额',markPrice:'标记价',indexPrice:'指数价',lastFundingRate:'接口报告费率',fundingRate:'已结算费率',interestRate:'利息率',basis:'绝对基差',basisRate:'基差率',annualizedBasisRate:'年化基差率',futuresPrice:'合约价',buyVol:'主动买入量',sellVol:'主动卖出量',buySellRatio:'主动买卖量比',longAccount:'净多账户比例',shortAccount:'净空账户比例',longPosition:'头部多仓比例',shortPosition:'头部空仓比例',longShortRatio:'多空比',open:'开盘',close:'收盘',high:'最高',low:'最低',baseVolume:'成交量',quoteVolume:'成交额',value:'数值',spread_USDT:'可见价差',spread_bps:'价差基点',bid_BTC:'可见买单数量',ask_BTC:'可见卖单数量',bid_notional_USDT:'可见买单名义额',ask_notional_USDT:'可见卖单名义额',imbalance_ratio:'可见深度不平衡',return_pct:'返回闭合窗口收益'};
const qualityNames={discovered_source_background:'已发现报道原件 · 事实待核验',usable:'可用',partial:'覆盖有限',insufficient:'资料不足',summary_only:'摘要材料',original_excerpt:'已取得网页摘录',failed:'读取失败',provided_unverified:'用户提供 · 来源未独立核验',original_report_background:'指定原报告 · 作为背景',missing_selected_material:'所选原件无法取得',stale:'资料陈旧',unusable:'不满足本次取证要求'};
function materialName(request={}){const id=request.dataset||request.tool,match=String(id).match(/^binance-(perp|spot)-klines-(.+)$/);if(match)return 'Binance '+(match[1]==='spot'?'现货':'永续')+' · '+match[2]+' K线';return {'selected-material':'所选事件原件',footprint:'成交足迹',liquidations:'已观察强平',events:'事件资料',article:'报道网页','binance-perp-book':'Binance 可见盘口','binance-perp-taker':'Binance 主动成交','binance-perp-oi':'永续持仓','binance-perp-oi-history':'历史持仓','binance-perp-funding':'资金费率','binance-perp-premium':'永续定价','binance-perp-basis':'基差','binance-perp-top-positions':'头部账户持仓比例','binance-perp-accounts':'账户比例','fred-dgs2':'美国两年期利率','fred-dgs10':'美国十年期利率','fred-real10y':'美国十年期实际利率','fred-dollar':'美元指标','fred-fed-assets':'美联储资产','fred-rrp':'逆回购','fred-tga':'美国财政部账户'}[id]||id||'资料';}
function coverageLine(coverage={}){const historical=coverage.referencePeriodContext===true&&coverage.windowAppliedToReferencePeriods===false,rows=historical?coverage.returnedRows:coverage.returnedInWindow??coverage.items,count=Number.isSafeInteger(rows)&&rows>=0?rows+' 条':'数量未知';return historical?'历史参考期 '+count+'；不是观察窗内公布数量':count+' · '+(coverage.completeWindow?'完整请求窗口':'未确认完整请求窗口');}
function articleCoverage(r){return typeof r.data?.article?.text==='string'?r.data.article.text.length.toLocaleString('zh-CN')+' 字符网页摘录 · 全文完整性未核验'+(r.coverage?.truncated?' · 读取时已截取':''):'本轮未取得报道文字，不作为正文证据';}
function articleMarkup(r){const a=r.data?.article;if(typeof a?.text!=='string'||!a.text.trim())return '';let source=null;try{const u=new URL(a.url);if(u.protocol==='https:')source=u;}catch{}
  return `<section class="at-article" data-testid="article-excerpt"><h3>报道网页摘录</h3><p class="at-warning">${a.extraction==='publisher-body-excerpt'?'已从发布方正文区域提取文字，外围导航已排除；仍不代表全文、附件或独立来源核验。':'只取得网页文字片段，可能含导航和其他新闻列表；不代表全文、附件或独立来源核验。'}</p><p>${source?`来源：<a href="${esc(source.href)}" target="_blank" rel="noopener noreferrer">${esc(source.hostname)} ↗</a>`:'发布方链接未取得'} · 条目标示的报道时间 ${when(a.publishedAt)}</p><details class="at-details" open><summary>阅读已取得的文字片段</summary><div class="at-article-text" tabindex="0" role="region" aria-label="已取得的报道文字摘录">${esc(a.text)}</div></details></section>`;
}
const unitName=u=>({'percent-per-year':'%/年（来源利率口径）','million-USD':'百万美元','billion-USD':'十亿美元','decimal':'小数比率','decimal-per-settlement':'每次结算小数比率','decimal-per-year':'每年小数比率','fraction':'比例（0—1）','ratio':'倍或比值','count':'项','index-Jan2006=100':'指数（2006年1月=100）'}[u]||u);
function analysisStatsMarkup(r){const a=r.data?.analysis;if(!a)return '';const reference=r.coverage?.referencePeriodContext===true,period=x=>reference?new Date(x).toISOString().slice(0,10)+' 参考期':when(x);const format=n=>typeof n==='number'?Number(n.toPrecision(7)).toLocaleString('zh-CN',{maximumFractionDigits:6}):'未知';return '<section class="at-analysis-stats"><h3>实际返回资料的窗口比较</h3><p class="muted">按实际返回样本计算；描述变化，不代表预测概率或因果。</p>'+(a.windows||[]).map(w=>'<div class="at-analysis-window"><strong>'+when(w.from)+' → '+when(w.to)+'</strong><p>'+format(w.elapsedHours)+' 小时收盘到收盘 · '+format(w.sampleRows)+' 根样本 · 收益 '+format(w.returnPercent)+'%'+(w.rangePercent!==undefined?' · 区间振幅 '+format(w.rangePercent)+'%':'')+'</p><p>'+(w.baseVolume!==undefined?'本段成交 '+format(w.baseVolume)+' BTC':'成交量资料不足')+(w.volumeRatio!==undefined?' · 与前一不重叠同长段之比 '+format(w.volumeRatio)+' 倍（基准 '+when(w.volumeBaselineFrom)+' → '+when(w.volumeBaselineTo)+'）':' · 无可用的同长成交基准')+'</p></div>').join('')+(a.comparisons||[]).map(c=>'<div class="at-analysis-window"><strong>'+esc(fields[c.field]||c.field)+' · '+period(c.from)+' → '+period(c.to)+'</strong><p>'+format(c.previous)+' → '+format(c.latest)+' '+esc(unitName(r.numericUnits?.['analysis.comparisons.'+(a.comparisons.indexOf(c))+'.latest']||''))+' · 变化 '+format(c.change)+(c.changeBasisPoints!==undefined?'（'+format(c.changeBasisPoints)+' bp）':'')+(c.changePercent!==undefined?'（'+format(c.changePercent)+'%）':'')+'</p><small>'+format(c.referenceSteps)+' 个观察/参考期跨度；不是新发布次数。</small></div>').join('')+'</section>';}
export function receiptCard(r){const data=r.data||{},metrics=Object.entries(data.metrics||{}),units=r.numericUnits||{},samples=Object.entries(data.observations||{}).slice(0,5);return `<section class="at-evidence"><h2>依据与覆盖</h2>${r.historicalBaseline?'<p class="at-warning">历史基线资料 · 保留原锚点和原索引，不能当作本轮新事实。</p><p>来源轮次：'+esc(r.originCycleId||'未取得')+'</p>':''}<p>${esc(materialName(r.request))} · ${esc(qualityNames[r.quality]||r.quality)}${r.error?' · '+esc(friendlyError(r.error)):''}</p><dl><dt>研究锚点</dt><dd>${when(r.asOf)}</dd><dt>${r.request?.tool==='article'?'条目标示的报道时间':'最新观察'}</dt><dd>${when(r.request?.tool==='article'?data.article?.publishedAt:r.sourceClock?.observedAt)}</dd><dt>实际取得</dt><dd>${when(r.receivedAt)}</dd><dt>覆盖范围</dt><dd>${esc(r.request?.tool==='article'?articleCoverage(r):coverageLine(r.coverage))}</dd></dl>${articleMarkup(r)}${analysisStatsMarkup(r)}${metrics.length?'<div class="at-table-scroll"><table><thead><tr><th>指标</th><th>数值</th><th>单位</th></tr></thead><tbody>'+metrics.map(([key,v])=>'<tr><td>'+esc(fields[key]||key)+'</td><td>'+esc(v===null?'未知':typeof v==='number'?Number(v.toPrecision(10)):v)+'</td><td>'+esc(units['metrics.'+key]||'未登记')+'</td></tr>').join('')+'</tbody></table></div>':''}${data.returnWindow?'<p class="muted">收益计算起止：'+when(data.returnWindow.from)+' → '+when(data.returnWindow.to)+'；仅返回样本。</p>':''}${data.items?.length?'<h3>发现的事件材料</h3>'+lists(data.items.slice(0,12).map(x=>x.title+' · 发生 '+when(x.occurredAt)+' · 报道 '+when(x.publishedAt)+' · '+(x.scope||'摘要或事件记录'))):''}${samples.length?'<h3>可引用样本</h3>'+samples.map(([i,row])=>'<section class="at-sample"><strong>'+when(row.observedAt)+'</strong><p>'+Object.entries(row.values||{}).filter(([,v])=>v!==null&&!Array.isArray(v)&&typeof v!=='object').map(([key,v])=>esc((fields[key]||key)+': '+v+' '+(units['observations.'+i+'.values.'+key]||''))).join(' · ')+'</p></section>').join(''):''}<h3>来源链与限制</h3>${lists([...(r.sourceChain||[]),...(Array.isArray(data.limitations)?data.limitations:typeof data.limitations==='string'?[data.limitations]:[]),...(data.method?[data.method]:[])])}<details><summary>完整原始回执与字段</summary><pre>${esc(JSON.stringify(r,null,2))}</pre></details></section>`;}
export function reportCard(record,{chief=false,historical=false}={}){
  if(!record)return `<section class="at-empty"><h2>${chief?'等待第一份首席解读':'这个岗位尚未交付判断'}</h2><p>发起一次研究，团队会核对价格、盘口、衍生品、宏观和事件。资料不足的领域会保留缺口。</p><a href="#/market?view=chart">先查看市场资料 →</a></section>`;
  const r=record.report,claims=r.claims||[],change=r.viewChange||{},task=record.task;
  const title=chief?(historical?'当时首席解读':task?.taskMode&&task.taskMode!=='current'?'本次问题解读':'当前市场解读'):((ROLES[record.role]?.name?ROLES[record.role].name+' · ':'')+(historical?'当时岗位判断':'岗位判断'));
  return `<article class="at-report ${chief?'at-chief-report':''}" data-testid="team-report"><header class="at-report-head"><h2>${title}</h2><span class="at-status at-status--${esc(r.status)}">${esc(labels[r.status]||r.status)}</span></header><div class="at-meta"><span>资料截至 ${when(record.asOf)}</span><span>研究完成 ${when(record.generatedAt)}</span><span>${historical?'历史时点':Number.isFinite(Date.parse(record.asOf))?'距资料截止 '+Math.max(0,Math.floor((Date.now()-Date.parse(record.asOf))/60000))+' 分钟':'时效未知'}</span></div>${record.provenance?.mode&&record.provenance.mode!=='codex_cli'?'<p class="at-warning">测试/导入样本，不能作为当前市场解读。</p>':''}${task?.taskMode&&task.taskMode!=='current'?taskCard(task,{compact:true}):''}<p class="at-thesis">${esc(readable(r.summary))}</p>${chief?'<section class="at-key-facts"><h3>支撑解读的关键事实</h3>'+lists(claims.filter(c=>c.kind==='fact'&&c.scope!=='history').slice(0,3).map(c=>c.text))+'</section>':''}<div class="at-report-grid"><section><h3>较上次的变化</h3>${lists(r.changes)}</section><section><h3>反证与分歧</h3>${lists([...(r.counterevidence||[]),...(r.disagreements||[])])}</section></div><section class="at-next"><h3>接下来核查什么</h3>${lists(r.nextChecks)}${conditionCard(record)}${researchProgressCard(record)}</section><details class="at-details"><summary>观点与引用依据 · ${claims.length} 项</summary>${claims.map((c,i)=>`<section class="at-claim"><div class="at-claim-kind"><span>${esc(c.kind==='fact'?'事实':c.kind==='inference'?'推断':'假设')}</span><span>${esc({current:'本轮资料',history:'历史资料',comparison:'跨轮对照'}[c.scope]||'旧版记录')}</span></div><p>${esc(readable(c.text))}</p><div class="at-evidence-actions">${(c.evidenceIds||[]).map((id,j)=>`<button class="btn" data-evidence="${esc(id)}" data-cycle="${esc(record.cycleId)}" title="查看观点${i+1}的依据${j+1}">查看依据</button>`).join(' ')}</div>${c.numbers?.length?'<details class="at-number-detail"><summary>核对引用数值与口径</summary><p class="muted">'+c.numbers.map(n=>esc(n.value+' '+n.unit+' · '+n.path)).join('；')+'</p></details>':''}</section>`).join('')}</details>${chief?dispositions(r,record.cycleId):''}<details class="at-details"><summary>观点变化与研究记录</summary><p>${esc(labels[change.action]||change.action||'旧版记录')}：${esc(readable(change.reason))}</p>${change.previousReportId?`<button class="btn" data-previous="${esc(change.previousReportId)}">打开上一版观点</button>`:''}<details class="at-number-detail"><summary>版本与用量明细</summary><p class="muted">${esc(record.promptVersion||'版本未登记')} · ${esc(record.provenance?.mode||'来源声明未取得')} · 用量 ${record.provenance?.usage?esc(JSON.stringify(record.provenance.usage)):'未取得'}</p></details></details></article>`;
}
function todoOriginReport(p,record){return /^([a-f0-9]{8}-(?:[a-f0-9]{4}-){3}[a-f0-9]{12}):/.exec(p.todoId||'')?.[1]||record.report.viewChange?.previousReportId||null;}
function researchProgressCard(record){const progress=record.report?.researchProgress||[];return progress.length?'<details class="at-details" data-testid="research-progress"><summary>上轮研究待办的进展 · '+progress.length+' 项</summary><p class="muted">研究员根据本轮依据复核，完成不代表预测命中。</p>'+progress.map(p=>'<article class="at-claim"><strong>'+esc({completed:'已取得完成依据',unresolved:'仍未解决',capability_bound:'当前能力边界'}[p.state])+'</strong><p>'+esc(readable(p.reason))+'</p>'+p.evidenceIds.map(id=>'<button class="btn" data-evidence="'+esc(id)+'" data-cycle="'+esc(record.cycleId)+'">本轮依据</button>').join('')+(todoOriginReport(p,record)?'<button class="btn" data-previous="'+esc(todoOriginReport(p,record))+'">原待办报告</button>':'')+'</article>').join('')+'</details>':'';}
function conditionCard(record){
  const ledger=record.conditionLedger;
  if(!ledger)return '<p class="at-condition-note muted">以上为研究建议；没有检查回执时，是否满足保持未知。</p>';
  const rows=Array.isArray(ledger)?ledger:ledger.conditions||[];
  const machine=rows.filter(c=>c.kind==='deterministic');return machine.length?`<details class="at-conditions"><summary>机器可核查条件 · ${machine.length} 项</summary>${conditionRows(machine)}</details>`:'<p class="muted at-condition-note">研究待办由下一轮取证复核；本报告没有登记机器阈值。</p>';
}
function conditionTimingMarkup(c){const t=conditionTiming(c),qualification={forward:'窗口开始前已登记',during_window:'观察窗口中形成，不是前向条件',retrospective:'观察窗口结束后形成，属于复盘条件',unknown:'前向登记资格未知'}[t.timingQualification]||'前向登记资格未知',registration=t.registrationBasis==='service-recorded'?'服务登记 '+when(t.registeredAt):t.registrationBasis==='legacy-report-generated-at'?'旧报告生成 '+when(c.createdAt)+'；只能作时序参考，不能证明前向登记':'登记时间未知';return `<div class="at-condition-timing" data-condition="${esc(c.id)}" data-timing-qualification="${esc(t.timingQualification)}"><strong>${esc(qualification)}</strong><p>${esc(registration)}<br>观察窗口 ${Number.isSafeInteger(c.from)?when(c.from):'未知'} → ${Number.isSafeInteger(c.to)?when(c.to):'未知'}<br>期限 ${when(c.deadline)} · 检查资料 ${when(c.checkedAt)}</p><small>登记时点不证明用户当时已看到，也不证明预测效果。</small></div>`;}
function conditionRows(rows,cycleId){return rows.map(c=>`<article><div class="at-report-head"><strong>${esc(c.text||'待核查条件')}</strong><span class="at-status">${esc({unknown:c.kind==='manual'?'待人工核查':'未知',triggered:'已触发',not_triggered:'未触发',expired:'已到期'}[c.state]||'未知')}</span></div><p>${esc(readable(c.reason||'没有取得足以判断的新资料。'))}</p>${c.kind==='deterministic'?conditionTimingMarkup(c):''}<div class="at-evidence-actions">${c.parentReportId?`<button class="btn" data-previous="${esc(c.parentReportId)}">原判断</button>`:''}${cycleId?(c.evidenceIds||[]).map(id=>`<button class="btn" data-evidence="${esc(id)}" data-cycle="${esc(cycleId)}">检查依据</button>`).join(''):''}</div></article>`).join('');}
export function conditionChecksCard(rows,cycleId){rows=rows?.filter(c=>c.kind==='deterministic');if(!rows?.length)return '';const actionable=rows.filter(c=>c.kind==='deterministic'&&['triggered','expired'].includes(c.state));return `<details class="at-condition-checks" ${actionable.length?'open':''}><summary>机器可核查条件的本次检查 · ${rows.length} 项${actionable.length?' · '+actionable.length+' 项需要关注':''}</summary><p class="muted">状态依据实际检查回执；资料范围不足时保持未知。</p><div class="at-conditions">${conditionRows(rows,cycleId)}</div></details>`;}
function readerMarkup(){return '<dialog id="at-dialog" aria-label="当时报告与原始依据"><div class="at-dialog-tools"><button class="btn" id="at-close">关闭</button><button class="btn" id="at-export" disabled>导出当前记录</button></div><div id="at-detail"></div></dialog>';}
function roleResultCard(record){const slot=record.result,previous=slot?.previousId;return `<section class="at-evidence" data-testid="role-result"><h2>${esc(ROLES[record.role]?.name||record.role)} · 当时岗位结果</h2><p class="at-status">${esc(labels[slot?.status]||slot?.status||'未取得')}</p><p class="at-warning">本轮没有已接受报告，保留缺口。</p><p class="at-thesis">${esc(readable(slot?.report?.summary||(slot?.error?friendlyError(slot.error):'没有取得该岗位的研究结果。')))}</p><p class="muted">研究锚点 ${when(record.asOf)} · 本轮结束 ${when(record.endedAt)}</p>${taskCard(record.task,{compact:true})}${previous?`<button class="btn" data-previous="${esc(previous)}">上次已接受判断（非本轮）</button>`:''}<details><summary>完整当时岗位记录</summary><pre>${esc(JSON.stringify(record,null,2))}</pre></details></section>`;}
function bindReader(root,feedback){
  let disposed=false,serial=0,value=null;const life=new AbortController(),dialog=root.querySelector('#at-dialog'),detail=root.querySelector('#at-detail'),exportButton=root.querySelector('#at-export');
  const close=()=>{++serial;dialog.close();};root.querySelector('#at-close').onclick=close;dialog.addEventListener('cancel',()=>{++serial;},{signal:life.signal});
  exportButton.onclick=()=>{if(value)downloadRecord(value);};
  root.addEventListener('click',async event=>{
    const target=event.target.closest('[data-evidence],[data-previous],[data-run],[data-report],[data-disposition]');if(!target||disposed)return;
    const ticket=++serial;exportButton.disabled=true;
    try{let loaded,html;
      if(target.dataset.disposition){const run=await request('runs/'+encodeURIComponent(target.dataset.cycle));if(disposed||ticket!==serial)return;const role=target.dataset.disposition,slot=run.roles?.[role],acceptedId=run.row.accepted?.[role],id=acceptedId||slot?.id;if(!id){loaded={schemaVersion:'bitdesk.role-result.v1',cycleId:run.row.id,role,asOf:run.row.asOf,endedAt:run.row.endedAt||null,task:run.row.task,result:slot||null};html=roleResultCard(loaded);}else{loaded=await request('reports/'+encodeURIComponent(id));const unacceptedFollowup=acceptedId&&['failed','insufficient'].includes(slot?.status);html=(unacceptedFollowup?'<p class="at-warning" data-testid="role-followup-warning">本轮初稿已接受，后续追问未被接受；以下保留当时初稿。</p><details data-testid="role-followup"><summary>未接受的后续追问记录</summary><p>'+esc(slot.error?friendlyError(slot.error):readable(slot.report?.summary||'后续追问未取得可接受报告。'))+'</p><pre>'+esc(JSON.stringify(slot,null,2))+'</pre></details>':'')+reportCard(loaded,{historical:true});}}
      else if(target.dataset.previous||target.dataset.report){loaded=await request('reports/'+encodeURIComponent(target.dataset.previous||target.dataset.report));html=reportCard(loaded,{chief:loaded.role==='chief',historical:true});}
      else{const run=await request('runs/'+encodeURIComponent(target.dataset.cycle||target.dataset.run)),receipt=target.dataset.evidence?run.receipts?.find(r=>r.id===target.dataset.evidence):null;if(target.dataset.evidence&&!receipt)throw Error('原记录中没有这项依据；未替换为最新资料。');loaded=receipt||run;html=receipt?receiptCard(receipt):runCard(run);}
      if(disposed||ticket!==serial)return;value=loaded;detail.innerHTML=html;exportButton.disabled=false;if(!dialog.open)dialog.showModal();
    }catch(error){if(!disposed&&ticket===serial){feedback(friendlyError(error));exportButton.disabled=!value;}}
  },{signal:life.signal});
  return ()=>{disposed=true;++serial;life.abort();dialog.close();};
}
function downloadRecord(value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='team-'+(value.id||value.row?.id||value.run?.row?.id||'evidence')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const inputTime=value=>Number.isSafeInteger(value)?new Date(value+8*3600000).toISOString().slice(0,-1):'';
const parseInputTime=value=>value?Date.parse(value+'+08:00'):null;
export async function mountTask(root){
  if(!root)return ()=>{};const workspace=globalThis.UserWorkspace,selection=workspace?.read()||{origin:'chart',chartInterval:'15m',product:'perpetual',symbol:'BTCUSDT',from:null,to:null};
  const requested=workspace?.query().get('taskId');
  let disposed=false,poll=null,capabilities=null,state=null,draft=null,submitted=requested?{id:requested}:null,busy=false,uncertain=false,serial=0,readingSavedTask=!!requested;
  root.innerHTML=`<section class="at-task-compose"><header class="at-report-head"><div><h2>${selection.material?'研究所选事件':'研究所选市场区间'}</h2><p class="muted">先核对范围。结果保留在这个问题和研究历史中。</p></div><a class="btn" href="#/boardroom">首席决策台</a></header><div class="at-task-selection" data-testid="selected-scope">${esc(workspace?.describe(selection)||'尚未选择明确范围')}</div><form id="at-task-form"><label class="at-question" for="at-task-question">这次想核对什么？<textarea id="at-task-question" rows="2" maxlength="2000" placeholder="例如：这段上涨更接近主动买入，还是杠杆扩张？"></textarea></label><div class="at-form-grid at-scope-fields"><label>起始时间（北京时间）<input id="at-task-from" type="datetime-local" step="0.001" value="${inputTime(selection.from)}" ${selection.material?'':'required'}></label><label>结束时间（北京时间）<input id="at-task-to" type="datetime-local" step="0.001" value="${inputTime(selection.to)}" ${selection.material?'':'required'}></label></div>${selection.material?'<p class="muted">不填写时间时，只提交所选材料及保存的原件位置。资料时间不当作事件发生时间；摘要、摘录与事实核验分别判断。</p>':'<p class="muted">所选阅读周期和实际资料范围会随请求保存；若资料有限，结果会显示实际覆盖。</p>'}<div class="at-toolbar"><button class="btn primary" type="submit" id="at-task-review" disabled>核对研究范围</button><button class="btn" type="button" id="at-task-source-export">导出所选资料</button><a class="btn" href="#/archive">研究历史</a></div></form><p id="at-task-feedback" role="status">正在核对研究服务支持的范围…</p><div id="at-task-confirmation" hidden></div></section><div id="at-task-result" aria-live="polite"></div>${readerMarkup()}`;
  const find=id=>root.querySelector('#'+id),feedback=message=>{if(!disposed)find('at-task-feedback').textContent=message;},readerCleanup=bindReader(root,feedback);
  function updateDraftScope(){if(readingSavedTask)return;const from=Date.parse(find('at-task-from').value+'+08:00'),to=Date.parse(find('at-task-to').value+'+08:00'),current={...selection,from:Number.isFinite(from)?from:null,to:Number.isFinite(to)?to:null};root.querySelector('[data-testid="selected-scope"]').textContent='当前研究范围：'+workspace.describe(current);const notice=find('at-future-notice');if(notice)notice.hidden=!Number.isFinite(to)||to<Date.now();}
  find('at-task-form').addEventListener('input',updateDraftScope);const original=document.createElement('details');original.className='at-details';original.innerHTML='<summary>'+esc(selection.material?'原始事件材料 · '+selection.material.title:'原始资料选区')+'</summary><p>'+esc(workspace.describe(selection))+'</p>';root.querySelector('[data-testid="selected-scope"]').after(original);updateDraftScope();
  if(requested){find('at-task-form').hidden=true;root.querySelector('[data-testid="selected-scope"]').textContent='正在阅读指定任务；范围以原记录为准。';}
  if(!requested&&Number.isSafeInteger(selection.to)&&selection.to>=Date.now()){
    const notice=document.createElement('div');notice.className='at-warning';notice.id='at-future-notice';notice.innerHTML='<p>所选末棒还在形成，原结束时点在未来。研究只能使用实际取得的资料；你可以调整结束时点，再核对范围。</p><button class="btn" type="button" id="at-task-observed-end">按当前浏览时点结束窗口</button>';find('at-task-form').querySelector('.at-scope-fields').after(notice);
    notice.querySelector('button').onclick=()=>{find('at-task-to').value=inputTime(Date.now()-1);updateDraftScope();draft=null;find('at-task-confirmation').hidden=true;feedback('已明确调整本次请求的结束时点，原选区仍保留在所选资料导出中。请重新核对范围。');};
  }
  find('at-task-question').value=selection.material?(selection.material.kind==='legacy_report_event'?'复核历史条目“'+selection.material.title+'”的原文事实、当时背景与仍需核验的部分。区分报告生成时间和公开可得时间。':selection.material.kind==='discovered_event'?'核对报道材料“'+selection.material.title+'”：实际新增事实、BTC传导路径和最强反证分别是什么？区分发现摘要、已取得摘录与事实核验。':'核对“'+selection.material.title+'”的事实、可能影响与最强反证。'):'';
  function lock(locked){for(const input of find('at-task-form').querySelectorAll('input,textarea'))input.disabled=locked;find('at-task-review').disabled=locked||!!taskCapabilityIssue(capabilities,{taskMode:selection.material?'narrative':'window'})||!!state?.active||!!state?.paused;}
  find('at-task-form').addEventListener('input',()=>{if(!busy&&!uncertain&&!submitted){draft=null;find('at-task-confirmation').hidden=true;}});
  find('at-task-source-export').onclick=()=>downloadRecord({selection,source:'user-selected-material',exportedAt:new Date().toISOString()});
  async function refresh(){
    if(disposed)return;try{state=await request('status');if(disposed)return;capabilities=state.capabilities;lock(!!submitted||busy);
      if(submitted){const run=await request('runs/'+encodeURIComponent(submitted.id));if(disposed)return;if(run.row?.id!==submitted.id)throw Error('返回的研究身份与本次任务不一致。');let chief=null,readerIssue='';if(run.row.accepted?.chief){try{chief=await request('reports/'+encodeURIComponent(run.row.accepted.chief));if(chief.id!==run.row.accepted.chief||chief.task?.contextId!==run.row.task?.contextId)throw Error('报告与这个问题的版本不一致。');}catch(error){chief=null;readerIssue=friendlyError(error);}}
        if(disposed)return;
        if(readingSavedTask){
          // A saved task is independent of this browser's current chart selection.
          const task=run.row.task||{},titles=[...(task.materialRefs||[]).map(ref=>run.materials?.find(m=>m.ref?.id===ref.id&&m.ref?.source===ref.source)?.content?.title),...(task.providedMaterials||[]).map(m=>m.content?.title||m.content?.report?.title)].filter(Boolean);
          original.innerHTML='<summary>'+esc('本次问题与研究范围'+(titles.length?' · '+titles.join(' / '):''))+'</summary><p>'+esc(run.row.question||'核对市场变化')+'</p>'+taskCard(task,{compact:true});
        }
        root.querySelector('.at-task-compose').classList.add('is-reading');find('at-task-form').hidden=true;root.querySelector('[data-testid="selected-scope"]').hidden=true;find('at-task-confirmation').hidden=true;find('at-task-result').innerHTML=(chief?reportCard(chief,{chief:true})+`<details class="at-task-audit"><summary>本次范围、岗位结果与原始材料</summary>${runCard(run)}</details>`:runCard(run))+(readerIssue?`<p class="at-warning">已接受报告暂时无法读取：${esc(readerIssue)}。原任务保留，未替换为其他判断。</p>`:'')+`<div class="at-toolbar"><button class="btn" id="at-task-record-export">导出完整任务记录</button>${run.row.terminal?'<button class="btn" id="at-task-new">重新核对新问题</button>':'<button class="btn" id="at-task-cancel">取消这个研究</button>'}</div>`;find('at-task-record-export').onclick=async()=>{try{const exported=await request('runs/'+encodeURIComponent(submitted.id)+'/export');const {contentHash,...bundle}=exported;if(exported.run?.row?.id!==submitted.id||globalThis.BitContentIdentity.contentId(bundle)!==contentHash||Object.values(exported.run.row.accepted||{}).some(id=>!exported.reports?.[id]))throw Error('完整导出与本次任务的记录不一致。');downloadRecord(exported);}catch(error){feedback(friendlyError(error));}};
        if(run.row.terminal){feedback('本次'+(labels[run.row.terminal]||run.row.terminal)+(run.row.reason?'：'+friendlyError(run.row.reason):'')+'。原范围与当时材料已保留。');find('at-task-new').onclick=()=>{submitted=null;draft=null;uncertain=false;readingSavedTask=false;original.innerHTML='<summary>'+esc(selection.material?'原始事件材料 · '+selection.material.title:'原始资料选区')+'</summary><p>'+esc(workspace.describe(selection))+'</p>';find('at-task-result').innerHTML='';root.querySelector('.at-task-compose').classList.remove('is-reading');find('at-task-form').hidden=false;find('at-task-confirmation').hidden=true;globalThis.history.replaceState(null,'','#/research?view=window');root.querySelector('[data-testid="selected-scope"]').hidden=false;updateDraftScope();lock(false);feedback('已保留原任务。修改问题或范围后，再核对新请求。');};return;}
        find('at-task-cancel').onclick=async()=>{try{await request('cancel',{id:submitted.id});feedback('正在取消并核对退出；已取得材料会保留。');}catch(error){feedback(friendlyError(error));}};feedback('研究正在进行，'+(state.active?.stage?'团队正在核对各领域材料。':'等待状态更新。'));poll=setTimeout(refresh,3000);
      }
    }catch(error){feedback(friendlyError(error));}
  }
  find('at-task-form').onsubmit=async event=>{event.preventDefault();if(busy||submitted)return;try{
    const values={...selection,from:parseInputTime(find('at-task-from').value),to:parseInputTime(find('at-task-to').value)};
    if(selection.material&&(values.from===null)!==(values.to===null))throw Error('事件窗口请同时填写起止时间，或同时留空。');
    if(values.to!==null&&values.to>=Date.now())throw Error('结束时点尚未来到。请明确调整结束时点后再核对；未静默缩短原选区。');
    draft=agentTaskRequest(values,find('at-task-question').value);const issue=taskCapabilityIssue(capabilities,draft);if(issue)throw Error(issue);
    find('at-task-confirmation').innerHTML=taskCard({...draft,dataCutoff:null})+`<p class="at-warning">${draft.taskMode==='narrative'?'所选事件与原报告作为材料提交，来源未独立核验。':'历史窗口会使用这次取得的材料；不保证这些材料在窗口当时已公开。'} 首席的当前市场判断保留原版本。</p><div class="at-toolbar"><button class="btn primary" id="at-task-confirm">开始这个问题的研究</button><button class="btn" id="at-task-edit">修改范围</button></div>`;find('at-task-confirmation').hidden=false;
    find('at-task-edit').onclick=()=>{draft=null;find('at-task-confirmation').hidden=true;feedback('修改后重新核对范围。');};
    find('at-task-confirm').onclick=submit;feedback('请核对以上范围与材料，再开始研究。');find('at-task-confirmation').scrollIntoView({block:'nearest'});
  }catch(error){draft=null;feedback(friendlyError(error));}};
  async function submit(){if(!draft||busy||submitted)return;const ticket=++serial;busy=true;lock(true);find('at-task-confirm').disabled=true;feedback('正在提交已核对的范围与原材料…');
    try{const accepted=await request('runs',draft);if(disposed||ticket!==serial)return;if(!acceptedTaskMatches(draft,accepted))throw Error('服务接受的范围与所选请求不一致。请到研究历史核对本次任务，勿重复创建。');submitted=accepted;uncertain=false;globalThis.history.replaceState(null,'','#/research?view=window&taskId='+encodeURIComponent(accepted.id));find('at-task-confirmation').innerHTML=taskCard(accepted.task);feedback('研究已开始，岗位将按本次范围独立核对材料。');await refresh();}
    catch(error){if(!disposed&&ticket===serial){uncertain=!(error.httpStatus>=400&&error.httpStatus<500);feedback(uncertain?'提交回执未确认：'+friendlyError(error)+' 原请求身份已保留；再次核对使用同一请求，不创建第二轮。':friendlyError(error));if(find('at-task-confirm')){find('at-task-confirm').disabled=false;find('at-task-confirm').textContent=uncertain?'核对这次请求':'重新提交已核对范围';}if(find('at-task-edit'))find('at-task-edit').disabled=uncertain;}}
    finally{if(!disposed&&ticket===serial){busy=false;lock(!!submitted||uncertain);}}
  }
  if(local()){connectPresence();await refresh();if(!disposed&&!submitted){const issue=taskCapabilityIssue(capabilities,{taskMode:selection.material?'narrative':'window'});feedback(issue||(state?.active?'另一项研究正在进行，请等待完成或取消后再开始。':state?.paused?'研究已暂停：'+friendlyError(state.paused):'研究服务支持本次任务。先核对范围与原材料。'));lock(false);}}
  else feedback('当前连接提供资料与记录阅读。连接你的研究服务后，可以执行这类问题。');
  return ()=>{disposed=true;++serial;clearTimeout(poll);readerCleanup();};
}
function currentAttempt(state){const active=state.active?.task?.taskMode&&state.active.task.taskMode!=='current'?null:state.active,last=state.lastAttempt?.task?.taskMode&&state.lastAttempt.task.taskMode!=='current'?null:state.lastAttempt;return active||last;}
function teamRows(state){return Object.entries(ROLES).map(([role,r])=>{const accepted=state.specialists?.[role],attempt=currentAttempt(state)?.roles?.[role];return `<a class="at-role-row" href="#/agent-${role}"><span class="at-role-name">${esc(r.name)}<small>${esc(r.area)}</small></span><span class="at-role-summary">${esc(attempt?labels[attempt.status]||attempt.status:accepted?labels[accepted.report.status]:'尚未研究')}<small>${attempt?.error?esc(friendlyError(attempt.error)):accepted?'资料截至 '+when(accepted.asOf):'等待真实材料'}</small></span><span class="at-role-arrow" aria-hidden="true">→</span></a>`;}).join('');}
function stateLine(state){const stage=state.active?.stage||'',role=stage.split(':')[0],name=ROLES[role]?.name,phase=name?name+'正在独立研究':({discovery:'正在核对各领域资料',chief:'首席正在综合各岗位判断','chief-after-clarification':'首席正在整理追问结果','semantic-review':'正在审核解释与引用','chief-revision':'首席正在修订审核发现的问题',cancelling:'正在取消并核对退出'}[stage]||'正在研究');return state.active?`${esc(state.active.task?.taskMode&&state.active.task.taskMode!=='current'?taskNames[state.active.task.taskMode]+' · ':'')}${esc(phase)} · 资料截至 ${when(state.active.asOf)}`:state.paused?'已暂停：'+esc(friendlyError(state.paused)):state.lastAttempt?.status==='failed'?'最近一轮未完成：'+esc(friendlyError(state.lastAttempt.reason))+'。最后已接受观点保留原时间。':'当前没有在途研究';}
export async function mount(root,role){if(!root)return ()=>{};if(!local()){root.innerHTML='<section class="at-empty"><h2>市场解读</h2><p>当前连接提供市场资料和保存的报告。连接你的研究服务后，可以更新团队判断。</p><a href="#/market?view=chart">查看市场资料 →</a></section>';return ()=>{};}connectPresence();let disposed=false,poll=null,loading=false;
  root.innerHTML='<div class="at-operating"><div class="at-toolbar"><button class="btn primary" id="at-update">现在更新</button><button class="btn" id="at-cancel">取消本轮</button><a class="btn" href="#/research?view=window">指定问题研究</a><a class="btn" href="#/settings">设置研究节奏</a><a class="btn" href="#/archive">研究历史</a></div><label class="at-question" for="at-question">希望这轮解释什么（可选）<input id="at-question" maxlength="2000" placeholder="例如：这次上涨有哪些支持和反证？"></label><p id="at-feedback" role="status"></p><p id="at-state" class="muted"></p><details id="at-status-diagnostics" class="at-details" hidden><summary>运行诊断</summary><pre style="white-space:pre-wrap;overflow-wrap:anywhere"></pre></details></div><div id="at-body"></div>'+readerMarkup();
  if(role==='archive'){root.querySelector('.at-question').hidden=true;root.querySelector('#at-update').hidden=true;root.querySelector('#at-cancel').hidden=true;const back=document.createElement('a');back.href='#/boardroom';back.className='btn';back.textContent='首席决策台';root.querySelector('.at-toolbar').prepend(back);}
  let rendered='',submittedRun=null,activeRun=null,paused=false,currentDraft=null,currentBusy=false,currentUncertain=false,terminalFailure=null;
  const feedback=message=>{if(!disposed)root.querySelector('#at-feedback').textContent=message;};
  const readerCleanup=bindReader(root,feedback);
  function currentControls(){if(disposed)return;root.querySelector('#at-question').disabled=currentBusy||currentUncertain;const update=root.querySelector('#at-update');update.disabled=currentBusy||(!currentUncertain&&(!!activeRun||paused));update.textContent=currentUncertain?'核对这次请求':'现在更新';}
  async function refresh(){if(loading||disposed)return;loading=true;try{const value=await request('status');if(disposed)return;activeRun=value.active?.id||null;paused=!!value.paused;root.querySelector('#at-state').innerHTML=stateLine(value);root.querySelector('#at-cancel').disabled=!value.active;currentControls();
    if(submittedRun&&!value.active){const terminal=value.history.find(r=>r.id===submittedRun);if(terminal&&terminal.status!=='running'){terminalFailure=terminal.reason?{id:terminal.id,status:terminal.status,reason:terminal.reason}:null;const sameFailure=terminal.reason&&terminal.id===value.lastAttempt?.id&&terminal.reason===value.lastAttempt?.reason&&value.lastAttempt?.status==='failed';feedback(sameFailure?'':'本轮'+(labels[terminal.status]||terminal.status)+(terminal.reason?'：'+friendlyError(terminal.reason):'')+'。');submittedRun=null;}}
    const diagnostics=root.querySelector('#at-status-diagnostics'),failures=[value.paused?{source:'paused',reason:value.paused}:null,value.lastAttempt?.reason?{source:'lastAttempt',id:value.lastAttempt.id,status:value.lastAttempt.status,reason:value.lastAttempt.reason}:null,terminalFailure&&!(terminalFailure.id===value.lastAttempt?.id&&terminalFailure.reason===value.lastAttempt?.reason)?{source:'submittedRun',...terminalFailure}:null].filter(Boolean);diagnostics.hidden=!failures.length;diagnostics.querySelector('pre').textContent=JSON.stringify(failures,null,2);
    const body=root.querySelector('#at-body');let html;if(role==='chief')html=reportCard(value.chief,{chief:true})+conditionChecksCard(value.conditions?.items||value.conditions,value.conditions?.cycleId||value.lastAttempt?.id)+'<section class="at-coverage"><header class="at-report-head"><div><h2>各领域的最新研究</h2><p class="muted">进入岗位核对原依据；首席采用的当时版本另列在报告中。</p></div><a href="#/market?view=chart">市场资料 →</a></header>'+teamRows(value)+'</section>';
    else if(role==='archive')html='<section class="at-history"><h2>研究轮次与状态</h2>'+value.history.map(row=>`<div class="at-history-row"><span><strong>${esc(taskNames[taskMode(row)]||'当前市场更新')}</strong> · ${when(row.asOf)}<small>${esc(row.question||'核对市场变化')}<br>${esc(labels[row.status]||row.status)}${row.reason?' · '+esc(friendlyError(row.reason)):''}</small></span><button class="btn" data-run="${esc(row.id)}">查看当时材料</button>${row.accepted?.chief?`<button class="btn" data-report="${esc(row.accepted.chief)}">首席报告</button>`:''}${taskMode(row)!=='current'?`<a class="btn" href="#/research?view=window&taskId=${encodeURIComponent(row.id)}">打开这个问题</a>`:''}</div>`).join('')+(value.history.length?'':'<p class="muted">还没有研究轮次。发起研究后，结果与缺口会一并保留。</p>')+'</section>';
    else {const attempt=currentAttempt(value)?.roles?.[role],accepted=value.specialists?.[role],current=accepted||attempt?.report&&{role,report:attempt.report,asOf:value.active?.asOf||value.lastAttempt?.asOf,generatedAt:null,cycleId:value.active?.id||value.lastAttempt?.id};html=`<section class="at-role-intro"><a href="#/boardroom">← 首席决策台</a><p>${esc(ROLES[role]?.area||'')}</p><p>${attempt?.error?'本轮未完成：'+esc(friendlyError(attempt.error)):attempt?.status==='insufficient'?'本轮材料不足'+(accepted?'，以下保留最后已接受观点。':'，以下列出当前缺口。'):''}</p></section>`+reportCard(current);}
    if(html!==rendered){const open=[...body.querySelectorAll('details[open]')].map(d=>d.querySelector('summary')?.textContent);body.innerHTML=html;for(const d of body.querySelectorAll('details'))if(open.includes(d.querySelector('summary')?.textContent))d.open=true;rendered=html;}
  }catch(error){if(!currentUncertain)feedback(friendlyError(error));}finally{loading=false;}}
  root.querySelector('#at-update').onclick=async()=>{if(currentBusy||disposed||(!currentUncertain&&(activeRun||paused)))return;currentDraft??={requestId:crypto.randomUUID(),question:root.querySelector('#at-question').value.trim()};currentBusy=true;currentControls();try{feedback(currentUncertain?'正在核对同一次请求的回执…':'正在核对页面连接与调用预算…');const accepted=await request('runs',currentDraft);if(disposed)return;if(typeof accepted.id!=='string'||!accepted.id)throw Error('研究服务没有返回明确的任务身份。');submittedRun=accepted.id;terminalFailure=null;currentDraft=null;currentUncertain=false;feedback('本轮已开始，岗位正在独立核对材料。');await refresh();}catch(error){if(!disposed){currentUncertain=!(error.httpStatus>=400&&error.httpStatus<500);if(!currentUncertain)currentDraft=null;feedback(currentUncertain?'提交回执未确认：'+friendlyError(error)+' 原请求身份已保留；再次核对使用同一请求，不创建第二轮。':friendlyError(error));}}finally{currentBusy=false;currentControls();}};
  root.querySelector('#at-cancel').onclick=async()=>{try{if(!activeRun)return;await request('cancel',{id:activeRun});feedback('正在取消并核对本轮进程退出。');await refresh();}catch(error){feedback(error.message);}};
  await refresh();poll=setInterval(refresh,3000);return ()=>{disposed=true;clearInterval(poll);readerCleanup();};
}
export async function mountSettings(root){if(!root)return ()=>{};if(!local()){root.textContent='研究运行设置需要连接你的研究服务。';return ()=>{};}connectPresence();let disposed=false,config;
  root.innerHTML='<h2>智囊团研究节奏</h2><p class="muted">页面关闭或连接中断后停止更新；电脑睡眠期间不补跑。</p><form id="at-settings-form"><div class="at-form-grid"><label class="at-toggle"><input type="checkbox" name="enabled"> 开启自动研究</label><label>更新方式<select name="mode"><option value="interval">固定间隔</option><option value="daily">每天指定时间</option></select></label><label>间隔（分钟）<input type="number" name="intervalMinutes" min="1" max="1440" required></label><label>每日时间（逗号分隔）<input name="dailyTimes" placeholder="09:00,18:00" required></label><label>时区<input name="timezone" value="Asia/Shanghai" required></label><label>研究窗口（小时）<input type="number" name="windowHours" min="1" max="2160" required></label><label>每轮调用上限<input type="number" name="maxCalls" min="7" max="20" required></label><label>本地日调用上限<input type="number" name="dailyCalls" min="7" max="500" required></label></div><div class="at-toolbar"><button class="btn primary" type="submit">保存研究设置</button><button class="btn" type="button" id="at-auth">检查模型连接</button><a class="btn" href="#/boardroom">打开市场解读</a></div></form><p id="at-settings-feedback" role="status"></p><div id="at-preview"></div><details><summary>运行方式与额度说明</summary><p>全部模型步骤使用本机官方 Codex CLI 的 ChatGPT 登录额度；不配置模型 Key、不自动切换付费接口。调用次数是本地预算，套餐剩余额度未取得时不猜测。节奏短于研究时长会跳过忙时段；保存的新配置从下一轮生效。</p></details>';
  const form=root.querySelector('form'),message=x=>{if(!disposed)root.querySelector('#at-settings-feedback').textContent=x;};
  const recovery=document.createElement('section');recovery.className='at-warning';recovery.hidden=true;recovery.id='at-cleanup-recovery';recovery.innerHTML='<h3>研究等待退出核对</h3><p>上一轮未能确认所有研究进程已退出。核对本机原进程身份后可以解除暂停；原失败记录与最后已接受观点会保留。</p><button class="btn" type="button" id="at-recover-cleanup">核对退出并解除暂停</button>';
  root.querySelector('#at-settings-feedback').after(recovery);let recovering=false;
  async function refreshRecovery(){try{const state=await request('status');if(disposed)return;recovery.hidden=state.paused!=='cleanup_uncertain';recovery.querySelector('button').disabled=recovering||!!state.active;return state;}catch(error){message(friendlyError(error));}}
  recovery.querySelector('button').onclick=async()=>{if(recovering||disposed)return;recovering=true;recovery.querySelector('button').disabled=true;message('正在核对上一轮记录的进程身份与退出状态…');try{await request('recover-cleanup',{});if(disposed)return;const state=await refreshRecovery();if(state?.paused)throw Error(state.paused);message('已核对原研究进程退出并解除暂停。原失败与报告保留；自动研究设置未改变。');}catch(error){message(friendlyError(error));}finally{recovering=false;if(!disposed)await refreshRecovery();}};
  const readDraft=()=>{const next={...config,enabled:form.elements.enabled.checked,mode:form.elements.mode.value,dailyTimes:form.elements.dailyTimes.value.split(',').map(x=>x.trim()).filter(Boolean),timezone:form.elements.timezone.value.trim()};for(const k of ['intervalMinutes','windowHours','maxCalls','dailyCalls'])next[k]=Number(form.elements.namedItem(k).value);return validateConfig(next);};
  const preview=(times,draft=false)=>{root.querySelector('#at-preview').innerHTML='<h3>'+(draft?'未保存草稿 · ':'已保存设置 · ')+'接下来三次计划时间</h3>'+lists(times.map(when))+'<p class="muted">开启自动研究并保持页面连接时执行。暂停不会取消当前轮；取消请在首席页面操作。</p>';};
  try{const value=await request('config');if(disposed)return ()=>{};config=value.config;for(const [k,v]of Object.entries(config)){const field=form.elements.namedItem(k);if(field){if(k==='enabled')field.checked=v;else field.value=Array.isArray(v)?v.join(','):v;}}preview(value.nextSlots);}catch(error){message(error.message);}
  const draftPreview=()=>{if(!config)return;try{preview(nextSlots(readDraft(),Date.now()),true);}catch{root.querySelector('#at-preview').textContent='草稿尚不完整；请填写有效时间和时区。已保存设置未改变。';}};form.addEventListener('input',draftPreview);form.addEventListener('change',draftPreview);
  form.onsubmit=async event=>{event.preventDefault();if(!config)return;
    try{const value=await request('config',readDraft());if(disposed)return;config=value.config;preview(value.nextSlots);message(config.enabled?'已保存并开启，下一轮使用新设置。':'已保存，自动研究已暂停。');}catch(error){message(error.message==='config_version_conflict'?'另一页面已修改设置，请重新打开后核对。':error.message);}};
  root.querySelector('#at-auth').onclick=async()=>{try{message('正在检查官方本地登录…');const value=await request('auth',{});message(value.message);}catch(error){message(error.message);}};
  await refreshRecovery();
  return ()=>{disposed=true;};
}

export async function mountEventReading(root){
  let disposed=false,serial=0,reading=null;
  root.innerHTML='<header class="at-report-head"><div><h2>团队最近发现的事件材料</h2><p>先看实际取得的报道，再看岗位与首席如何解释。</p></div><button class="btn" id="at-events-refresh">刷新材料</button></header><p id="at-events-feedback" role="status">正在读取已保存材料，不启动模型…</p><div id="at-events-body"></div>'+readerMarkup();
  const feedback=text=>{if(!disposed)root.querySelector('#at-events-feedback').textContent=text;},cleanup=bindReader(root,feedback);
  const safeUrl=value=>{try{const u=new URL(value);return u.protocol==='https:'?u.href:null;}catch{return null;}};
  async function refresh(){const ticket=++serial;try{const value=await request('events');if(disposed||ticket!==serial)return;if(!Array.isArray(value.items)||!Array.isArray(value.sources)||!['not_researched','not_acquired','sources_unavailable','no_materials_found','materials_found'].includes(value.state))throw Error('当前事件资料结构不完整，暂不能判断是否有新材料。');reading=value;
    const messages={not_researched:'尚未做过团队研究',not_acquired:'本轮尚未取得事件材料',sources_unavailable:'本轮事件来源读取失败',no_materials_found:'本轮未发现可列示材料',materials_found:'以下是团队实际取得的报道材料，未独立认证全部事实'};
    feedback(messages[value.state]||'材料状态未知');
    root.querySelector('#at-events-body').innerHTML=`<p class="muted">团队资料截止 ${when(value.asOf)}${value.asOf?' · 距今 '+Math.max(0,Math.floor((Date.now()-Date.parse(value.asOf))/60000))+' 分钟':''} · ${esc(labels[value.runStatus]||value.runStatus||'尚未研究')}</p><p class="at-warning">报道时间与事件发生时间不同。未发现、未取得或读取失败均不表示市场没有事件；本页只读取保存资料。</p><div class="at-toolbar"><a class="btn" href="#/agent-events">事件研究员</a><a class="btn" href="#/boardroom">首席决策台</a>${value.analyst?`<button class="btn" data-report="${esc(value.analyst.id)}">最后已接受岗位判断 · ${when(value.analyst.asOf)}</button>`:''}${value.chief?`<button class="btn" data-report="${esc(value.chief.id)}">最后已接受首席 · ${when(value.chief.asOf)}</button>`:''}</div>${value.items.map((item,index)=>{const url=safeUrl(item.url),article=item.article;return `<article class="rd-event at-event-material"><div class="rd-event-main"><span class="rd-tag">${esc(item.sourceType==='publisher-rss'?'发布方RSS摘要':'已存报道材料')}</span><h3>${esc(item.title)}</h3><p>${esc(item.summary||'原条目未提供摘要。')}</p><p class="muted">条目标示报道时间 ${when(item.publishedAt)} · 事件发生 ${when(item.occurredAt)}</p><p>${article?article.ok?'已取得网页文字摘录 · '+article.characters+' 字符；全文完整性未知':'网页摘录未取得：'+esc(friendlyError(article.error)):'本轮未补读网页文字；当前仅有发现材料。'}</p><div class="at-toolbar">${url?`<a class="btn" href="${esc(url)}" target="_blank" rel="noopener noreferrer">发布方链接 ↗</a>`:''}<button class="btn" data-evidence="${esc(item.receiptId)}" data-cycle="${esc(value.cycleId)}">发现原件</button>${article?`<button class="btn" data-evidence="${esc(article.receiptId)}" data-cycle="${esc(value.cycleId)}">取文结果</button>`:''}<button class="btn primary" data-current-event="${index}">研究此材料 →</button></div></div></article>`;}).join('')}<details class="at-details"><summary>本轮来源读取与覆盖 · ${value.sources.length} 项</summary>${value.sources.map(source=>'<p>'+esc(source.ok?(source.usable?'已取得可用材料':'已读取，材料有限'):'读取失败：'+friendlyError(source.error))+' · '+esc((source.sourceChain||[]).join('；'))+'</p>').join('')||'<p>本轮还没有事件来源回执。</p>'}</details>`;
  }catch(error){if(!disposed&&ticket===serial)feedback(friendlyError(error));}}
  root.querySelector('#at-events-refresh').onclick=refresh;
  root.addEventListener('click',event=>{const button=event.target.closest('[data-current-event]');if(!button||disposed)return;const item=reading?.items?.[Number(button.dataset.currentEvent)];if(item)globalThis.UserWorkspace.begin({origin:'events',material:{kind:'discovered_event',title:item.title,materialRef:item.materialRef}});});
  await refresh();return ()=>{disposed=true;++serial;cleanup();};
}
