/* 分析层员工页静态视图数据（后续可改为 fetch 云端 API） */
const AGENT_VIEWS = {
  chief: {
    stance: "谨慎做多",
    stanceColor: "var(--warn)",
    confidence: 68,
    oneliner: "综合四位结论，环境偏多但尚未极端；建议 30% 试仓，盯守 63.7k 止损与 21:30 CPI。",
    kpis: [
      { label: "综合结论", value: "试多 30%", delta: "待 CPI 验证", good: true },
      { label: "置信度", value: "68%", delta: "B+", good: true },
      { label: "主策略", value: "回踩做多", delta: "入场 63.9-64.2k" },
      { label: "反对票", value: "0", delta: "四位一致" },
      { label: "二层共识", value: "高", delta: "5/5" },
      { label: "风险预算", value: "30%", delta: "本日上限" },
    ],
    reasoning: [
      "<strong>环境评估员</strong>：4H 趋势扩张初期，BB 口径 2.1%→4.6%，VIX/MOVE 未出现极端冲击，方向偏多。",
      "<strong>盘口流动性官</strong>：63.8k 存在未触及流动性池，昨晚 SFP 下影已形成，利于回踩做多。",
      "<strong>衍生品情报官</strong>：Funding +0.012%、OI 6h +4.3%，多头略拥挤但未极端。",
      "<strong>风控官</strong>：账户风险占用 18%，可开仓对应 1.2% 风险，允许 30% 试仓。",
    ],
    suggestions: [
      { label: "试多 30%", type: "ok" },
      { label: "入场 63.9-64.2k", type: "" },
      { label: "止损 63.7k", type: "warn" },
      { label: "目标 66.5k", type: "" },
      { label: "CPI 高于预期即清仓", type: "danger" },
    ],
    history: [
      ["今日 09:12", "试多 30%", "综合四位结论，环境偏多、流动性支持回踩、衍生品未极端、风控允许。"],
      ["昨日 17:40", "观望", "震荡末端无明确方向，等待扩张信号。"],
      ["昨日 09:15", "空仓观望", "四位意见分歧，风控评分下调至 C。"],
      ["前日 21:30", "试空", "基差升水偏高 + 多头极端拥挤，高位做空风险收益比佳。"],
    ],
    subordinates: true,
  },
  flow: {
    stance: "回踩买方占优",
    stanceColor: "var(--ok)",
    confidence: 74,
    oneliner: "上方 65.2k-65.4k 是 VAH 堆积区，下方 63.8k 存在未触及流动性池；昨晚 SFP 下影已形成。",
    kpis: [
      { label: "POC", value: "64,620", delta: "价值中轴" },
      { label: "VAH", value: "65,280", delta: "价值区上沿" },
      { label: "VAL", value: "63,940", delta: "价值区下沿" },
      { label: "最近 SFP", value: "下影", delta: "+3.2 小时前", good: true },
      { label: "Imbalance", value: "+62%", delta: "买压占优", good: true },
      { label: "清算池", value: "63.8k", delta: "下方 $4.2 亿" },
    ],
    reasoning: [
      "<strong>成交量分布</strong>：昨日 VP 显示 65.2k 有异常堆积，是短期强阻力。",
      "<strong>SFP 形态</strong>：63.5k 曾出现假突破下影，Liquidity Grab 完成。",
      "<strong>Imbalance</strong>：近 3 根 1H 买方失衡持续 > 60%，吸收中。",
      "<strong>清算图</strong>：63.8k 堆积约 $4.2 亿潜在空头清算，回踩此处容易反抽。",
    ],
    suggestions: [
      { label: "回踩 63.8-63.9k 做多", type: "ok" },
      { label: "止损 63.5k 下", type: "warn" },
      { label: "跟踪 65.2k 压力", type: "" },
    ],
    history: [
      ["今日 09:04", "回踩买方占优", "63.8k 存在流动性池 + SFP 下影，做多性价比高。"],
      ["昨日 22:10", "上方 VAH 压制", "65.2k 堆积量是上周均量的 3 倍，短线难穿。"],
      ["昨日 13:00", "均衡震荡", "POC 稳定在 64.6k，买卖 Imbalance 接近 0。"],
      ["前日 19:30", "上影 SFP", "65.0k 向上猎流动性后回落，短期看空。"],
    ],
  },
  deriv: {
    stance: "中性偏多",
    stanceColor: "var(--info)",
    confidence: 62,
    oneliner: "资金费率 +0.012%、OI 过去 6h +4.3%，主动买盘略占优；Top Trader 偏多但未极端。",
    kpis: [
      { label: "BTC Funding", value: "+0.012%", delta: "中性偏多" },
      { label: "OI 6h 变化", value: "+4.3%", delta: "温和累积", good: true },
      { label: "主动买卖比", value: "1.12", delta: "买盘略占优", good: true },
      { label: "基差年化", value: "+6.4%", delta: "温和升水", good: true },
      { label: "Top Trader", value: "1.21", delta: "持仓偏多" },
      { label: "多空比", value: "1.18", delta: "历史 52 分位" },
    ],
    reasoning: [
      "<strong>Funding</strong>：所有主流永续 Funding 均在 0.01% 附近，未到 0.03% 极端线。",
      "<strong>OI 变化</strong>：BTC OI 过去 6h 温和上涨 4.3%，配合价格同向上行——真实累积。",
      "<strong>主动买卖量</strong>：Buy/Sell ratio 维持在 1.12，主动买盘略占优但未失衡。",
      "<strong>基差</strong>：季度合约年化升水约 6.4%，属于健康风险偏好而非极端抢多。",
    ],
    suggestions: [
      { label: "可顺势做多", type: "ok" },
      { label: "Funding > 0.03% 则减仓", type: "warn" },
      { label: "观察 CME 缺口回补", type: "" },
    ],
    history: [
      ["今日 09:06", "中性偏多", "Funding 未极端，OI 温和累积，方向偏多。"],
      ["昨日 18:00", "多头拥挤预警", "Funding 触达 0.028%，暂缓加仓。"],
      ["昨日 10:30", "空头挤压", "OI 6h -2.1% 且价格上涨，空头主动止损。"],
      ["前日 15:00", "Top Trader 分歧", "账户比偏多但持仓比回落，大户方向不一致。"],
    ],
  },
  risk: {
    stance: "B+ 允许试仓",
    stanceColor: "var(--ok)",
    confidence: 85,
    oneliner: "账户风险占用 18%，本日 PnL +0.8%，距离日内 3% 风险预算仍有缓冲；CPI 前不超 30%。",
    kpis: [
      { label: "账户余额", value: "$50,320", delta: "+0.64% 今日", good: true },
      { label: "当前风险", value: "1.8%", delta: "占用 18% 预算" },
      { label: "本日 PnL", value: "+0.8%", delta: "+$402", good: true },
      { label: "最大回撤", value: "-3.2%", delta: "近 30 日" },
      { label: "可开仓风险", value: "1.2%", delta: "对应 $600 止损" },
      { label: "风控评分", value: "B+", delta: "允许试仓" },
    ],
    reasoning: [
      "<strong>风险预算</strong>：本日总上限 3%，已占用 18%（约 0.54%），剩余 2.46%。",
      "<strong>回撤状态</strong>：近 30 日最大回撤 -3.2%，距离警戒线 -6% 有缓冲。",
      "<strong>黑天鹅雷达</strong>：Funding 未极端、交易所余额平稳、ETF 流入正常。",
      "<strong>CPI 约束</strong>：21:30 数据前单笔仓位不超过账户 30%。",
    ],
    suggestions: [
      { label: "允许试仓 30%", type: "ok" },
      { label: "单笔止损 $600", type: "" },
      { label: "CPI 前冻结加仓", type: "warn" },
    ],
    history: [
      ["今日 09:08", "B+ 允许试仓", "风险占用 18%，可开仓对应 1.2% 风险。"],
      ["昨日 22:00", "A- 无限制", "风险占用 8%，账户状态健康。"],
      ["昨日 11:15", "C 降级", "连续 3 笔亏损，累计风险 2.7%，剩余预算紧张。"],
      ["前日 20:00", "D 冻结", "单日风险 > 3%，风控官自动冻结新仓 2 小时。"],
    ],
  },
  env: null,
};
