/* Research reading surface. Cloud reads only; model work stays in user sessions. */
const ResearchDesk = (() => {
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels={confirmed:'已核实',reported:'单源报道',unverified:'待核实',supported:'证据支持',contested:'存在分歧',untested:'尚未验证',primary:'原始披露',media:'专业媒体',social:'社媒样本',market_data:'市场数据'};
  let disposer=null;
  function time(v,precision){if(!v||!Number.isFinite(Date.parse(v)))return '时间未明确';if(precision==='date')return v+' · 仅日期';return new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})+' 北京时间';}
  function tag(s){return `<span class="rd-tag rd-tag--${esc(s)}">${esc(labels[s]||s)}</span>`;}
  function empty(title,detail){return `<div class="rd-empty"><span aria-hidden="true">—</span><h3>${esc(title)}</h3><p>${esc(detail)}</p></div>`;}
  function section(id,title,detail,body){return `<section class="rd-panel" id="${id}"><header class="rd-section-head"><h2>${title}</h2><p>${detail}</p></header>${body}</section>`;}
  function refs(ids,r){return `<div class="rd-refs">${(ids||[]).map(id=>{const s=r.sources.find(x=>x.id===id);return s?`<button data-source="${esc(id)}">${esc(s.publisher)} ↗</button>`:'';}).join('')}</div>`;}
  function scaffold(kind){const event=kind==='daily_event';return `<div class="rd-workspace" data-research-kind="${kind}">
    <header class="rd-page-head"><div><div class="rd-eyebrow">${event?'EVENT INTELLIGENCE':'NARRATIVE RESEARCH'}</div><h1>${event?'事件一览':'舆情分析'}</h1><p>${event?'先厘清发生了什么，再判断什么值得关注。':'将市场叙事放回数据、反证与条件中检验。'}</p></div><div class="rd-actions"><button class="btn" data-action="refresh">刷新报告</button><button class="btn primary" data-action="workflow">准备 AI 分析 ↗</button></div></header>
    <div class="rd-commandbar"><label>报告版本 <select id="rd-report-select" aria-label="报告版本"><option value="">最新报告</option></select></label><div class="rd-actions"><button class="btn small" data-action="preview">预览报告文件</button><button class="btn small" data-action="export">导出此报告</button></div></div><p id="rd-feedback" class="rd-feedback" role="status"></p>
    <div class="rd-layout"><div id="rd-content" aria-live="polite">${empty('正在读取报告','读取已保存研究，不触发模型生成。')}</div><aside class="rd-rail"><section class="rd-panel rd-workflow-card"><div class="rd-eyebrow">RESEARCH PROCESS</div><h2>${event?'从事实到观察':'从观点到验证'}</h2><ol class="rd-process">${ResearchProtocol.modules[kind].map(m=>`<li><button data-module="${m.id}"><strong>${m.title}</strong><span>${m.question}</span></button></li>`).join('')}</ol><button class="btn rd-full" data-action="workflow">查看完整研究指令</button></section><section class="rd-panel rd-context-note"><h3>两种时钟，分开阅读</h3><p>行情持续更新；报告只代表资料截止时的判断。旧研究不会随最新价格自动变成新结论。</p><a href="#/${event?'news-analysis':'news'}">${event?'打开舆情分析':'返回事件事实'} →</a></section><section class="rd-panel rd-context-note"><h3>交叉核对</h3><div class="rd-quicklinks"><a href="#/chart">价格与结构 ↗</a><a href="#/orderflow">主动成交 ↗</a><a href="#/heatmap">分所强平 ↗</a><a href="#/derivatives">资金与宏观 ↗</a></div></section></aside></div>
    <dialog id="rd-dialog" class="rd-dialog"><header class="rd-dialog-head"><h2 id="rd-dialog-title"></h2><button class="btn" data-action="close-dialog" aria-label="关闭对话框">关闭 ×</button></header><div id="rd-dialog-body"></div></dialog></div>`;}
  function eventCard(e,r){return `<article class="rd-event"><div class="rd-event-time">${esc(time(e.occurredAt,e.timePrecision))}<span>${esc(e.category)}</span></div><div class="rd-event-main">${tag(e.status)}<h3>${esc(e.title)}</h3><p>${esc(e.summary)}</p><dl class="rd-insight"><div><dt>影响路径</dt><dd>${esc(e.transmission)}</dd></div><div><dt>观察什么</dt><dd>${esc(e.watch)}</dd></div></dl>${refs(e.sourceIds,r)}</div></article>`;}
  function renderReport(row,kind){
    const r=row.report||{};
    if(r.schemaVersion!==ResearchProtocol.VERSION)return renderLegacy(row,kind);
    const errors=ResearchProtocol.validate(row);
    if(errors.length)return section('rd-invalid','报告未通过校验','保留原文，避免把不完整内容显示成已核实研究。',`<ul>${errors.map(e=>`<li>${esc(e)}</li>`).join('')}</ul>`);
    const dated=Date.now()-Date.parse(r.asOf)>86400000;
    const head=`<section class="rd-summary"><div class="rd-summary-meta">${tag(dated?'历史研究':'研究快照')}<span>资料截至 ${esc(time(r.asOf))}</span></div><h2>${esc(r.title)}</h2><p>${esc(r.summary)}</p><div class="rd-summary-foot"><span>${r.sources.length} 个来源</span><span>${kind==='daily_event'?r.events.length+' 项事件':r.narratives.length+' 条叙事'}</span><span>生成 ${esc(time(row.generatedAt))}</span></div>${dated?'<div class="rd-caution">资料截止距今已超过 24 小时，使用前请核对新增事实与价格变化。</div>':''}</section>`;
    const watch=section('rd-watch','下一观察','把判断变成可以验证的问题。',r.watchlist.length?`<div class="rd-watchlist">${r.watchlist.map((w,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><div><h3>${esc(w.question)}</h3><p>${esc(w.condition)}</p>${refs(w.sourceIds,r)}</div></article>`).join('')}</div>`:empty('未形成观察条件','先补齐事实，再建立可检验的问题。'));
    const limits=section('rd-limits','研究边界','缺失、冲突和不确定性属于结果的一部分。',`<ul class="rd-limit-list">${r.limitations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`);
    const sources=section('rd-sources','证据与来源','核对原始披露；同一报道的转载不等于独立来源。',`<div class="rd-source-list">${r.sources.map(s=>`<article id="rd-source-${esc(s.id)}" tabindex="-1"><span class="rd-source-index">${esc(s.id)}</span><div><a href="${esc(ResearchProtocol.safeUrl(s.url))}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a><p>${esc(s.publisher)} · ${esc(labels[s.type])}<br>发布 ${esc(time(s.publishedAt))} · 访问 ${esc(time(s.accessedAt))}</p></div></article>`).join('')||empty('未提供来源','不能据此形成已确认判断。')}</div>`);
    if(kind==='daily_event')return head+section('rd-events','关键事件','状态表示核实程度，不代表投资方向。',`<div class="rd-filters"><label class="rd-search">检索事件<input id="rd-search" type="search" placeholder="关键词或类别"></label><label>核实程度<select id="rd-status-filter"><option value="all">全部</option><option value="confirmed">已核实</option><option value="reported">单源报道</option><option value="unverified">待核实</option></select></label><span id="rd-result-count">${r.events.length} 项</span></div><div id="rd-event-list">${r.events.map(e=>eventCard(e,r)).join('')||empty('本次没有可列示事件','查看资料限制，或从右侧研究流程开始。')}</div>`)+section('rd-calendar','接下来值得留意','未来排期与已发生事实分开；未知时间不生成倒计时。',r.catalysts.map(e=>eventCard(e,r)).join('')||empty('没有已核实的催化剂排期','没有准确来源时留空，不拿新闻发布时间代替。'))+watch+limits+sources;
    return head+`<p class="rd-parent">上游事件：${r.parentReportId==='unlinked'?'未关联':`<a href="#/news?reportId=${encodeURIComponent(r.parentReportId)}">${esc(r.parentReportId)} ↗</a>`}</p>`+
      section('rd-checks','先看市场证据','观察和解释分列；每项数据保留自己的时点。',r.checks.length?`<div class="rd-table-scroll"><table class="rd-table"><thead><tr><th>指标 / 时点</th><th>可观察事实</th><th>解释与边界</th></tr></thead><tbody>${r.checks.map(c=>`<tr><th>${esc(c.metric)}<small>${esc(time(c.asOf))}</small></th><td>${esc(c.observation)}</td><td>${esc(c.interpretation)}${refs(c.sourceIds,r)}</td></tr>`).join('')}</tbody></table></div>`:empty('缺少可验证的市场证据','核对价格、成交和资金后，再形成判断。'))+
      section('rd-narratives','叙事与反证','关注度、可信度和市场定价是三个不同问题。',r.narratives.map(n=>`<article class="rd-narrative">${tag(n.status)}<h3>${esc(n.title)}</h3><p class="rd-thesis">${esc(n.claim)}</p><div class="rd-two-col"><div><h4>支持证据</h4><p>${esc(n.support)}</p></div><div class="rd-counter"><h4>最强反证</h4><p>${esc(n.counterEvidence)}</p></div></div><div class="rd-pricing"><strong>市场验证</strong><p>${esc(n.pricing)}</p></div>${refs(n.sourceIds,r)}</article>`).join('')||empty('暂无经过核对的叙事','先核实观点出处，再核对支持和反对证据。'))+
      section('rd-scenarios','条件情景','用触发与失效条件替代无依据的精确概率。',r.scenarios.length?`<div class="rd-scenarios">${r.scenarios.map(s=>`<article><h3>${esc(s.name)}</h3><dl>${[['触发',s.trigger],['确认',s.confirmation],['失效',s.invalidation],['可能影响',s.implication]].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>${refs(s.sourceIds,r)}</article>`).join('')}</div>`:empty('暂不建立情景','证据不足时，等待观察也是完整的研究结果。'))+watch+limits+sources;
  }
  function renderLegacy(row,kind){const r=row.report||{};
    const groups=kind==='daily_event'?[['topStories','历史头条'],['dynamicBriefs','历史速览'],['aiIntel','历史技术资讯'],['githubTools','历史工具记录']]:[['riskRadar','历史风险观察'],['opportunityScanner','历史条件观察'],['eventCalendar','历史事件记录']];
    const sections=groups.filter(([key])=>Array.isArray(r[key])&&r[key].length).map(([key,title])=>section('rd-legacy-'+key,title,'以下为旧报告原文，本轮未重新核实；不作为当前行情判断。',r[key].map(item=>`<article class="rd-narrative"><span class="rd-tag">历史原文 · 待复核</span><h3>${esc(item.title||item.label||item.name||'历史条目')}</h3>${['fact','body','coreFact','whyUseful','trigger','setup','analysis','nextWatch','watch','invalidation','response','why'].filter(k=>typeof item[k]==='string'&&item[k]).map(k=>`<p>${esc(item[k])}</p>`).join('')}${ResearchProtocol.safeUrl(item.sourceUrl)?`<a href="${esc(ResearchProtocol.safeUrl(item.sourceUrl))}" target="_blank" rel="noopener noreferrer">旧报告所列来源：${esc(item.sourceName||'查看链接')} ↗</a>`:''}</article>`).join(''))).join('');
    return `<section class="rd-summary"><div class="rd-summary-meta">${tag('历史格式')}<span>${esc(time(row.generatedAt))}</span></div><h2>${esc(r.title||'历史研究报告')}</h2><p>旧版研究完整保留。旧评分、模型配置和时间状态不代表当前市场，也不会自动转换为新版结论。</p><div class="rd-caution">请先核对资料时间；使用右侧流程生成有证据的新版本。旧版模型配置说明已退役。</div><a class="btn" href="#/${kind==='daily_event'?'news':'news-analysis'}?legacy=1${row.id?'&reportId='+encodeURIComponent(row.id):''}">打开旧版报告与历史管理 ↗</a></section>${sections}<section class="rd-panel"><h2>原始报告内容</h2><details class="rd-legacy"><summary>展开原始正文（历史结构）</summary><pre>${esc(JSON.stringify(r,null,2))}</pre></details></section>`;}
  function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function mount(kind){
    disposer?.();const root=document.querySelector('[data-research-kind="'+kind+'"]');if(!root)return;
    const content=root.querySelector('#rd-content'),feedback=root.querySelector('#rd-feedback'),dialog=root.querySelector('#rd-dialog'),body=root.querySelector('#rd-dialog-body'),select=root.querySelector('#rd-report-select');
    const life=new AbortController();let request=null,generation=0,row=null,preview=false;
    const id=()=>new URLSearchParams(location.hash.split('?')[1]||'').get('reportId')||'';
    const message=t=>feedback.textContent=t;
    const render=()=>content.innerHTML=row?renderReport(row,kind):empty('还没有这份研究','打开「准备 AI 分析」，复制指令到 AI 对话；保存结果后回到这里阅读。');
    async function load(reportId=''){
      const ticket=++generation;request?.abort();request=new AbortController();preview=false;message('正在读取'+(reportId?'指定报告':'最新报告')+'…');
      try{const data=reportId?await DataEngine.fetchYuqingReportItem(reportId,{signal:request.signal}):await DataEngine.fetchYuqingReportLatest(kind,{signal:request.signal});if(ticket!==generation||life.signal.aborted)return;row=data?.report||null;if(row&&(row.kind!==kind||(reportId&&row.id!==reportId)))throw Error('报告与所选版本不一致');if(reportId&&!row)throw Error('指定报告不存在，未替换为最新');render();message(row?'已载入保存的研究快照 · 不会自动触发分析':'暂无已保存报告，可以开始一次研究');}
      catch(e){if(ticket!==generation||life.signal.aborted)return;row=null;content.innerHTML=empty('报告暂时无法读取',e.message);message('未用其他版本替代；可点刷新重试。');}
    }
    async function loadHistory(){try{const data=await DataEngine.fetchYuqingReportHistory(kind,365,{signal:life.signal});if(life.signal.aborted)return;const current=id();select.innerHTML='<option value="">最新报告</option>'+(data?.items||[]).map(x=>`<option value="${esc(x.id)}">${esc(time(x.generatedAt))} · ${esc(x.title||x.id)}</option>`).join('');if(current&&!Array.from(select.options).some(o=>o.value===current))select.add(new Option('指定历史报告',current));select.value=current;}catch(_){if(!life.signal.aborted)select.title='历史列表读取失败，当前报告读取独立进行';}}
    function show(title,html){root.querySelector('#rd-dialog-title').textContent=title;body.innerHTML=html;if(!dialog.open)dialog.showModal();}
    function workflow(moduleId){const list=ResearchProtocol.modules[kind],module=moduleId?list.find(x=>x.id===moduleId):null;show(module?.title||'在 AI 对话中完成研究',`<p class="rd-dialog-intro">复制指令到 AI 对话。AI 负责检索与分析，网站读取保存的结果；这里不会启动模型或要求 API Key。</p><div class="rd-workflow-grid">${(module?[module]:list).map((m,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><div><h3>${m.title}</h3><p>${m.prompt}</p><small>输出：${m.output}</small></div></article>`).join('')}</div><label class="rd-focus-label">这次特别关注什么？<input id="rd-focus" maxlength="600" placeholder="例如：未来一周宏观事件对 BTC 的传导"></label><details class="rd-prompt-details"><summary>查看完整指令</summary><textarea id="rd-prompt" readonly aria-label="完整研究指令">${esc(ResearchProtocol.prompt(kind,moduleId,{reportId:row?.id}))}</textarea></details><div class="rd-dialog-foot"><p id="rd-copy-status" role="status">含来源规则、报告格式及保存步骤。</p><button class="btn primary" data-action="copy-prompt" data-module-id="${moduleId||''}">复制${module?'模块':'完整研究'}指令</button></div>`);}
    async function previewFile(file){if(!file)return;if(file.size>2097152){body.querySelector('#rd-preview-errors').textContent='文件超过 2 MB。';return;}try{const candidate=JSON.parse(await file.text());if(life.signal.aborted)return;const errors=ResearchProtocol.validate(candidate);if(candidate.kind!==kind)errors.push('报告类型与当前页面不一致');if(errors.length){body.querySelector('#rd-preview-errors').textContent=errors.join('\n');return;}++generation;request?.abort();row=candidate;preview=true;render();dialog.close();message('本地预览 · 尚未保存云端。请在 AI 对话中校验并导入，再刷新读回。');}catch(e){if(body.querySelector('#rd-preview-errors'))body.querySelector('#rd-preview-errors').textContent='无法读取 JSON：'+e.message;}}
    root.addEventListener('click',async ev=>{
      const mod=ev.target.closest('[data-module]');if(mod){workflow(mod.dataset.module);return;}
      const source=ev.target.closest('[data-source]');if(source){const el=document.getElementById('rd-source-'+source.dataset.source);el?.scrollIntoView({block:'center'});el?.focus();return;}
      const btn=ev.target.closest('[data-action]');if(!btn)return;
      switch(btn.dataset.action){case 'refresh':await load(id());loadHistory();break;case 'workflow':workflow();break;case 'close-dialog':dialog.close();break;case 'export':if(row)download(row,(preview?'preview-':'research-')+kind+'.json');else message('没有报告可导出。');break;
        case 'copy-prompt':{const text=ResearchProtocol.prompt(kind,btn.dataset.moduleId||undefined,{reportId:row?.id,focus:body.querySelector('#rd-focus')?.value.trim()}),area=body.querySelector('#rd-prompt'),status=body.querySelector('#rd-copy-status');area.value=text;area.closest('details').open=true;try{await navigator.clipboard.writeText(text);if(!life.signal.aborted&&status.isConnected)status.textContent='已复制，可粘贴到 AI 对话。';}catch(_){if(!life.signal.aborted&&area.isConnected){area.focus();area.select();status.textContent='剪贴板不可用，请复制已选中的指令。';}}break;}
        case 'preview':show('预览结构化研究','<p class="rd-dialog-intro">选择 AI 生成的 JSON。先校验来源、时间和字段，再本地预览；不会上传或覆盖云端报告。</p><label class="rd-file-label">选择报告 JSON<input id="rd-file" type="file" accept="application/json,.json"></label><pre id="rd-preview-errors" role="alert"></pre><p class="rd-muted">正式保存使用仓库中的报告导入脚本，按新版本保存。</p>');break;
      }
    },{signal:life.signal});
    const filter=()=>{const r=row?.report;if(!r?.events)return;const q=(root.querySelector('#rd-search')?.value||'').toLowerCase(),status=root.querySelector('#rd-status-filter')?.value;const list=r.events.filter(e=>(status==='all'||e.status===status)&&[e.title,e.summary,e.category].join(' ').toLowerCase().includes(q));root.querySelector('#rd-event-list').innerHTML=list.map(e=>eventCard(e,r)).join('')||empty('没有匹配事件','调整关键词或核实程度筛选。');root.querySelector('#rd-result-count').textContent=list.length+' 项';};
    root.addEventListener('input',e=>{if(e.target.id==='rd-search')filter();},{signal:life.signal});
    root.addEventListener('change',e=>{if(e.target===select){history.replaceState(null,'','#/'+(kind==='daily_event'?'news':'news-analysis')+(select.value?'?reportId='+encodeURIComponent(select.value):''));load(select.value);}if(e.target.id==='rd-status-filter')filter();if(e.target.id==='rd-file')previewFile(e.target.files[0]);},{signal:life.signal});
    load(id());loadHistory();disposer=()=>{++generation;request?.abort();life.abort();if(dialog.open)dialog.close();};
  }
  return {scaffold,mount,dispose:()=>{disposer?.();disposer=null;},esc,time,empty,section,download};
})();
