import {request,reportCard,runCard,receiptCard,readerMarkup,bindReader,friendlyError,prepareReading} from './agent-team/ui.mjs';

const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const modes={current:'当前市场',window:'窗口专题',narrative:'事件专题'},states={complete:'已完成',limited:'覆盖有限',insufficient:'材料不足',failed:'本轮未完成',cancelled:'已取消',interrupted:'服务中断',running:'研究中',checked:'已核对无变化',cleanup_uncertain:'退出待确认',storage_failed:'保存失败',skipped_busy:'忙时跳过'};
const stamp=x=>typeof x==='number'?x:typeof x==='string'&&x.trim()?Date.parse(x):NaN;
const day=x=>Number.isFinite(stamp(x))?new Date(stamp(x)+8*3600000).toISOString().slice(0,10):'unknown';
const date=x=>ResearchDesk.time(x);
let saved=null;
function markup(){return `<header class="rd-page-head"><div><h1>往期报告</h1><p>回到那一天，阅读当时的判断。</p></div><a class="btn" href="#/boardroom">返回首席决策台</a></header>
 <form id="records-query" class="records-query" role="search"><div class="records-query-main"><label>问题或标题<input id="records-search" name="q" type="search" placeholder="搜索报告标题或研究问题" maxlength="2000"></label><label>来源<select id="records-source" name="source"><option value="team">本地报告</option><option value="all">全部来源</option><option value="cloud">云端旧报告</option><option value="local">本机旧记录</option><option value="import">导入任务</option></select></label><button class="btn primary" type="submit">查询</button><button class="btn" type="button" id="records-refresh">刷新索引</button></div><details class="records-filters"><summary>日期与研究类型</summary><div class="records-query-extra"><label>日期依据<select id="records-date-basis" name="dateBasis"><option value="completed">完成 / 保存日</option><option value="cutoff">资料截止日</option></select></label><label>起始日期<input type="date" id="records-from" name="from"></label><label>结束日期<input type="date" id="records-to" name="to"></label><label>研究类型<select id="records-kind" name="kind"><option value="all">全部研究</option><option value="current">当前市场</option><option value="window">窗口专题</option><option value="narrative">事件专题</option><option value="daily_event">旧格式 · 事件</option><option value="sentiment_analysis">旧格式 · 叙事</option><option value="session">旧窗口 / 导入任务</option></select></label></div><p class="muted">北京时间，包含结束日。日期未知单独列出；设定日期范围后不计入。标题查询不搜索报告全文。</p></details></form>
 <p id="records-feedback" role="status"></p><p id="records-coverage" class="records-coverage"></p>
 <div class="records-layout"><section class="records-directory" aria-label="日期研究目录"><div id="records-list"></div><p id="records-page-status" class="muted"></p><div class="at-toolbar"><button class="btn" id="records-latest" hidden>最新一页</button><button class="btn" id="records-previous" hidden>上一页</button><button class="btn" id="records-more" hidden>更早一页</button></div></section><section id="records-detail" class="records-detail" aria-label="所选研究详情"><div class="rd-empty"><h2>选择一轮，阅读当时结果</h2><p>同日多轮分别保留，不合成为一份日报。</p></div></section></div>
 <details class="records-import-panel"><summary>导入与旧格式原件</summary><p>导入文件最多16MiB，完整任务内容最多12MiB。本机持久总额最多4MiB、8个任务；容量不足时仅保留本次会话。导入来源未认证，请保留导出原件。</p><button class="btn" id="records-import-open" type="button">导入完整任务原件</button><input id="records-import" type="file" aria-label="完整任务原件" accept="application/json,.json" hidden><p id="records-import-feedback" role="status"></p></details>${readerMarkup()}`;}

export async function mountLibrary(root,records){
  if(!root)return ()=>{};root.innerHTML=markup();const life=new AbortController(),find=id=>root.querySelector('#'+id),form=find('records-query'),list=find('records-list'),detail=find('records-detail'),feedback=find('records-feedback'),layout=root.querySelector('.records-layout');
  let disposed=false,serial=0,detailSerial=0,queryAbort=null,detailAbort=null,timer=null,rows=[],others=null,teamPage=null,failures=[],selected='',selectedValue=null,closedDays=new Set(),returnScroll=null,focusKey=null;
  const outlet=root.closest('#outlet'),directory=root.querySelector('.records-directory');
  const scrollState=()=>({page:outlet?.scrollTop||0,directory:directory.scrollTop,window:scrollY});
  const restoreScroll=state=>{if(!state)return;outlet?.scrollTo({top:state.page,behavior:'instant'});directory.scrollTop=state.directory;window.scrollTo({top:state.window,behavior:'instant'});};
  const restoreList=()=>requestAnimationFrame(()=>{restoreScroll(returnScroll);if(focusKey)list.querySelector('[data-record-key="'+CSS.escape(focusKey)+'"]')?.focus({preventScroll:true});});
  const params=()=>new URLSearchParams(location.hash.split('?')[1]||''),fields=['q','source','dateBasis','from','to','kind'];
  const filters=()=>Object.fromEntries(fields.map(key=>[key,form.elements.namedItem(key).value]));
  function setFilters(p){for(const key of fields){const value=p.get(key);if(value!==null)form.elements.namedItem(key).value=value;}if(!form.elements.source.value)form.elements.source.value='team';if(!form.elements.kind.value)form.elements.kind.value='all';if(!form.elements.dateBasis.value)form.elements.dateBasis.value='completed';if(p.get('from')||p.get('to')||p.get('kind')&&p.get('kind')!=='all'||p.get('dateBasis')==='cutoff')root.querySelector('.records-filters').open=true;}
  setFilters(params());
  function url(id=selected){const p=new URLSearchParams(filters());if(id)p.set('selected',id);if(teamPage?.offset)p.set('offset',teamPage.offset);return '#/records?'+p;}
  const rowDate=row=>filters().dateBasis==='cutoff'?row.cutoff:row.date;
  const sourceOf=row=>row.key.startsWith('team-task:')?'team':row.key.startsWith('import-task:')?'import':row.source==='云端'?'cloud':'local';
  function otherMatches(row,f){const source=sourceOf(row),d=day(f.dateBasis==='cutoff'?row.cutoff:row.date);return (f.source==='all'||f.source===source)&&(f.kind==='all'||f.kind===row.kind||f.kind===(row.taskMode||row.task?.taskMode))&&String(row.title).toLowerCase().includes(f.q.trim().toLowerCase())&&(!f.from||d!=='unknown'&&d>=f.from)&&(!f.to||d!=='unknown'&&d<=f.to);}
  function remember(){saved={filters:filters(),rows,others,teamPage,failures,closedDays:[...closedDays],scroll:scrollState(),returnScroll,focusKey,selected};}
  function paint(){
    const groups=new Map();for(const row of rows){const d=day(rowDate(row));if(!groups.has(d))groups.set(d,[]);groups.get(d).push(row);}
    list.innerHTML=[...groups].map(([d,items])=>{const teamCount=items.filter(r=>sourceOf(r)==='team').length,total=teamPage?.dateCounts?.[d],partial=Number.isInteger(total)&&teamCount<total;
      return `<details class="records-day" data-day="${esc(d)}" ${closedDays.has(d)?'':'open'}><summary><strong>${d==='unknown'?'日期未知':esc(d)}</strong><span>${items.length} 个本页条目${partial?' · 本地研究为此日部分（共 '+total+' 轮）':''}</span></summary>${items.map(row=>{const team=sourceOf(row)==='team',n=Object.keys(row.accepted||{}).filter(x=>x!=='chief').length;return `<a class="user-record-row records-entry" href="${esc(team?url(row.id):row.href)}" data-record-key="${esc(row.key)}" ${team?'data-select-run="'+esc(row.id)+'"':''} ${selected===row.id&&team?'aria-current="true"':''}><div class="records-entry-meta"><span>${esc(modes[row.taskMode]||({daily_event:'旧格式 · 事件',sentiment_analysis:'旧格式 · 叙事',session:'旧窗口 / 导入任务'}[row.kind])||'研究')}</span><span>${esc(states[row.status]||'原件资格见详情')}</span></div><strong>${esc(row.title.length>76?row.title.slice(0,76)+'…':row.title)}</strong><span class="records-scope">${esc(records.scopeLabel(row))}</span><span>资料截至 ${esc(date(row.cutoff))}</span><span>${esc(row.dateLabel||'完成/保存')} ${esc(date(row.date))}</span>${team?'<span class="records-entry-result">'+(row.hasChief?'首席已形成':'本轮未形成新首席')+' · '+n+' / 5 领域交付</span>':'<span>'+esc(row.source)+'</span>'}</a>`;}).join('')}</details>`;
    }).join('')||(failures.length?ResearchDesk.empty('读取失败或查询覆盖不足','不能据此判断不存在报告。查看上方来源说明并重试。'):ResearchDesk.empty('没有匹配研究',teamPage?.coverage?.complete?'完整本地索引未找到符合条件的研究；可调整日期、类型或标题。':'在已读取的所选来源范围内没有匹配；更早云端历史不在本次覆盖内。'));
    find('records-more').hidden=!teamPage||teamPage.nextOffset===null;find('records-previous').hidden=find('records-latest').hidden=!teamPage?.offset;
    find('records-page-status').textContent=teamPage?'本地研究匹配 '+teamPage.total+' 轮 · 本页 '+(teamPage.count?teamPage.offset+1:0)+'—'+(teamPage.offset+teamPage.count)+(teamPage.nextOffset!==null?' · 尚有更早匹配':' · 已到匹配末页'):'';
    const f=filters();find('records-coverage').textContent=(teamPage?.coverage?.complete?'本地共 '+teamPage.coverage.indexedCount+' 轮；'+(teamPage.coverage.titleCoverage?.state==='unavailable'?'中文标题暂时无法读取。':teamPage.coverage.titleCoverage?'已整理 '+teamPage.coverage.titleCoverage.count+' 份中文标题，其余按原问题检索。':'标题整理范围以原件为准。')+'正文不参与搜索。':'本地研究索引未参与或未完成本次查询。')+(f.source==='all'||f.source==='cloud'?' 云端旧报告：近365天索引，不含更早记录。':'')+(f.source!=='team'?(f.source==='import'?' 导入：仅此浏览器保存或本次会话。':f.source==='cloud'?'':' 本机旧记录：此浏览器及已连接本地旧研究服务；导入只在此浏览器或本次会话。'):'');
    feedback.textContent=(failures.length?'读取限制：'+failures.join('；'):'本页 '+rows.length+' 个研究条目；岗位稿收在所属研究内。')+(f.from||f.to?' · '+(f.dateBasis==='cutoff'?'按资料截止日':'按完成/保存日'):'');remember();
  }
  function clearDetail(){++detailSerial;detailAbort?.abort();selected='';selectedValue=null;layout.classList.remove('has-selection');detail.innerHTML='<div class="rd-empty"><h2>选择一轮，阅读当时结果</h2><p>列表与详情始终对应同一原件。</p></div>';}
  function backToList(){clearDetail();history.replaceState(null,'',url(''));paint();restoreList();}
  async function select(id,{push=true}={}){
    if(!/^[a-f0-9-]{36}$/.test(id)){clearDetail();feedback.textContent='所选研究身份无效。';return;}
    const ticket=++detailSerial;detailAbort?.abort();detailAbort=new AbortController();if(push)returnScroll=scrollState();selected=id;selectedValue=null;layout.classList.add('has-selection');if(push){history.pushState(null,'',url(id));}
    detail.innerHTML='<div class="records-detail-tools"><button class="btn" id="records-back">← 返回查询结果</button></div><p role="status">正在读取所选研究…</p>';find('records-back').onclick=backToList;
    for(const a of list.querySelectorAll('[data-select-run]')){if(a.dataset.selectRun===id)a.setAttribute('aria-current','true');else a.removeAttribute('aria-current');}
    try{const read=p=>request(p,undefined,{signal:detailAbort.signal});const run=await read('runs/'+encodeURIComponent(id));if(disposed||ticket!==detailSerial)return;if(run.row?.id!==id)throw Error('返回原件与所选研究不一致。');
      let chief=null,issue='';if(run.row.accepted?.chief)try{chief=await read('reports/'+encodeURIComponent(run.row.accepted.chief));if(chief.id!==run.row.accepted.chief||chief.cycleId!==id)throw Error('首席报告身份不一致');await prepareReading(chief,read);}catch(e){chief=null;issue='该轮已接受首席暂时无法读取：'+friendlyError(e);}
      if(disposed||ticket!==detailSerial)return;selectedValue=run;
      detail.innerHTML=`<div class="records-detail-tools"><button class="btn" id="records-back">← 返回查询结果</button><a class="btn" href="#/records?selected=${encodeURIComponent(id)}">本轮链接</a><button class="btn" id="records-export">导出完整研究原件</button></div><div class="records-detail-identity"><span>${esc(modes[run.row.task?.taskMode||run.row.taskMode]||'当时研究')} · ${esc(states[run.row.terminal||run.row.status]||'状态未知')}</span><h2 tabindex="-1" class="sr-only">所选研究</h2>${run.row.question?'<details class="records-question"><summary>原研究问题与观察范围</summary><p>'+esc(run.row.question)+'</p></details>':''}<p>资料截止 ${esc(date(run.row.asOf))} · 完成/保存 ${esc(date(run.row.endedAt))}</p></div>${chief?reportCard(chief,{chief:true,historical:true}):'<section class="at-empty"><h2>'+(issue?'首席原件读取失败':'本轮未形成新首席')+'</h2><p>'+esc(issue||'可以阅读本轮已交付领域及证据；没有使用旧首席补作本轮结论。')+'</p></section>'}<details class="records-run-materials"><summary>本轮领域交付、观察范围与原件</summary>${runCard(run,{showQuestion:false})}</details>${!chief&&run.baselines?.chief?'<section class="at-baseline-link"><p>本轮封存的首席基线，代表较早时点，不是本轮结果。</p><button class="btn" data-report="'+esc(run.baselines.chief.id)+'">单独阅读封存基线</button></section>':''}`;
      find('records-back').onclick=backToList;find('records-export').onclick=async()=>{const button=find('records-export');button.disabled=true;try{const bundle=await read('runs/'+encodeURIComponent(id)+'/export');if(disposed||ticket!==detailSerial)return;if(bundle.run?.row?.id!==id)throw Error('导出与所选原件不一致。');ResearchDesk.download(bundle,'BTC-research-'+id+'.json');feedback.textContent='已导出所选研究轮及其封存报告。';}catch(e){if(!disposed&&ticket===detailSerial)feedback.textContent='导出失败：'+friendlyError(e);}finally{if(button.isConnected)button.disabled=false;}};
      if(push){detail.scrollIntoView({block:'start'});detail.querySelector('h2')?.focus({preventScroll:true});}remember();
    }catch(error){if(disposed||ticket!==detailSerial)return;detail.innerHTML='<button class="btn" id="records-back">← 返回查询结果</button><section class="at-empty"><h2>所选研究读取失败</h2><p>'+esc(id)+'</p><p>'+esc(friendlyError(error))+'；没有替换成最新报告。</p><button class="btn" id="records-retry">重试所选研究</button></section>';find('records-back').onclick=backToList;find('records-retry').onclick=()=>select(id,{push:false});}
  }
  async function query({offset=0,reuse=false,keepSelection=false}={}){
    const ticket=++serial;queryAbort?.abort();queryAbort=new AbortController();const f=filters();clearTimeout(timer);if(!keepSelection)clearDetail();
    if(f.from&&f.to&&f.from>f.to){rows=[];teamPage=null;failures=['起始日期晚于结束日期，请调整。'];paint();return;}
    feedback.textContent='正在查询索引…';form.querySelector('[type=submit]').disabled=true;
    try{let page=null,issues=[];const wantsTeam=['all','team'].includes(f.source)&&['all',...Object.keys(modes)].includes(f.kind);
      const teamPromise=wantsTeam?records.readTeamPage(offset,{signal:queryAbort.signal,query:{q:f.q,type:f.kind,from:f.from,to:f.to,dateBasis:f.dateBasis,...(reuse&&teamPage?.snapshot?{snapshot:teamPage.snapshot}:{})}}).catch(e=>{issues.push(e.message);return null;}):null;
      const otherPromise=f.source==='team'?null:others?.[f.source]?Promise.resolve(others[f.source]):records.read({signal:queryAbort.signal,includeTeam:false,source:f.source});
      const results=await Promise.all([teamPromise,otherPromise]);if(disposed||ticket!==serial)return;page=results[0];if(results[1]){others={...others,[f.source]:results[1]};issues.push(...results[1].failures);}teamPage=page;failures=issues;
      rows=[...(teamPage?.rows||[]),...(f.source==='team'?[]:(others?.[f.source]?.rows||[]).filter(row=>otherMatches(row,f)))].sort((a,b)=>(Number.isFinite(stamp(rowDate(b)))?stamp(rowDate(b)):-Infinity)-(Number.isFinite(stamp(rowDate(a)))?stamp(rowDate(a)):-Infinity)||a.key.localeCompare(b.key));
      history.replaceState(history.state,'',url());paint();
    }catch(error){if(!disposed&&ticket===serial){rows=[];teamPage=null;failures=[friendlyError(error)];paint();}}
    finally{if(!disposed&&ticket===serial)form.querySelector('[type=submit]').disabled=false;}
  }
  const reader=bindReader(root,message=>{feedback.textContent=message;});
  form.onsubmit=event=>{event.preventDefault();void query();};form.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>void query(),250);},{signal:life.signal});form.addEventListener('change',()=>{clearTimeout(timer);void query();},{signal:life.signal});
  find('records-refresh').onclick=()=>{others=null;void query();};find('records-more').onclick=()=>void query({offset:teamPage?.nextOffset||0,reuse:true});find('records-previous').onclick=()=>void query({offset:Math.max(0,(teamPage?.offset||0)-50),reuse:true});find('records-latest').onclick=()=>void query({reuse:true});
  list.addEventListener('click',event=>{const a=event.target.closest('[data-select-run]');if(a){event.preventDefault();focusKey=a.dataset.recordKey;void select(a.dataset.selectRun);}else if(event.target.closest('a'))remember();},{signal:life.signal});list.addEventListener('toggle',event=>{const d=event.target.dataset?.day;if(d){if(event.target.open)closedDays.delete(d);else closedDays.add(d);}},{signal:life.signal,capture:true});
  window.addEventListener('popstate',()=>{const id=params().get('selected')||'';if(id===selected)return;if(id)void select(id,{push:false});else{clearDetail();paint();restoreList();}},{signal:life.signal});
  find('records-import-open').onclick=()=>find('records-import').click();find('records-import').onchange=async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>records.MAX_IMPORT_BYTES)throw Error('文件超过16MiB。');const value=JSON.parse(await file.text());if(disposed)return;const message=await records.importBundle(value);if(disposed)return;find('records-import-feedback').textContent=message;others=null;form.elements.source.value='import';void query();}catch(e){if(!disposed)find('records-import-feedback').textContent='无法导入：'+e.message;}finally{event.target.value='';}};
  const initial=params().get('selected'),offset=Number(params().get('offset')||0);
  if(saved&&(saved.teamPage?.offset||0)===offset&&JSON.stringify(saved.filters)===JSON.stringify(filters())){({rows,others,teamPage,failures}=saved);closedDays=new Set(saved.closedDays);focusKey=saved.focusKey;returnScroll=saved.returnScroll;const scroll=saved.scroll;paint();requestAnimationFrame(()=>restoreScroll(scroll));if(initial)void select(initial,{push:false});}else void query({offset:Number.isSafeInteger(offset)&&offset>=0?offset:0,keepSelection:true}).then(()=>{if(initial&&!disposed)void select(initial,{push:false});});
  return ()=>{remember();disposed=true;++serial;++detailSerial;clearTimeout(timer);queryAbort?.abort();detailAbort?.abort();life.abort();reader();};
}

export function mountSavedRecord(root,records){
  const life=new AbortController(),params=new URLSearchParams(location.hash.split('?')[1]||''),isImport=params.get('source')==='import';let bundle=null,reader=null,disposed=false;
  const back=new URLSearchParams(saved?.filters||{});if(saved?.teamPage?.offset)back.set('offset',saved.teamPage.offset);if(saved?.selected)back.set('selected',saved.selected);
  root.innerHTML='<header class="rd-page-head"><div><h1>'+(isImport?'导入研究原件':'当时报告与依据')+'</h1><p>始终阅读所选版本，保留当时的截止、来源与判断。</p></div><a class="btn" href="#/records?'+esc(back)+'">← 返回查询结果</a></header><p id="team-record-feedback" role="status">正在读取指定原件…</p><div id="team-record-body"></div>'+readerMarkup();
  const feedback=root.querySelector('#team-record-feedback'),body=root.querySelector('#team-record-body');
  const read=async (p,_body,options={})=>{if(!bundle)return request(p,undefined,{signal:AbortSignal.any([life.signal,...(options.signal?[options.signal]:[])])});const [kind,encoded]=p.split('/'),id=decodeURIComponent(encoded||'');const value=kind==='reports'?(bundle.reports[id]||Object.values(bundle.run.baselines||{}).find(record=>record?.id===id)):kind==='runs'&&id===bundle.run.row.id?bundle.run:null;if(!value)throw Error('导入包缺少这份原件；没有从最新观点或研究服务替换。');return value;};
  async function load(){try{let original,html;
    if(isImport){await records.importedRows();if(disposed)return;bundle=records.getImport(params.get('importId'));if(!bundle)throw Error('指定导入原件不存在，请重新导入原文件。');await records.validateImport(bundle);if(disposed)return;original=bundle;const chief=bundle.reports[bundle.run.row.accepted.chief];html=(chief?reportCard(chief,{chief:true,historical:true,source:'import'}):'<section class="at-empty"><h2>本轮未形成新首席</h2><p>以下保留本轮领域交付，没有补放旧结论。</p></section>')+runCard(bundle.run)+(!chief&&bundle.run.baselines?.chief?'<p class="at-warning">封存基线代表较早时点。</p><button class="btn" data-report="'+esc(bundle.run.baselines.chief.id)+'">单独阅读首席基线（非本轮）</button>':'');feedback.textContent='只读导入原件 · 来源未认证；保留原范围与时点，不更新当前观点。';}
    else if(params.get('evidenceId')){const cycle=params.get('cycleId'),run=await read('runs/'+encodeURIComponent(cycle));if(run.row?.id!==cycle)throw Error('研究轮身份不一致');original=run.receipts?.find(r=>r.id===params.get('evidenceId'));if(!original)throw Error('指定引用原件不存在。');html=receiptCard(original);feedback.textContent='已打开精确引用原件；未从最新材料补齐。';}
    else{const id=params.get('reportId');if(!id)throw Error('没有指定研究原件。');original=await read('reports/'+encodeURIComponent(id));if(original.id!==id||!original.report)throw Error('报告身份与所选版本不一致');await prepareReading(original,read);html=reportCard(original,{chief:original.role==='chief',historical:true});feedback.textContent='已打开指定报告，保留当时版本与原有资料时间。';}
    if(disposed)return;body.innerHTML='<div class="at-toolbar"><button class="btn" id="team-record-export">导出所选原件</button></div>'+html;body.querySelector('#team-record-export').onclick=()=>ResearchDesk.download(original,'BTC-original-'+(original.id||original.run?.row.id||'record')+'.json');reader=bindReader(root,text=>{feedback.textContent=text;},{read,source:isImport?'import':'service',findEvidence:isImport?ref=>bundle.run.receipts.find(r=>r.id===ref.evidence&&(ref.cycle===bundle.run.row.id||r.historicalBaseline&&r.originCycleId===ref.cycle)):null});
  }catch(error){if(!disposed){feedback.textContent='所选原件读取失败：'+friendlyError(error);body.innerHTML='<section class="at-empty"><h2>没有替换成其他报告</h2><p>所选身份仍在地址中。返回查询结果或重新打开原件。</p></section>';}}}
  void load();return ()=>{disposed=true;life.abort();reader?.();};
}
