import crypto from 'node:crypto';
import path from 'node:path';
import fs from 'node:fs';
import {performance} from 'node:perf_hooks';
import {ROLES,VERSION,TASK_VERSION,TASK_CAPABILITIES,normalizeTaskRequest,roleDatasets,modelSchema,decisionSchema,CHIEF_SCHEMA,REVIEW_SCHEMA,validateSchema,validateReport,conditionTiming,fieldAt} from '../../js/agent-team/contract.mjs';
import {PROMPT_VERSION,specialistPrompt,chiefPrompt,reviewPrompt} from '../../js/agent-team/prompts.mjs';
import {createTools,hash} from './tools.mjs';
import {eventReading,eventMaterial} from './event-reading.mjs';
import {TeamStore} from './store.mjs';
import {Presence,scheduleSlot,nextSlots,localDay} from './schedule.mjs';
import {authStatus,runStructured} from '../research/codex-provider.mjs';
import {createKnowledgeRetriever} from './knowledge.mjs';
import {klineOpenAt} from '../../cloudflare/kline-recovery.mjs';
const date=()=>new Date().toISOString();
export function reusableToolReceipt(receipts,role,request,{asOf,windowHours=24,contextId='current'}){const identity=q=>({tool:['dataset','market'].includes(q.tool)?'dataset':q.tool,dataset:q.tool==='market'?(q.dataset||'binance-perp-klines-15m'):(q.dataset||''),limit:q.limit||100,windowHours:q.windowHours||windowHours,articleId:q.articleId||''}),wanted=identity(request);return receipts.find(r=>r.role===role&&r.asOf===asOf&&(r.contextId||'current')===contextId&&r.ok&&r.usable&&!r.historicalBaseline&&!r.conditionEvidenceOnly&&Object.entries(wanted).every(([k,v])=>identity(r.request||{})[k]===v));}
export function compactReceipt(r,paths=null,{endpointCount=2}={}){const {rawResponse,...safe}=r;if(!r.data)return safe;const data=structuredClone(r.data);let indices=[];delete data.nativeBars;if(Array.isArray(data.sources))data.sources=data.sources.map(({rawResponse,...source})=>source);
  if(Array.isArray(data.observations)){const requested=(paths||[]).filter(p=>p.startsWith('observations.')),completeSelected=!r.historicalBaseline&&!r.conditionEvidenceOnly&&r.ok&&r.usable&&/^binance-(perp-klines-(5m|15m|1h|4h|1d|3d|1w)|spot-klines-1h)$/.test(r.request?.dataset||'')&&r.coverage?.completeWindow===true&&r.coverage?.sourceQualificationApplied===true&&r.coverage?.requestedRange&&data.observations.length>0&&data.observations.length<=TASK_CAPABILITIES.limits.modelRows;
    indices=completeSelected?data.observations.map((_,i)=>i):[...new Set([...requested.map(p=>Number(p.split('.')[1])),...data.observations.slice(0,paths?endpointCount:5).map((_,i)=>i),...(!r.historicalBaseline?data.representativeIndices||[]:[]),Math.max(0,data.observations.length-1)])];data.observations=Object.fromEntries(indices.filter(i=>data.observations[i]).map(i=>{let row=data.observations[i];if(paths&&!completeSelected)row=Object.fromEntries(Object.entries(row).filter(([k])=>['observedAt','values','effectiveReceivedAt','publicAvailableAt','sourceRevision','sourceHost','ingestionMode','sourceVerification','origin','finality'].includes(k)));return [i,row];}));data.modelSampling=completeSelected?{kind:'complete-selected-klines',originalCount:indices.length,returnedCount:indices.length,originalIndicesPreserved:true,allValuesAndClocksRetained:true}:paths?`cited + first ${endpointCount} + representative rows + oldest; full row values/original indices; other rows omitted`:'deterministic window statistics + representative rows; full receipt retained';}
  else if(data.observations&&typeof data.observations==='object')indices=Object.keys(data.observations).map(Number).filter(Number.isInteger);
  if(Array.isArray(data.items)&&r.request?.tool!=='selected-material'){const count=data.items.length;data.items=data.items.slice(0,12).map(({originalRSS,...x})=>{if(typeof x.summary!=='string'||x.summary.length<=1500)return x;return {...x,summary:x.summary.slice(0,1500),summaryProjection:{originalCharacters:x.summary.length,omittedCharacters:x.summary.length-1500,fullOriginalSaved:true}};});data.itemProjection={originalCount:count,returnedCount:data.items.length,omittedCount:count-data.items.length,originalIndicesPreserved:true,fullOriginalSaved:true,rawRSSOmitted:true};}
  if(data.article){const originalLength=data.article.text.length,limit=r.historicalBaseline?2000:10000;data.article.text=data.article.text.slice(0,limit);if(originalLength>limit)data.article.modelProjection={kind:'article-excerpt',originalCharacters:originalLength,omittedCharacters:originalLength-limit,fullOriginalSaved:true};}
  return {...safe,data,numericUnits:Object.fromEntries(Object.entries(r.numericUnits||{}).filter(([key])=>!key.startsWith('observations.')||indices.includes(Number(key.split('.')[1]))))};
}
export function historicalModelReceipt(receipt,paths=[]){const projected=compactReceipt(receipt,paths);if(!projected.data)return projected;const data=structuredClone(projected.data),allowed=new Set(paths),set=(target,path,value)=>{const pieces=path.split('.');for(const part of pieces.slice(0,-1))target=target[part]??=(Object.create(null));target[pieces.at(-1)]=value;};
  if(data.observations){const rows={};for(const path of allowed){const match=/^observations\.(\d+)\./.exec(path);if(!match)continue;const index=match[1],original=data.observations[index];if(!original)continue;rows[index]??=Object.fromEntries(Object.entries(original).filter(([key])=>['observedAt','effectiveReceivedAt','publicAvailableAt','sourceRevision','sourceHost','sourceVerification','ingestionMode','finality','origin'].includes(key)));const value=path.split('.').slice(2).reduce((row,key)=>row?.[key],original);if(value!==undefined)set(rows[index],path.split('.').slice(2).join('.'),value);}data.observations=rows;}
  if(data.metrics){const metrics={};for(const path of allowed)if(path.startsWith('metrics.')&&data.metrics[path.slice(8)]!==undefined)metrics[path.slice(8)]=data.metrics[path.slice(8)];data.metrics=metrics;}
  if(data.analysis){const original=data.analysis;delete data.analysis;for(const p of allowed)if(p.startsWith('analysis.')){const value=p.split('.').slice(1).reduce((r,k)=>r?.[k],original);if(value!==undefined)set(data,p,value);}}delete data.representativeIndices;
  delete data.units;data.modelSampling={kind:'historical-cited-paths',originalIndicesPreserved:true,unreferencedValuesOmitted:true,fullOriginalSaved:true};return {...projected,data,numericUnits:Object.fromEntries(Object.entries(projected.numericUnits||{}).filter(([key])=>allowed.has(key)))};
}
export function macroBaselinePaths(previous,receipts=[]){const paths=new Map(),datasets=new Set();if(previous?.role!=='macro')return paths;
  for(const receipt of receipts){const dataset=receipt.request?.dataset;if(datasets.has(dataset)||!ROLES.macro.datasets.includes(dataset)||receipt.role!=='macro'||!receipt.ok||!receipt.usable||receipt.historicalBaseline||receipt.conditionEvidenceOnly||receipt.asOf!==previous.asOf||(receipt.contextId||'current')!==(previous.task?.contextId||'current')||!previous.evidenceIds?.includes(receipt.id))continue;
    const rows=Object.entries(receipt.data?.observations||{}).filter(([index,row])=>/^\d+$/.test(index)&&Number.isFinite(Date.parse(row.observedAt))&&typeof row.values?.value==='number'&&Number.isFinite(row.values.value)&&typeof receipt.numericUnits?.['observations.'+index+'.values.value']==='string').sort((a,b)=>Date.parse(b[1].observedAt)-Date.parse(a[1].observedAt)),periods=new Set(),selected=[];
    for(const [index,row]of rows){if(periods.has(row.observedAt))continue;periods.add(row.observedAt);selected.push('observations.'+index+'.values.value');if(selected.length===2)break;}if(selected.length){paths.set(receipt.id,selected);datasets.add(dataset);}
  }return paths;
}
export function specialistModelReceipts(receipts,previous){const paths=new Map(),add=(id,path)=>{if(!paths.has(id))paths.set(id,[]);if(path)paths.get(id).push(path);};for(const c of previous?.report?.claims||[])for(const id of c.evidenceIds){add(id);for(const n of c.numbers.filter(n=>n.evidenceId===id))add(id,n.path);}for(const c of previous?.report?.conditions||[])if(c.criterion)add(c.criterion.evidenceId,c.criterion.path);
  for(const receipt of receipts)if(receipt.historicalBaseline&&receipt.baselineReportIds?.includes(previous?.id))for(const path of receipt.baselineComparisonPaths||[])add(receipt.id,path);
  const history=receipts.filter(r=>r.historicalBaseline&&paths.has(r.id));return receipts.filter(r=>!r.historicalBaseline||paths.has(r.id)).map(r=>{if(r.historicalBaseline)return modelRowDefaults(historicalModelReceipt(r,paths.get(r.id)));const matched=[];
    if(previous?.role==='macro'&&ROLES.macro.datasets.includes(r.request?.dataset)){const periods=new Set(history.filter(old=>old.request?.dataset===r.request.dataset).flatMap(old=>(old.baselineComparisonPaths||[]).map(path=>fieldAt(old.data,path.split('.').slice(0,2).join('.')+'.observedAt'))));for(const [index,row]of Object.entries(r.data?.observations||{}))if(periods.has(row.observedAt))matched.push('observations.'+index+'.values.value');}
    return modelRowDefaults(compactReceipt(r,matched.length?matched:null,{endpointCount:5}));});}
export function modelRowDefaults(receipt){if(!receipt.data?.observations)return receipt;const data=structuredClone(receipt.data),rows=Object.values(data.observations),defaults={...data.rowDefaults};delete data.units;if(rows.length<2)return {...receipt,data};
  for(const key of ['effectiveReceivedAt','publicAvailableAt','sourceRevision','sourceHost','sourceVerification','ingestionMode','origin','finality'])if(rows.every(row=>Object.hasOwn(row,key))){const first=JSON.stringify(rows[0][key]);if(first!==undefined&&rows.every(row=>JSON.stringify(row[key])===first)){defaults[key]=rows[0][key];for(const row of rows)delete row[key];}}
  if(Object.keys(defaults).length)data.rowDefaults=defaults;return {...receipt,data};
}
export function chiefMaterials(job,extraReports=[]){const used=new Map(),add=report=>{for(const claim of report?.claims||[])for(const id of claim.evidenceIds){if(!used.has(id))used.set(id,[]);used.get(id).push(...claim.numbers.filter(n=>n.evidenceId===id).map(n=>n.path));}for(const c of report?.conditions||[])if(c.criterion){const q=c.criterion;if(!used.has(q.evidenceId))used.set(q.evidenceId,[]);used.get(q.evidenceId).push(q.path);}};
  for(const report of [...Object.values(job.roles).map(r=>r?.report),job.baselines?.chief?.report,...extraReports])add(report);
  const direct=new Map([...used].map(([id,paths])=>[id,new Set(paths)])),roleHistory={};
  for(const [role,r]of Object.entries(job.baselines||{})){if(role==='chief')continue;if(!r){roleHistory[role]=null;continue;}const referencedPriorClaims=(r.report.claims||[]).map(c=>({id:c.id,kind:c.kind,scope:c.scope,numbers:c.numbers.filter(n=>direct.get(n.evidenceId)?.has(n.path))})).filter(c=>c.numbers.length),report={...r.report,claims:[],referencedPriorClaims,historicalClaimProjection:{kind:'referenced-prior-values-and-full-counterevidence',originalCount:r.report.claims.length,transmittedOriginalClaims:0,claimTextOmitted:true,fullOriginalSaved:true,allCounterevidenceRetained:true}};roleHistory[role]={id:r.id,cycleId:r.cycleId,asOf:r.asOf,report};}
  // Optional prior definitions still need their exact threshold source even when
  // unrelated narrative claims are omitted from the model's historical view.
  for(const r of Object.values(job.baselines||{}))for(const c of r?.report?.conditions||[])if(c.criterion){const q=c.criterion;if(!used.has(q.evidenceId))used.set(q.evidenceId,[]);used.get(q.evidenceId).push(q.path);}
  const historical=job.receipts.filter(r=>r.historicalBaseline),included=historical.filter(r=>used.has(r.id)),omitted=historical.filter(r=>!used.has(r.id));
  // A failed researcher's uncited raw data is not an accepted interpretation for the chief.
  const omittedCurrent=job.receipts.filter(r=>!r.historicalBaseline&&r.ok&&r.usable&&['failed','insufficient'].includes(job.roles[r.role]?.status)&&!used.has(r.id)),omitIds=new Set(omittedCurrent.map(r=>r.id));
  return {roles:Object.fromEntries(Object.entries(job.roles).map(([role,r])=>[role,{status:r.status,error:r.error,id:r.id,asOf:r.asOf,generatedAt:r.generatedAt,conditionRegistrations:(r.conditionLedger||[]).filter(c=>c.kind==='deterministic').map(c=>({id:c.id,from:c.from,to:c.to,deadline:c.deadline,...conditionTiming(c)})),report:r.report}])),roleHistory,historicalReceipts:included.map(r=>modelRowDefaults(historicalModelReceipt(r,used.get(r.id)||[]))),historicalEvidenceProjection:{kind:'transmitted-claims-and-condition-paths',originalCount:historical.length,returnedCount:included.length,omitted:omitted.map(r=>({id:r.id,originCycleId:r.originCycleId,baselineReportIds:r.baselineReportIds})),fullOriginalSaved:true,unreferencedHistoricalMaterialsOmitted:true},receipts:job.receipts.filter(r=>!r.historicalBaseline&&r.ok&&r.usable&&!omitIds.has(r.id)).map(r=>modelRowDefaults(compactReceipt(r,used.get(r.id)||[],{endpointCount:1}))),coverage:job.receipts.filter(r=>!r.historicalBaseline&&(!r.ok||!r.usable||omitIds.has(r.id))).map(r=>({id:r.id,role:r.role,request:r.request,ok:r.ok,usable:r.usable,quality:r.quality,error:r.error,sourceClock:r.sourceClock,coverage:r.coverage,sourceChain:r.sourceChain,...(omitIds.has(r.id)?{modelProjection:'raw material saved; no accepted role interpretation; omitted from chief facts'}:{})}))};}
const gap=(reason,previous)=>({status:'insufficient',summary:reason,changes:[],claims:[],counterevidence:[],nextChecks:['补齐该领域真实数据后重新取证'],viewChange:{action:'insufficient',reason,previousReportId:previous?.id||null}});
function recordProcessEvent(row,event){if(!['process_spawned','process_started','process_inventory','process_finished'].includes(event.event)||!Number.isSafeInteger(event.pid)||event.pid<=0)return null;
  const phase=event.phase||'model';row.launches??=[];let execution=event.launchId?row.launches.find(p=>p.launchId===event.launchId):row.launches.findLast(p=>p.pid===event.pid&&p.phase===phase&&p.state!=='finished');
  if(!execution){execution={launchId:event.launchId||null,pid:event.pid,phase,startedAt:event.startedAt||date(),deadline:event.deadline,born:null,state:'spawned'};row.launches.push(execution);}
  if(execution.pid!==event.pid||execution.phase!==phase)throw Error('process_launch_identity_changed');
  const root=event.processes?.find(p=>p.pid===event.pid);if(root&&Number.isFinite(Date.parse(root.born))){if(execution.born&&execution.born!==root.born)throw Error('process_launch_identity_changed');execution.born=root.born;}
  if(event.event==='process_started')execution.state='running';if(event.event==='process_finished')Object.assign(execution,{state:'finished',finishedAt:date(),cleanup:event.cleanup,stopped:event.stopped,exitCode:event.code});return execution;
}
export class TeamService {
  constructor({directory='.local/agent-team',toolsFactory=()=>createTools(),knowledgeFactory=()=>createKnowledgeRetriever(),provider=runStructured,auth=authStatus,clock=()=>Date.now(),presenceOptions={},storeOptions={}}={}){
    this.store=new TeamStore(directory,{...storeOptions,clock});this.toolsFactory=toolsFactory;this.knowledgeFactory=knowledgeFactory;this.provider=provider;this.auth=auth;this.clock=clock;this.presence=new Presence({...presenceOptions,clock,onResume:()=>{if(this.active)this.cancel('page_closed');}});this.active=null;this.authCache=null;this.lastSlot=null;this.closed=false;this.ready=this.store.acquire().then(store=>{this.lastSlot=scheduleSlot(store.config,this.clock())?.id||null;return store;});
  }
  async checkAuth(force=false){await this.ready;if(this.closed)throw Error('service_closed');if(['cleanup_uncertain','storage_failed'].includes(this.store.journal.paused))throw Error(this.store.journal.paused);if(this.authInflight)return this.authInflight;if(!force&&this.authCache&&this.clock()-this.authCache.checkedAt<30000)return this.authCache;
    const controller=new AbortController();this.authController=controller;const row={id:crypto.randomUUID(),startedAt:date(),processes:[],terminal:null};this.store.journal.authChecks??=[];this.store.journal.authChecks.push(row);this.store.saveJournal();
    const signal=this.active?AbortSignal.any([controller.signal,this.active.controller.signal]):controller.signal;
    this.authInflight=(async()=>{await Promise.resolve();try{const value=await this.auth({signal,onEvent:event=>{const execution=recordProcessEvent(row,event);if(event.processes)for(const p of event.processes)if(!row.processes.some(x=>x.pid===p.pid&&x.born===p.born))row.processes.push(p);if(execution||event.processes)this.store.saveJournal();}});row.terminal='finished';this.authCache={...value,checkedAt:this.clock()};return this.authCache;
      }catch(error){row.terminal=error.message==='cleanup_uncertain'?'cleanup_uncertain':'failed';if(row.terminal==='cleanup_uncertain'||error.code==='TEAM_STORAGE'){this.store.journal.paused=row.terminal==='cleanup_uncertain'?'cleanup_uncertain':'storage_failed';}throw error;
      }finally{row.endedAt=date();try{this.store.saveJournal();}catch(error){this.authCache=null;if(this.store.journal.paused!=='cleanup_uncertain')this.store.journal.paused='storage_failed';throw error;}finally{this.authController=null;this.authInflight=null;}}})();return this.authInflight;
  }
  async recoverCleanup(){await this.ready;if(this.closed)throw Error('service_closed');if(this.active||this.authInflight)throw Error('team_busy');if(this.cleanupRecovery)return this.cleanupRecovery;this.cleanupRecovery=this.store.recoverCleanup();try{return await this.cleanupRecovery;}finally{this.cleanupRecovery=null;}}
  status(){const row=this.active?.row,last=this.store.journal.runs.filter(r=>r.terminal&&r.terminal!=='skipped_busy'&&(r.task?.contextId||'current')==='current').at(-1),lastAttempt=last?this.store.read('run-'+last.id+'.json'):null;return {version:VERSION,capabilities:TASK_CAPABILITIES,instanceId:this.store.instanceId,config:this.store.config,presence:this.presence.state(),active:row?{id:row.id,asOf:row.asOf,task:row.task,requestHash:row.requestHash,startedAt:row.startedAt,calls:row.calls,stage:this.active.stage,roles:this.active.roles,status:row.terminal||'running',failure:row.reason}:null,lastAttempt:lastAttempt?{id:last.id,status:last.terminal,reason:last.reason,asOf:last.asOf,task:last.task,roles:lastAttempt.roles}:null,conditions:lastAttempt?.conditionChecks||[],auth:this.authCache,paused:this.store.journal?.paused,chief:this.store.accepted('chief'),specialists:Object.fromEntries(Object.keys(ROLES).map(role=>[role,this.store.accepted(role)])),nextSlots:nextSlots(this.store.config,this.clock()),history:this.store.history()};}
  events(){const row=this.store.journal.runs.filter(r=>(r.task?.contextId||'current')==='current'&&r.terminal!=='skipped_busy').at(-1),run=row?this.store.read('run-'+row.id+'.json'):null;return eventReading(run,{accepted:this.store.accepted('events'),chief:this.store.accepted('chief')});}
  persist(job){this.store.write('run-'+job.row.id+'.json',{version:VERSION,row:job.row,roles:job.roles,baselines:job.baselines,receipts:job.receipts,materials:job.materials||[],requirements:job.requirements||[],conditionChecks:job.conditionChecks||[],knowledgeReceipts:job.knowledgeReceipts||{},trace:job.trace,chiefCandidate:job.chiefCandidate||null,audits:job.audits||[]});}
  freezeBaselines(contextId='current'){const baselines={},receipts=new Map();for(const role of [...Object.keys(ROLES),'chief']){const previous=this.store.accepted(role,contextId);baselines[role]=previous?structuredClone(previous):null;if(!previous)continue;const committed=this.store.read('report-'+previous.id+'.json');if(committed?.hash!==hash(committed?.payload))throw Object.assign(Error('invalid_committed_baseline:'+previous.id),{code:'TEAM_STORAGE'});const old=this.store.read('run-'+previous.cycleId+'.json');
    const paths=new Map();for(const claim of previous.report.claims)for(const id of claim.evidenceIds){if(!paths.has(id))paths.set(id,[]);paths.get(id).push(...claim.numbers.filter(n=>n.evidenceId===id).map(n=>n.path));}
    for(const condition of previous.report.conditions||[])if(condition.criterion){const q=condition.criterion;if(!paths.has(q.evidenceId))paths.set(q.evidenceId,[]);paths.get(q.evidenceId).push(q.path);}
    const comparison=macroBaselinePaths(previous,old?.receipts);for(const [id,extra]of comparison){if(!paths.has(id))paths.set(id,[]);paths.get(id).push(...extra);}
    for(const receipt of old?.receipts||[])if(paths.has(receipt.id)){const saved=receipts.get(receipt.id);if(saved){if(saved.receipt.contentHash!==receipt.contentHash||saved.receipt.rawHash!==receipt.rawHash||saved.receipt.asOf!==receipt.asOf)throw Object.assign(Error('conflicting_baseline_identity:'+receipt.id),{code:'TEAM_STORAGE'});saved.roles.push(role);saved.reportIds.push(previous.id);saved.paths.push(...paths.get(receipt.id));saved.comparisonPaths.push(...comparison.get(receipt.id)||[]);continue;}receipts.set(receipt.id,{receipt,paths:paths.get(receipt.id),comparisonPaths:comparison.get(receipt.id)||[],roles:[role],reportIds:[previous.id],originCycleId:receipt.originCycleId||previous.cycleId});}
  }return {baselines,receipts:[...receipts.values()].map(saved=>({...compactReceipt(saved.receipt,saved.paths),historicalBaseline:true,originCycleId:saved.originCycleId,baselineRoles:saved.roles,baselineReportIds:saved.reportIds,...(saved.comparisonPaths.length?{baselineComparisonPaths:[...new Set(saved.comparisonPaths)]}:{})}))};}
  async start({source='manual',requestId=crypto.randomUUID(),question='',...fields}={}){
    await this.ready;if(this.closed)throw Error('service_closed');if(!this.presence.alive())throw Error('development_page_not_present');
    const request=normalizeTaskRequest({requestId,question,...fields}),requestHash=globalThis.BitContentIdentity.contentId(request);
    const old=this.store.findRequest(requestId);if(old){const saved=this.store.read('run-'+old.id+'.json'),oldHash=old.requestHash||globalThis.BitContentIdentity.contentId(normalizeTaskRequest({requestId,question:saved?.row?.question||''}));if(oldHash!==requestHash)throw Error('request_id_conflict');return {id:old.id,status:old.terminal||'running',requestHash:oldHash,task:saved?.row.task||null};}
    if(this.active)throw Error('team_busy');if(this.store.journal.paused)throw Error('team_paused:'+this.store.journal.paused);
    if(request.observation?.to>=this.clock())throw Error('observation_after_server_cutoff');
    if(request.providedMaterials.some(m=>Date.parse(m.content?.reportAsOf||m.content?.report?.asOf)>this.clock()))throw Error('provided_material_after_server_cutoff');
    const id=crypto.randomUUID(),asOf=new Date(this.clock()).toISOString(),contextId=request.taskMode==='current'?'current':'task:'+id,task={schemaVersion:TASK_VERSION,requestHash,contextId,taskMode:request.taskMode,observation:request.observation,clientObservedAt:request.clientObservedAt,materialRefs:request.materialRefs,providedMaterials:request.providedMaterials,dataCutoff:asOf,publicAvailabilityReconstructed:false,requirements:this.taskRequirements(request)},row={id,requestId,requestHash,source,question,task,asOf,startedAt:date(),config:structuredClone(this.store.config),calls:0,processes:[],accepted:{},terminal:null,slot:this.lastSlot};
    const frozen=this.freezeBaselines(contextId),job={row,controller:new AbortController(),started:performance.now(),roles:{},receipts:frozen.receipts,baselines:frozen.baselines,trace:[],materials:[],requirements:[],conditionChecks:[],knowledgeReceipts:{},stage:'discovery'};
    this.store.journal.runs.push(row);try{this.store.saveJournal();this.persist(job);}catch(error){this.store.journal.runs.pop();throw error;}
    this.active=job;job.promise=this.execute(job);return {id,status:'running',requestHash,task};
  }
  taskRequirements(request){const o=request.observation;if(request.taskMode==='narrative')return [{id:'selected_material',role:'events',kind:'material'}];if(!o)return [];
    const map={chart:{role:'env',dataset:'binance-'+(o.product==='spot'?'spot':'perp')+'-klines-'+o.timeframe},orderflow:{role:'flow',tool:'footprint'},heatmap:{role:'flow',tool:'liquidations'},derivatives:{role:'deriv',dataset:'binance-perp-premium'},macro:{role:'macro',dataset:'fred-dgs2'},events:{role:'events',tool:'events'}};return [{id:'selected_'+o.view,...map[o.view]}];}
  toolContext(job,extra={}){return {asOf:job.row.asOf,windowHours:job.row.config.windowHours,task:job.row.task,signal:job.controller.signal,...extra};}
  async retrieveKnowledge(job,role,receipts){job.knowledgeReceipts??={};if(!job.knowledgeRetriever)job.knowledgeRetriever=this.knowledgeFactory?.()||createKnowledgeRetriever();const declared=new Set(Object.keys(ROLES).flatMap(r=>roleDatasets(r))),activeDatasets=[...new Set(receipts.map(r=>r.request?.dataset).filter(id=>declared.has(id)))].sort();const value=await job.knowledgeRetriever.retrieve(role,{question:job.row.question,domains:job.row.task?.observation?[job.row.task.observation.view]:[],activeDatasets,limit:3},{asOf:job.row.asOf,signal:job.controller.signal});job.knowledgeReceipts[role]=value;this.persist(job);return value;}
  async loadMaterials(job,tools){const items=[...job.row.task.materialRefs,...job.row.task.providedMaterials];for(const item of items){await this.gate(job);const receipt={id:crypto.randomUUID(),role:'events',asOf:job.row.asOf,contextId:job.row.task.contextId,request:{tool:'selected-material',source:item.source,id:item.id,contentHash:item.contentHash},requestedAt:date(),numericUnits:{},sourceChain:[item.source+':'+item.id]};
      try{let content,origin;if(item.source.startsWith('provided-')){content=structuredClone(item.content);origin='用户提供；来源未独立核验';}
        else if(item.source==='discovered-event'){const match=/^([a-f0-9-]{36}):([a-f0-9-]{36}):(\d+)$/.exec(item.id);if(!match)throw Error('invalid_discovered_event_id');content=eventMaterial(this.store.read('run-'+match[1]+'.json'),match[2],Number(match[3]));origin='本地团队实际发现的报道材料；保留原轮资料，摘要与摘录不认证外部事实';}
        else if(item.source==='agent-report'){if(!/^[a-f0-9-]{36}$/.test(item.id))throw Error('invalid_agent_report_id');const record=this.store.read('report-'+item.id+'.json');if(!record||record.hash!==hash(record.payload))throw Error('material_report_not_found');content=record.payload;origin='本地Agent原报告；观点是待复核背景，不认证外部事实';}
        else if(item.source==='legacy-report'){if(!/^[a-f0-9-]{36}$/.test(item.id))throw Error('invalid_legacy_report_id');const file=path.resolve('.artifacts/research-team',item.id+'.json');if(!fs.existsSync(file)||fs.statSync(file).size>1024*1024)throw Error('legacy_material_unavailable');content=JSON.parse(fs.readFileSync(file,'utf8'));if(content.id!==item.id&&content.runId!==item.id)throw Error('legacy_material_identity_mismatch');origin='旧本地研究原记录；只作待复核背景';}
        else if(tools.readMaterial){content=await tools.readMaterial(item,this.toolContext(job));origin='指定已存事件原报告；公开时点按原字段，未知保留未知';}else throw Error('material_reader_unavailable');
        if(globalThis.BitContentIdentity.contentId(content)!==item.contentHash)throw Error('material_content_hash_mismatch');
        const report=content.originalReport?.report||content.report,sourceChains=Array.isArray(report?.sources)?report.sources.map(s=>s.url):[],isEvent=['provided-event','discovered-event'].includes(item.source),events=isEvent?[content.event]:[...report?.events||[],...report?.catalysts||[]];
        const usableBackground=events.length>0||!isEvent&&(typeof report?.summary==='string'&&report.summary.trim().length>0||[content,content.run].some(value=>value?.tasks?.some(task=>typeof task.receipt?.output?.summary==='string'&&task.receipt.output.summary.trim().length>0)));
        Object.assign(receipt,{ok:true,usable:!!usableBackground,quality:item.source.startsWith('provided-')?'provided_unverified':item.source==='discovered-event'?'discovered_source_background':'original_report_background',sourceVerified:false,receivedAt:date(),contentHash:item.contentHash,rawResponse:globalThis.BitContentIdentity.canonical(content),sourceChain:sourceChains.length?sourceChains:receipt.sourceChain,data:{material:{id:item.id,source:item.source,parentReportId:item.parentReportId??report?.parentReportId??null,asOf:report?.asOf??content.asOf??null,publicAvailableAt:content.publicAvailableAt??null,origin},items:events,summary:report?.summary??null,sources:report?.sources||[],originalReport:content.originalReport??content},coverage:{completeWindow:false,selectedIdentityMatched:true,sourceIndependentlyVerified:false,strictHistoricalAvailability:false}});job.materials.push({ref:{source:item.source,id:item.id,contentHash:item.contentHash},content,origin});
      }catch(error){if(job.controller.signal.aborted)throw error;Object.assign(receipt,{ok:false,usable:false,quality:'missing_selected_material',error:error.message,data:null,receivedAt:date(),contentHash:null});}
      job.receipts.push(receipt);this.persist(job);
    }}
  conditionPolicy(job,purpose,now=this.clock(),timeoutMs=480000){const remaining=Math.max(0,55*60000-(performance.now()-job.started)),chief=/^chief|semantic-review/.test(purpose),safetyUntil=now+(chief?remaining:Math.min(timeoutMs,remaining)),steps={'5m':300000,'15m':900000,'1h':3600000,'4h':14400000,'1d':86400000,'3d':259200000,'1w':604800000};return {issuedAt:new Date(now).toISOString(),basis:'service-record-point; does not prove user visibility, public availability or prediction performance',safetyUntil:new Date(safetyUntil).toISOString(),covers:chief?'remaining whole research deadline including audit':'this bounded specialist call',earliestFromByTimeframe:Object.fromEntries(Object.entries(steps).map(([interval,step])=>[interval,klineOpenAt(interval,safetyUntil)+step])),acceptance:'deterministic from must be at or after actual server registration; original invalid definitions are rejected, never shifted'};}
  researchTodos(previous,seen=new Set()){if(!previous||seen.has(previous.id))return [];seen.add(previous.id);const own=(previous.conditionLedger||this.store.reportConditions(previous)).filter(c=>c.kind==='manual').map(c=>({id:c.id,text:c.text,role:c.role,parentReportId:c.parentReportId}));if(own.length||!Object.hasOwn(previous.report,'researchProgress'))return own;const id=previous.report.viewChange?.previousReportId,parent=id?this.store.read('report-'+id+'.json')?.payload:null;if(!parent||parent.role!==previous.role||(parent.task?.contextId||'current')!==(previous.task?.contextId||'current'))return [];const resolved=new Set((previous.report.researchProgress||[]).filter(p=>p.state==='completed'||p.state==='capability_bound').map(p=>p.todoId));return this.researchTodos(parent,seen).filter(todo=>!resolved.has(todo.id));}
  checkResearchProgress(report,job,role){const known=new Set(this.researchTodos(job.baselines[role]).map(t=>t.id)),answered=new Set();for(const p of report.researchProgress||[]){if(!known.has(p.todoId))throw Error('research_progress_parent_mismatch');answered.add(p.todoId);}const missing=[...known].filter(id=>!answered.has(id));if(missing.length)throw Object.assign(Error('research_progress_incomplete'),{validationDetails:{missingTodoIds:missing,instruction:'逐项交代提供的旧待办：完成、未解决或能力边界；不得省略或以空数组覆盖。'}});}
  checkConditionDefinitions(report,job,role,at=this.clock()){this.checkResearchProgress(report,job,role);const previous=job.baselines[role],known=new Set([...(previous?.conditionLedger||this.store.reportConditions(previous||{report:{}})),...this.store.pendingConditions(job.row.task?.contextId||'current').filter(c=>c.role===role)].map(c=>c.id));for(const c of report.conditions||[]){if(c.kind==='deterministic'&&c.from<at)throw Error('condition_starts_before_registration:'+c.from+':'+new Date(at).toISOString());if(c.revisesConditionId&&!known.has(c.revisesConditionId))throw Error('condition_revision_parent_mismatch');if(c.criterion&&role!=='chief'&&!roleDatasets(role).includes(c.criterion.dataset))throw Error('condition_dataset_scope_denied');}}
  conditionOrigin(condition){const q=condition.criterion,base={marketEvidence:false,purpose:'original registered threshold only; not a new market claim',parentReportId:condition.parentReportId,evidenceId:q.evidenceId,path:q.path,value:q.value,unit:q.unit,status:'unknown',reason:'原阈值来源未取得或旧稀疏原件不含此路径',receipt:null};const record=this.store.read('report-'+condition.parentReportId+'.json');if(!record)return base;if(record.hash!==hash(record.payload))throw Object.assign(Error('invalid_condition_parent:'+condition.parentReportId),{code:'TEAM_STORAGE'});const saved=record.payload.conditionLedger?.find(c=>c.id===condition.id);if(!saved||JSON.stringify(saved.criterion)!==JSON.stringify(q))return {...base,reason:'条件定义与封存父报告不匹配'};const source=this.store.read('run-'+record.payload.cycleId+'.json')?.receipts?.find(r=>r.id===q.evidenceId),value=fieldAt(source?.data,q.path);if(!source?.ok||!source.usable||value===null||value===''||!Number.isFinite(Number(value))||Math.abs(Number(value)-q.value)>Math.max(1e-9,Math.abs(q.value)*1e-8)||source.numericUnits?.[q.path]!==q.unit)return base;return {...base,status:'saved_source_matched',reason:'仅证明原封存路径/数值/单位对应，不证明前向登记、公开可得性或预测表现',receipt:modelRowDefaults(historicalModelReceipt({...source,historicalBaseline:true},[q.path]))};}
  async checkConditions(job,tools){const conditions=this.store.pendingConditions(job.row.task.contextId);for(const previous of Object.values(job.baselines)){if(previous)conditions.push(...(previous.conditionLedger||this.store.reportConditions(previous)).filter(c=>c.kind==='manual'));}const unique=new Map(conditions.map(c=>[c.id,c]));for(const condition of unique.values()){const role=condition.role;await this.gate(job);const check={...condition,...conditionTiming(condition),state:'unknown',checkedAt:date(),evidenceIds:[],query:null,coverage:null,observedValues:[],reason:'自然语言建议保持待核查，不自动解释为结构化阈值'};
      if(condition.kind==='deterministic'&&condition.criterion)check.thresholdOrigin=this.conditionOrigin(condition);
      if(condition.kind==='deterministic'&&condition.criterion){const q=condition.criterion,to=Math.min(condition.to,Date.parse(job.row.asOf)-1);if(to>=condition.from){const timeframe=q.dataset.slice(q.dataset.lastIndexOf('-')+1),observation={exchange:'binance',symbol:'BTCUSDT',product:q.dataset.includes('-spot-')?'spot':'perpetual',view:'chart',timeframe,from:condition.from,to},request={tool:'dataset',dataset:q.dataset,limit:200,windowHours:Math.max(1,Math.ceil((to-condition.from+1)/3600000))},executor=role==='chief'?'env':role;
          const receipt=await tools.execute(executor,request,this.toolContext(job,{observation,conditionCheck:true}));job.receipts.push({...receipt,conditionEvidenceOnly:true});check.query={request,observation,dataCutoff:job.row.asOf};check.evidenceIds=[receipt.id];check.coverage=receipt.coverage||null;
          const values=(receipt.data?.observations||[]).filter(row=>row.values?.[q.field]!==null&&Number.isFinite(Number(row.values?.[q.field]))).map(row=>({observedAt:row.observedAt,value:Number(row.values[q.field]),unit:q.unit}));check.observedValues=values;
          const compare={gt:v=>v>q.value,gte:v=>v>=q.value,lt:v=>v<q.value,lte:v=>v<=q.value,eq:v=>v===q.value}[q.operator];const unitsOk=(receipt.data?.observations||[]).every((row,index)=>row.values?.[q.field]===null||!Number.isFinite(Number(row.values?.[q.field]))||receipt.numericUnits?.['observations.'+index+'.values.'+q.field]===q.unit);
          if(receipt.ok&&receipt.usable&&unitsOk&&values.length&&values.some(row=>compare(row.value))){check.state='triggered';check.reason='已取得闭合栏满足登记阈值；不推断因果';}
          else if(receipt.ok&&receipt.usable&&unitsOk&&values.length&&receipt.coverage?.completeWindow===true){check.state=this.clock()>=condition.deadline&&to>=condition.to?'expired':'not_triggered';check.reason=check.state==='expired'?'取得完整完成范围，期限内未观察到登记阈值':'完整覆盖已检查部分，尚未观察到登记阈值';}
          else check.reason=receipt.error||'未取得完整有效条件范围；不能判未触发或到期';
        }else check.reason='条件观察范围尚未开始';}
      job.conditionChecks.push(check);this.store.saveConditionCheck(check);this.persist(job);
    }}
  checkpoint(job){if(job.controller.signal.aborted)throw Error('research_cancelled');if(this.presence.state()==='absent')throw Error('page_presence_lost');if(performance.now()-job.started>=55*60000)throw Error('research_deadline');}
  refreshRequirements(job){job.requirements=job.row.task.requirements.map(requirement=>{
    const selected=job.receipts.filter(r=>r.role===requirement.role&&!r.historicalBaseline&&!r.conditionEvidenceOnly&&(requirement.kind==='material'?r.request?.tool==='selected-material':requirement.dataset?r.request?.dataset===requirement.dataset:r.request?.tool===requirement.tool)),usable=selected.filter(r=>r.ok&&r.usable);
    return {...requirement,available:usable.length>0,evidenceIds:selected.map(r=>r.id),completeWindow:usable.some(r=>r.coverage?.completeWindow===true),reason:usable.length?'available with receipt coverage limits':'selected capability/data unavailable'};
  });return job.requirements;}
  async gate(job){while(this.presence.state()==='grace'){this.checkpoint(job);await new Promise(resolve=>setTimeout(resolve,250));}this.checkpoint(job);}
  async model(job,purpose,prompt,schema,reserved=0,timeoutCapMs=Infinity){
    schema=modelSchema(schema);
    await this.gate(job);if(job.row.calls>=job.row.config.maxCalls-reserved)throw Error('model_call_budget');
    if(/:research:/.test(purpose)&&job.row.calls===0&&this.dailyRemaining(job.row.config)<7)throw Error('daily_call_budget');
    const auth=await this.checkAuth();if(!auth.available){this.store.journal.paused='auth';this.store.saveJournal();throw Error(auth.message);}await this.gate(job);
    const now=this.clock(),day=localDay(now,job.row.config.timezone),spent=job.row.config.dailyCalls-this.dailyRemaining(job.row.config);
    if(spent>=job.row.config.dailyCalls)throw Error('daily_call_budget');
    if(spent>=job.row.config.dailyCalls-reserved)throw Error('daily_model_reserve');
    const timeoutMs=Math.min(720000,55*60000-(performance.now()-job.started),timeoutCapMs);if(typeof prompt==='function')prompt=prompt(this.conditionPolicy(job,purpose,now,timeoutMs));
    const attempt={id:crypto.randomUUID(),purpose,promptHash:hash(prompt),promptBytes:Buffer.byteLength(prompt),schemaHash:hash(schema),promptVersion:PROMPT_VERSION,startedAt:date(),timeoutMs,day,status:'intent',executions:[]};
    job.row.callDays??={};job.row.callDays[day]=(job.row.callDays[day]||0)+1;job.row.callTimes??=[];job.row.callTimes.push(now);
    job.trace.push(attempt);job.row.calls++;this.store.saveJournal();this.persist(job);
    job.stage=purpose;
    // Reuse this call's successful preflight; the official CLI still forces ChatGPT login.
    try{const result=await this.provider(prompt,schema,{signal:job.controller.signal,timeoutMs,authCheck:async()=>auth,onEvent:event=>{
      const execution=recordProcessEvent(job.row,event);if(execution&&!attempt.executions.includes(execution))attempt.executions.push(execution);
      if(event.processes)for(const p of event.processes)if(!job.row.processes.some(x=>x.pid===p.pid&&x.born===p.born))job.row.processes.push(p);
      if(execution||event.processes){this.store.saveJournal();this.persist(job);}
      if(event.diagnostic){attempt.providerDiagnostic=event.diagnostic;this.persist(job);}
      if(event.type==='turn.failed'&&/quota|usage limit|rate limit/i.test(JSON.stringify(event))){this.store.journal.paused='quota';this.store.saveJournal();job.controller.abort();}
      attempt.lastProgress={at:date(),event:event.event||event.type,itemType:event.itemType};this.store.write('progress-'+job.row.id+'.json',attempt.lastProgress);
    }});this.checkpoint(job);if(schema.properties.conditions&&result.output?.conditions===undefined)result.output.conditions=[];if(result.output?.report&&schema.properties.report&&result.output.report.conditions===undefined)result.output.report.conditions=[];if(schema.properties.researchProgress&&result.output?.researchProgress===undefined)result.output.researchProgress=[];if(result.output?.report&&schema.properties.report&&result.output.report.researchProgress===undefined)result.output.report.researchProgress=[];validateSchema(result.output,schema);attempt.status='returned';attempt.finishedAt=date();attempt.output=result.output;attempt.provenance=result.provenance;this.persist(job);return result;
    }catch(error){attempt.status='failed';attempt.finishedAt=date();attempt.error=error.message;attempt.errorCode=error.code;attempt.errorPhase=error.phase;attempt.cleanup=error.cleanup;if(error.providerDiagnostic)attempt.providerDiagnostic=error.providerDiagnostic;this.persist(job);throw error;}
  }
  finalRecoveryBudget(job,role,error,round,finalOnly,clarification){const attempt=job.trace.findLast(t=>t.purpose===role+':research:'+round),execution=attempt?.executions?.findLast(p=>p.phase==='model');if(round!==1||finalOnly||clarification||error.code!=='CODEX_PROCESS_DEADLINE'||error.phase!=='model'||error.cleanup!=='confirmed'||execution?.state!=='finished'||execution.cleanup!=='confirmed'||execution.stopped!==true||job.controller.signal.aborted||this.store.journal.paused||job.row.calls+3>job.row.config.maxCalls||this.dailyRemaining(job.row.config)<3)return null;
    const roles=Object.keys(ROLES),later=roles.slice((Math.floor(roles.indexOf(role)/2)+1)*2),pendingGroups=new Set(later.filter(r=>!['accepted','unchanged','failed','insufficient'].includes(job.roles[r]?.status)).map(r=>Math.floor(roles.indexOf(r)/2))).size,remaining=55*60000-(performance.now()-job.started),reservedMs=2*(720000+15000)+pendingGroups*(720000+15000)+15000,timeoutMs=Math.min(720000,remaining-reservedMs);return timeoutMs>=60000?{timeoutMs,reservedMs,pendingGroups}:null;}
  async specialist(job,tools,role,seeds,clarification=null){
    const previous=job.baselines[role],clarificationOf=clarification?structuredClone(job.roles[role]):null;job.roles[role]={status:'researching',previousId:previous?.id||null};this.persist(job);
    try{
      const eligible=seeds.some(r=>r.ok&&r.usable);
      if(!eligible){
        const referenceWindowEmpty=role==='macro'&&job.row.task?.observation&&ROLES.macro.datasets.every(dataset=>seeds.some(r=>r.request?.dataset===dataset&&r.ok&&!r.usable&&r.coverage?.referencePeriodContext===true&&r.coverage.windowAppliedToReferencePeriods===true&&r.coverage.returnedInWindow===0));
        const report=gap(referenceWindowEmpty?'宏观序列已读取，按所选区间筛选后未取得参考期记录。参考期不是公布时间，不能据此认定窗内没有宏观消息或影响。':'本轮未取得可用的本领域材料。',previous);
        if(referenceWindowEmpty)report.nextChecks=['研究该区间的宏观影响，仍需发布日历与实际公布时点；当前参考期筛选不能回答，尚未取得的公布时点保持未知。'];
        job.roles[role]={status:'insufficient',report,mode:'deterministic_missing_evidence'};return;
      }
      const knowledge=await this.retrieveKnowledge(job,role,[...seeds,...job.receipts.filter(r=>r.historicalBaseline&&r.baselineRoles.includes(role))]),fingerprint=hash({evidence:seeds.map(r=>({hash:r.contentHash,quality:r.quality,coverage:r.coverage,sourceChain:r.sourceChain})),knowledge:knowledge?{version:knowledge.registryVersion,registryHash:knowledge.registryHash,hashes:knowledge.receipts.map(r=>r.contentHash)}:null});
      const unresolved=job.conditionChecks?.some(c=>c.role===role&&c.kind==='deterministic'&&['unknown','triggered','expired'].includes(c.state));
      if(!clarification&&!job.row.question&&!job.row.task?.materialRefs?.length&&!job.row.task?.providedMaterials?.length&&!unresolved&&job.row.task?.taskMode==='current'&&previous?.promptVersion===PROMPT_VERSION&&previous.autonomousToolRequests?.length===0&&previous?.fingerprint===fingerprint&&seeds.every(r=>r.ok&&r.usable&&r.coverage?.discoverySucceeded!==false)&&Date.parse(previous.asOf)+Math.max(3600000,job.row.config.intervalMinutes*120000)>=Date.parse(job.row.asOf)){const old=this.store.read('run-'+previous.cycleId+'.json');for(const receipt of old?.receipts||[])if(previous.evidenceIds.includes(receipt.id)&&!job.receipts.some(r=>r.id===receipt.id))job.receipts.push(receipt);job.roles[role]={status:'unchanged',report:previous.report,id:previous.id,asOf:previous.asOf,checkedAt:date(),mode:'same_default_evidence; manual next observations remain unknown'};return;}
      // Shared question material is background, not another specialist's opinion or a market seed.
      let receipts=[...seeds,...job.receipts.filter(r=>r.request?.tool==='selected-material'&&!seeds.some(s=>s.id===r.id)),...job.receipts.filter(r=>r.historicalBaseline&&r.baselineRoles.includes(role)&&!seeds.some(s=>s.id===r.id))],decisions=[],recovery=null;
      for(let round=0;round<3;round++){
        const finalOnly=!!clarification||round===2||job.row.calls>=job.row.config.maxCalls-3||!!recovery;await this.retrieveKnowledge(job,role,receipts);
        const input={cycleId:job.row.id,asOf:job.row.asOf,task:job.row.task,requirements:job.requirements||[],knowledgeReceipts:job.knowledgeReceipts?.[role]||null,researchTodos:this.researchTodos(previous),conditionChecks:(job.conditionChecks||[]).filter(c=>c.role===role),role,round,question:job.row.question,clarification,clarificationOf:clarificationOf?{id:clarificationOf.id,asOf:clarificationOf.asOf,report:clarificationOf.report}:null,tools:roleDatasets(role),additionalTools:role==='events'?['events','article']:role==='flow'?['footprint','liquidations']:[],previous:previous?{id:previous.id,asOf:previous.asOf,report:previous.report}:null,receipts:specialistModelReceipts(receipts,previous),decisions};
        let result;try{result=await this.model(job,role+':research:'+round,policy=>specialistPrompt(role,{...input,conditionRegistrationPolicy:policy},finalOnly),decisionSchema(role,finalOnly),2,recovery?.timeoutMs);}catch(error){const budget=this.finalRecoveryBudget(job,role,error,round,finalOnly,clarification);if(!budget)throw error;recovery=budget;decisions.push({attemptFailed:{purpose:role+':research:'+round,code:error.code,phase:error.phase,cleanup:error.cleanup},instruction:'上一模型执行达到单步截止且进程清理已确认，没有可接受输出。仅用现有回执收口关键判断、反证和缺口；本次必须final/insufficient且tools为空，不增加来源，不编造未返回的观点。',budget});continue;}const output=result.output;decisions.push(output);
        if(output.kind==='tools'){
          if(!output.tools.length||output.report!==null)throw Error('invalid_tool_decision');
          for(const request of output.tools){await this.gate(job);const reused=reusableToolReceipt(receipts,role,request,{asOf:job.row.asOf,windowHours:job.row.config.windowHours,contextId:job.row.task?.contextId||'current'});if(reused){decisions.push({toolReused:{request,evidenceId:reused.id,coverage:reused.coverage},instruction:'同一锚点与参数已有成功材料，沿用原回执；没有扩展覆盖，也不新增独立证据。每次最多200行，相同请求不能突破上限。按实际覆盖收口，或选择已登记的不同周期/范围；不得承诺下次相同请求能补齐。'});continue;}const receipt=await tools.execute(role,request,this.toolContext(job));receipts.push(receipt);job.receipts.push(receipt);this.refreshRequirements(job);this.persist(job);}continue;
        }
        if(output.tools.length||!output.report)throw Error('invalid_final_decision');try{validateReport(output.report,receipts,undefined,{completeNumericText:true});this.checkConditionDefinitions(output.report,job,role);}catch(error){if(finalOnly)throw error;decisions.push({validationRejected:error.message,validationDetails:error.validationDetails,instruction:'上一候选未接受。完整覆盖旧待办；正文每个量值均需相应数值引用，少写也不能半段引用。失败或不可用回执只写缺口/反证，不作为claims市场事实；过窗条件不能冒充前向登记，按本次conditionRegistrationPolicy重新给合法定义或撤为manual/conditions=[]，不得自动挪动原条件。'});continue;}
        if(output.report.viewChange.previousReportId!==(previous?.id||null))throw Error('wrong_previous_report');
        const payload={role,cycleId:job.row.id,asOf:job.row.asOf,task:job.row.task,requirements:job.requirements||[],conditionChecks:(job.conditionChecks||[]).filter(c=>c.role===role),generatedAt:date(),report:output.report,clarifiesReportId:clarificationOf?.id||null,provenance:result.provenance,promptVersion:PROMPT_VERSION,fingerprint,autonomousToolRequests:decisions.flatMap(d=>d.tools||[]),evidenceIds:receipts.map(r=>r.id)};
        let accepted;try{accepted=this.store.commit(job.row,role,payload);}catch(error){if(finalOnly||!error.message.startsWith('condition_starts_before_registration:'))throw error;decisions.push({validationRejected:error.message,instruction:'服务实际登记点已超过原窗口起点，原定义未登记。按最新安全建议重新交付，或撤为manual/conditions=[]。'});continue;}job.roles[role]={status:'accepted',...accepted};return;
      }
      throw Error('research_round_budget');
    }catch(error){if(error.code==='TEAM_STORAGE'||['cleanup_uncertain','daily_call_budget'].includes(error.message)){job.fatal=error.code==='TEAM_STORAGE'?'storage_failed':error.message;job.controller.abort();throw error;}if(job.controller.signal.aborted)throw error;job.roles[role]={status:'failed',error:error.message,previousId:previous?.id||null};}
    finally{this.persist(job);}
  }
  async execute(job){const timer=setTimeout(()=>{job.row.reason='research_deadline';job.controller.abort();},55*60000);
    try{
      const tools=this.toolsFactory(),seeds={};job.knowledgeRetriever=this.knowledgeFactory();
      await this.loadMaterials(job,tools);await this.checkConditions(job,tools);
      for(let i=0;i<Object.keys(ROLES).length;i+=2){const results=await Promise.allSettled(Object.keys(ROLES).slice(i,i+2).map(async role=>{await this.gate(job);seeds[role]=await tools.discover(role,this.toolContext(job));job.receipts.push(...seeds[role]);if(role==='events')seeds[role].push(...job.receipts.filter(r=>r.role==='events'&&r.request?.tool==='selected-material'));this.persist(job);}));const failed=results.find(r=>r.status==='rejected');if(failed)throw failed.reason;}
      this.refreshRequirements(job);this.persist(job);
      const config=job.row.config;
      for(let i=0;i<Object.keys(ROLES).length;i+=2){const results=await Promise.allSettled(Object.keys(ROLES).slice(i,i+2).map(role=>this.specialist(job,tools,role,seeds[role])));const failed=results.find(r=>r.status==='rejected');if(failed)throw failed.reason;}
      this.refreshRequirements(job);this.persist(job);
      const usable=Object.values(job.roles).some(r=>['accepted','unchanged'].includes(r.status)&&r.report?.claims.length);
      if(!usable||job.requirements.some(r=>!r.available)){job.row.terminal='insufficient';job.row.reason=job.requirements.some(r=>!r.available)?'指定任务所需材料未取得，不以其他领域成功替代':'没有可用于首席综合的岗位判断';return;}
      const previous=job.baselines.chief;
      if(this.canReuseChief(job,previous)){job.row.terminal='checked';job.row.reason='已检查，岗位版本与原首席一致；保留原首席报告生成时间';return;}
      const input={cycleId:job.row.id,asOf:job.row.asOf,task:job.row.task,requirements:job.requirements,conditionChecks:job.conditionChecks,knowledgeReceipts:job.knowledgeReceipts.chief,researchTodos:this.researchTodos(previous),question:job.row.question,clarificationAvailable:job.row.calls+4<=config.maxCalls&&this.dailyRemaining(config)>=4,previous:previous?{id:previous.id,report:previous.report,asOf:previous.asOf}:null,...chiefMaterials(job)};
      input.knowledgeReceipts=await this.retrieveKnowledge(job,'chief',[...input.receipts,...input.historicalReceipts]);
      let candidate=await this.model(job,'chief',policy=>chiefPrompt({...input,conditionRegistrationPolicy:policy}),CHIEF_SCHEMA,1);
      if(candidate.output.clarifications.length){
        if(!input.clarificationAvailable)throw Error('chief_clarification_budget');const request=candidate.output.clarifications[0];
        job.trace.push({purpose:'chief-question',request,at:date()});await this.specialist(job,tools,request.role,job.receipts.filter(r=>r.role===request.role&&!r.historicalBaseline),request.question);
        input.clarificationAvailable=false;Object.assign(input,chiefMaterials(job));input.clarification=request;
        input.knowledgeReceipts=await this.retrieveKnowledge(job,'chief',[...input.receipts,...input.historicalReceipts]);
        candidate=await this.model(job,'chief-after-clarification',policy=>chiefPrompt({...input,conditionRegistrationPolicy:policy}),CHIEF_SCHEMA,1);
      }
      for(let attempt=0;attempt<2;attempt++){
        let validationError=null,registrationError=null,review=null;
        try{validateReport(candidate.output,job.receipts,CHIEF_SCHEMA,{completeNumericText:true});this.checkResearchProgress(candidate.output,job,'chief');if(candidate.output.viewChange.previousReportId!==(previous?.id||null))throw Error('chief_wrong_previous_report');
          if(candidate.output.clarifications.length)throw Error('chief_repeated_clarification');
          if(candidate.output.dispositions.length!==Object.keys(ROLES).length||new Set(candidate.output.dispositions.map(d=>d.role)).size!==Object.keys(ROLES).length)throw Error('chief_missing_or_duplicate_role_disposition');
          for(const disposition of candidate.output.dispositions)if(disposition.treatment==='adopt'&&(!['accepted','unchanged'].includes(job.roles[disposition.role]?.status)||job.roles[disposition.role].report.status==='insufficient'))throw Error('chief_adopts_missing_role');
        }catch(error){if(error.code||error.name!=='Error'||error.message.startsWith('conflicting_evidence_identity:'))throw error;validationError=error;job.trace.push({purpose:'chief-validation-rejected',candidateHash:hash(candidate.output),error:error.message,details:error.validationDetails||null,at:date()});this.persist(job);}
        if(!validationError){job.chiefCandidate=candidate.output;this.persist(job);try{this.checkConditionDefinitions(candidate.output,job,'chief');}catch(error){if(!error.message.startsWith('condition_starts_before_registration:'))throw error;registrationError=error.message;}}
        if(!validationError&&!registrationError){const materials=chiefMaterials(job,[candidate.output]),knowledgeReceipts=await this.retrieveKnowledge(job,'review',[...materials.receipts,...materials.historicalReceipts]);review=await this.model(job,'semantic-review',policy=>reviewPrompt({...input,...materials,conditionRegistrationPolicy:policy,knowledgeReceipts,candidate:candidate.output}),REVIEW_SCHEMA);job.audits??=[];job.audits.push({output:review.output,provenance:review.provenance,candidateHash:hash(candidate.output)});this.persist(job);}
        if(review?.output.verdict==='accept'){
          if(review.output.issues.length)throw Error('review_accept_with_issues');
          try{this.checkConditionDefinitions(candidate.output,job,'chief');this.store.commit(job.row,'chief',{role:'chief',cycleId:job.row.id,asOf:job.row.asOf,task:job.row.task,requirements:job.requirements,conditionChecks:job.conditionChecks,generatedAt:date(),report:candidate.output,provenance:candidate.provenance,promptVersion:PROMPT_VERSION,evidenceIds:job.receipts.map(r=>r.id),semanticAudit:job.audits.at(-1)});job.row.terminal=candidate.output.status==='sufficient'&&Object.values(job.roles).every(r=>r.report?.status==='sufficient')?'complete':'limited';return;}catch(error){if(!error.message.startsWith('condition_starts_before_registration:'))throw error;registrationError=error.message;}
        }
        if(registrationError){job.trace.push({purpose:'condition-registration-rejected',candidateHash:hash(candidate.output),error:registrationError,at:date()});this.persist(job);}
        if(attempt===1||job.row.calls+2>config.maxCalls)throw Error(validationError?.message||registrationError||'semantic_review_rejected');const issues=validationError?[validationError.message+'；上一候选未接受。完整重交并通过所有数字/来源/时序/岗位契约后才可审核；Node不修值、不猜替代ID。',...(validationError.validationDetails?['确定性原回执对照：'+JSON.stringify(validationError.validationDetails)]:[])]:registrationError?[registrationError+'；候选未登记。按最新conditionRegistrationPolicy给真正未来的新定义，或撤为manual/conditions=[]；不能把原窗强行平移后冒称原条件。']:(review?.output.issues||[]);candidate=await this.model(job,'chief-revision',policy=>chiefPrompt({...input,...chiefMaterials(job,[candidate.output]),conditionRegistrationPolicy:policy,reviewIssues:issues,previousCandidate:candidate.output}),CHIEF_SCHEMA,1);
      }
    }catch(error){job.controller.abort();job.row.terminal=error.code==='TEAM_STORAGE'||job.fatal==='storage_failed'?'storage_failed':job.fatal==='cleanup_uncertain'||error.message==='cleanup_uncertain'?'cleanup_uncertain':job.row.reason==='user_cancelled'||job.row.reason==='page_closed'?'cancelled':'failed';job.row.reason??=job.fatal||error.message;if(['cleanup_uncertain','storage_failed'].includes(job.row.terminal))this.store.journal.paused=job.row.terminal;}
    finally{clearTimeout(timer);job.row.endedAt=date();try{this.persist(job);this.store.saveJournal();}catch(error){job.row.terminal='storage_failed';job.row.reason=error.message;this.store.journal.paused='storage_failed';}
      if(this.active===job)this.active=null;}
  }
  cancel(reason='user_cancelled'){if(!this.active||this.active.row.terminal)return;this.active.row.reason=reason;this.active.stage='cancelling';this.active.controller.abort();}
  dailyRemaining(config){const day=localDay(this.clock(),config.timezone),spent=(this.store.journal.archivedCallTimes||[]).filter(at=>localDay(at,config.timezone)===day).length+this.store.journal.runs.reduce((n,r)=>n+(r.callTimes?r.callTimes.filter(at=>localDay(at,config.timezone)===day).length:Object.entries(r.callDays||{}).filter(([key])=>key===day).reduce((a,[,count])=>a+count,0)),0);return Math.max(0,config.dailyCalls-spent);}
  canReuseChief(job,previous){if(!previous||previous.promptVersion!==PROMPT_VERSION||job.conditionChecks?.some(c=>c.kind==='deterministic'&&c.state!=='not_triggered'))return false;const original=this.store.read('run-'+previous.cycleId+'.json');return Object.keys(ROLES).every(role=>job.roles[role]?.status==='unchanged'&&job.roles[role].id&&['accepted','unchanged'].includes(original?.roles?.[role]?.status)&&job.roles[role].id===original.roles[role].id);}
  async tick(){if(this.closed)return;await this.ready;if(this.closed)return;if(this.presence.state()==='absent'&&this.active)this.cancel('page_closed');if(!this.presence.alive()||!this.store.config.enabled||this.store.journal.paused)return;
    if(this.lastPresenceGeneration!==this.presence.generation){this.lastPresenceGeneration=this.presence.generation;this.lastSlot=scheduleSlot(this.store.config,this.presence.resumedAt??this.clock())?.id||null;}
    const slot=scheduleSlot(this.store.config,this.clock());if(!slot||this.lastSlot===slot.id)return;this.lastSlot=slot.id;
    if(this.store.journal.runs.some(r=>r.slot===slot.id))return;
    if(this.active){this.store.journal.runs.push({id:crypto.randomUUID(),slot:slot.id,source:'scheduled',asOf:date(),startedAt:date(),endedAt:date(),terminal:'skipped_busy',calls:0,accepted:{},reason:'当前研究未结束，本时段跳过'});this.store.saveJournal();return;}
    await this.start({source:'scheduled'});
  }
  close(){if(!this.closePromise)this.closePromise=(async()=>{this.closed=true;try{await this.ready;}catch{}this.cancel('development_service_closed');this.authController?.abort();await Promise.allSettled([this.active?.promise,this.authInflight,this.cleanupRecovery].filter(Boolean));if(!this.active)this.store.release();})();return this.closePromise;}
}
export function agentTeamBridge(options={}){
  let service;
  return {name:'local-agent-team',configureServer(server){
    // Acquire the writer only after the port is actually owned. A failed bind
    // must never leave a half-created ownership transition behind.
    server.httpServer?.once('listening',()=>{service=new TeamService(options);service.ready.catch(()=>{});});
    const timer=setInterval(()=>{if(service)service.tick().catch(error=>{service.backgroundError=error.message;});},1000);
    const hardStop=setTimeout(()=>{void server.close().catch(error=>{if(service)service.backgroundError=error.message;});},8*3600000);
    const originalClose=server.close.bind(server);let closing=null,closed=false;const closeTeam=()=>{closed=true;clearInterval(timer);clearTimeout(hardStop);return service?.close();};
    server.close=()=>closing??=(async()=>{try{await closeTeam();}finally{await originalClose();}})();
    server.httpServer?.once('close',()=>{void Promise.resolve(closeTeam()).catch(error=>{if(service)service.backgroundError=error.message;});});
    server.middlewares.use(async(req,res,next)=>{
      const url=new URL(req.url,'http://127.0.0.1');
      const legacy=url.pathname.startsWith('/api/local-research/');
      if(!url.pathname.startsWith('/api/local-agent-team/')&&!legacy)return next();
      const send=(data,status=200)=>{res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.end(JSON.stringify(data));};
      try{
        if(!/^(localhost|127\.0\.0\.1):\d+$/.test(req.headers.host||''))return send({error:'loopback_only'},403);
        const origin='http://'+req.headers.host;if(req.headers.origin&&req.headers.origin!==origin)return send({error:'same_origin_only'},403);
        if(req.method!=='GET'&&(req.headers.origin!==origin||!String(req.headers['content-type']).startsWith('application/json')))return send({error:'same_origin_json_required'},403);
        if(legacy){if(req.method!=='GET')return send({error:'legacy_execution_retired'},410);return legacyRead(url,res);}
        if(!service)throw Error('service_initializing');await service.ready;const tail=url.pathname.slice('/api/local-agent-team/'.length);
        if(req.method==='GET'&&tail==='presence'){
          const id=url.searchParams.get('id');if(!/^[a-f0-9-]{36}$/.test(id||''))throw Error('invalid_tab_id');const nonce=crypto.randomUUID();service.presence.connect(id,nonce);
          res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-store','Connection':'keep-alive'});
          const ping=()=>{res.write('data: '+JSON.stringify({nonce,instanceId:service.store.instanceId})+'\n\n');};ping();const stream=setInterval(ping,30000);res.once('close',()=>{clearInterval(stream);service.presence.disconnect(id,nonce);});return;
        }
        if(req.method==='GET'&&tail==='status')return send({...service.status(),backgroundError:service.backgroundError||null});
        if(req.method==='GET'&&tail==='events')return send(service.events());
        if(req.method==='GET'&&tail==='config')return send({config:service.store.config,capabilities:TASK_CAPABILITIES,nextSlots:nextSlots(service.store.config,service.clock())});
        if(req.method==='GET'&&tail==='runs')return send(service.store.historyPage({offset:Number(url.searchParams.get('offset')||0),limit:Number(url.searchParams.get('limit')||50),contextId:url.searchParams.get('contextId')}));
        if(req.method==='GET'&&/^contexts\/task:[a-f0-9-]{36}$/.test(tail)){const contextId=tail.slice(9);return send({contextId,chief:service.store.accepted('chief',contextId),specialists:Object.fromEntries(Object.keys(ROLES).map(role=>[role,service.store.accepted(role,contextId)]))});}
        if(req.method==='GET'&&/^runs\/[a-f0-9-]{36}\/export$/.test(tail)){const id=tail.split('/')[1],run=service.store.read('run-'+id+'.json');if(!run)throw Error('run_not_found');const reports={};for(const {id:reportId}of run.row.commits||Object.entries(run.row.accepted||{}).map(([role,id])=>({role,id}))){const record=service.store.read('report-'+reportId+'.json');if(!record||record.hash!==hash(record.payload))throw Error('invalid_report');reports[reportId]=record.payload;}const bundle={version:VERSION,source:'local-agent-team',run,reports};return send({...bundle,contentHash:globalThis.BitContentIdentity.contentId(bundle)});}
        if(req.method==='GET'&&/^runs\/[a-f0-9-]{36}$/.test(tail))return send(service.store.read('run-'+tail.slice(5)+'.json')||{error:'run_not_found'});
        if(req.method==='GET'&&/^reports\/[a-f0-9-]{36}$/.test(tail)){const record=service.store.read('report-'+tail.slice(8)+'.json');if(!record||record.hash!==hash(record.payload))throw Error('invalid_report');return send(record.payload);}
        if(req.method!=='POST')return send({error:'route_not_found'},404);
        const body=await readBody(req);if(closed||service.closed)throw Error('service_closed');
        if(tail==='presence'){service.presence.ack(body.id,body.nonce);return send({ok:true});}
        if(tail==='config'){const config=service.store.saveConfig(body);service.lastSlot=scheduleSlot(config,service.clock())?.id||null;if(config.enabled&&service.store.journal.paused!=='cleanup_uncertain'&&service.store.journal.paused!=='storage_failed'){service.store.journal.paused=null;service.store.saveJournal();}return send({config,nextSlots:nextSlots(config,service.clock())});}
        if(tail==='auth')return send(await service.checkAuth(true));
        if(tail==='recover-cleanup'){if(Object.keys(body).length)throw Error('invalid_cleanup_recovery_request');return send(await service.recoverCleanup());}
        if(tail==='runs')return send(await service.start({source:'manual',...body}),202);
        if(tail==='cancel'){if(Object.keys(body).some(k=>k!=='id')||body.id!==undefined&&!/^[a-f0-9-]{36}$/.test(body.id))throw Error('invalid_cancel_request');if(body.id&&service.active&&body.id!==service.active.row.id)throw Error('cancel_run_conflict');service.cancel();return send({status:service.active?'cancelling':'idle'});}
        return send({error:'route_not_found'},404);
      }catch(error){if(!res.headersSent)send({error:error.message},/busy|conflict|paused|present|budget|owns_team/.test(error.message)?409:400);else res.end();}
    });
  }};
}
async function readBody(req){const timer=setTimeout(()=>req.destroy(),15000);let size=0;const chunks=[];try{for await(const b of req){size+=b.length;if(size>65536)throw Error('request_too_large');chunks.push(b);}return JSON.parse(Buffer.concat(chunks).toString('utf8'));}finally{clearTimeout(timer);}}
function legacyRead(url,res){res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');const directory=path.resolve('.artifacts/research-team');
  try{const match=/^\/api\/local-research\/runs\/([a-f0-9-]{36})(?:\/summary)?$/.exec(url.pathname);if(match){const file=path.join(directory,match[1]+'.json');if(!fs.existsSync(file))throw Error('run_not_found');res.end(fs.readFileSync(file));return;}
    if(url.pathname==='/api/local-research/runs'){res.end(JSON.stringify({runs:fs.existsSync(directory)?fs.readdirSync(directory).filter(x=>/^[a-f0-9-]{36}\.json$/.test(x)).slice(-50).map(x=>({runId:x.slice(0,-5),legacy:true})):[]}));return;}
    res.statusCode=410;res.end(JSON.stringify({error:'legacy_execution_retired',historyAvailable:true}));
  }catch(error){res.statusCode=404;res.end(JSON.stringify({error:error.message}));}
}
