/* A read facade over existing records; no migration, overwrite or remote writes. */
const ResearchRecords = (() => {
  const kinds=['daily_event','sentiment_analysis'];
  const labels={daily_event:'事件',sentiment_analysis:'叙事',session:'研究任务与旧窗口',team:'团队研究轮'};
  const esc=UserWorkspace.esc;
  const IMPORT_KEY='bitdesk-agent-imports-v1',MAX_IMPORT_BYTES=16*1024*1024,MAX_BUNDLE_BYTES=12*1024*1024,MAX_STORED_BYTES=4*1024*1024,MAX_IMPORTS=8,PAGE_SIZE=50;
  const imports=new Map();
  const byteSize=value=>new TextEncoder().encode(typeof value==='string'?value:JSON.stringify(value)).length;
  const finiteDate=value=>typeof value==='string'&&Number.isFinite(Date.parse(value));
  function scopeLabel(row){
    const observation=row.observation||row.task?.observation,mode=row.taskMode||row.task?.taskMode;
    if(observation){
      const market=[observation.exchange==='binance'?'Binance':observation.exchange,observation.symbol,observation.product==='perpetual'?'永续':observation.product==='spot'?'现货':null].filter(Boolean).join(' '),period=observation.timeframe||observation.interval;
      const ranged=Number.isSafeInteger(observation.from)&&Number.isSafeInteger(observation.to)&&observation.from<=observation.to&&Number.isFinite(new Date(observation.from).valueOf())&&Number.isFinite(new Date(observation.to).valueOf());
      const clock=value=>new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',...(value%1000?{fractionalSecondDigits:3}:{})});
      return (market||'市场身份未随索引提供')+(period?' · '+period:' · 周期未随索引提供')+' · '+(ranged?'观察窗 '+clock(observation.from)+' — '+clock(observation.to)+' 北京时间，起止均包含':'观察窗未随索引提供，请核对原件');
    }
    if(mode==='current')return '当前市场 · 各源原生范围，无统一观察窗';
    if(mode==='narrative'&&(row.observation===null||row.task?.observation===null))return '事件问题 · 未限定统一市场窗口，市场身份见原件';
    return '市场身份与观察范围未随索引提供，请核对原件';
  }
  function recordMeta(row){const states={complete:'已完成',limited:'覆盖有限',insufficient:'材料不足',failed:'本轮未完成',cancelled:'已取消',interrupted:'服务中断',checked:'已核对无变化',running:'研究中',skipped_busy:'忙时跳过',cleanup_uncertain:'清理待确认',storage_failed:'保存失败'},parentStates={complete:'所属轮已完成',limited:'所属轮覆盖有限',insufficient:'所属轮材料不足',failed:'所属轮未完成',cancelled:'所属轮已取消',interrupted:'所属轮服务中断',checked:'所属轮已核对无变化',running:'所属轮研究中',cleanup_uncertain:'所属轮清理待确认',storage_failed:'所属轮保存失败'};return scopeLabel(row)+' · '+(row.cutoff?'资料截至 '+ResearchDesk.time(row.cutoff):'资料截止未随索引提供，请核对原件')+' · '+(row.acceptedReport?'报告已接受 · '+(parentStates[row.status]||'所属轮状态见原件'):states[row.status]||row.notice||'覆盖与报告格式请核对原件');}
  function localReports(failures=[]){
    return kinds.flatMap(kind=>{try{const saved=JSON.parse(localStorage.getItem('bitdesk-local-reports-'+kind)||'[]');if(!Array.isArray(saved))throw Error('invalid_index');let damaged=0;const rows=saved.flatMap(x=>{if(x?.row?.kind!==kind||ResearchProtocol.validate(x.row).length||x.id!=='local:'+BitContentIdentity.contentId(x.row)){damaged++;return [];}return [{key:'local-report:'+kind+':'+x.id,id:x.id,kind,title:x.row.report.title,date:x.row.generatedAt,cutoff:x.row.report.asOf,notice:'人工报告 · 覆盖限制见原件',source:'本机',href:'#/'+(kind==='daily_event'?'news':'news-analysis')+'?source=local&reportId='+encodeURIComponent(x.id)}];});if(damaged)failures.push('本机'+labels[kind]+'有 '+damaged+' 条损坏或身份不符，未展示');return rows;}catch{failures.push('本机'+labels[kind]+'索引损坏或无法读取，原存储未改动');return [];}});
  }
  async function localSessions(failures=[]){
    const {restoreSession}=await import('../research-v2/index.mjs');
    let stored=[];try{stored=JSON.parse(localStorage.getItem('bitdesk-research-sessions-v2')||'[]');if(!Array.isArray(stored))throw Error('invalid_index');}catch{stored=[];failures.push('本机窗口研究索引损坏或无法读取，原存储未改动');}
    const live=UserWorkspace.getReaderSession();
    let damaged=0;const rows=stored.flatMap(row=>{try{return [restoreSession(row)];}catch{damaged++;return [];}});if(damaged)failures.push('本机窗口研究有 '+damaged+' 条损坏，未展示');
    if(live&&!rows.some(row=>row.runId===live.runId))rows.unshift(live);
    return rows.map(row=>({key:'local-session:'+row.runId,id:row.runId,kind:'session',title:row.snapshot.question,date:row.completedAt||row.createdAt,cutoff:row.snapshot.bundle?.knowledgeCutoff||row.snapshot.asOf,notice:'旧窗口原件 · 各源范围见原件',source:'本机 · 旧窗口研究',href:'#/research?view=window&source=local&runId='+encodeURIComponent(row.runId)}));
  }
  async function validateImport(value){
    const fail=message=>{throw Error(message);};
    if(!value||typeof value!=='object'||Array.isArray(value)||byteSize(value)>MAX_BUNDLE_BYTES)fail('完整任务内容超过12MiB或不是有效对象。');
    const {contentHash,...body}=value;
    if(!/^sha256:[a-f0-9]{64}$/.test(contentHash||'')||BitContentIdentity.contentId(body)!==contentHash)fail('任务包内容哈希不一致，未导入。');
    const contract=await import('../agent-team/contract.mjs'),row=value.run?.row,task=row?.task;
    if(value.source!=='local-agent-team'||!/^bitdesk\.agent-team\.\d{4}-\d{2}-\d{2}\.\d+$/.test(value.version||'')||!row||!/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/.test(row.id||'')||task?.schemaVersion!==contract.TASK_VERSION||!['current','window','narrative'].includes(task.taskMode)||!finiteDate(task.dataCutoff)||!finiteDate(row.asOf))fail('不支持的完整任务包协议或资料时间，未导入。');
    if(task.contextId!==(task.taskMode==='current'?'current':'task:'+row.id)||task.dataCutoff!==row.asOf||typeof row.requestHash!=='string'||!row.requestHash||row.requestHash!==task.requestHash)fail('任务上下文、请求摘要或资料截止与研究身份不一致，未导入。');
    try{const normalized=contract.normalizeTaskRequest({requestId:row.requestId,question:row.question||'',taskMode:task.taskMode,observation:task.observation,materialRefs:task.materialRefs||[],providedMaterials:task.providedMaterials||[],clientObservedAt:task.clientObservedAt??undefined});if(BitContentIdentity.contentId(normalized)!==row.requestHash)fail('请求摘要与封存问题或范围不一致，未导入。');}catch(error){fail(error.message==='请求摘要与封存问题或范围不一致，未导入。'?error.message:'任务材料、范围或请求身份不符合协议，未导入。');}
    if(task.taskMode==='window'&&!task.observation||task.observation&&(task.observation.exchange!=='binance'||task.observation.symbol!=='BTCUSDT'||!Number.isSafeInteger(task.observation.from)||!Number.isSafeInteger(task.observation.to)||task.observation.from>task.observation.to||task.observation.to-task.observation.from>2160*3600000||!contract.TASK_CAPABILITIES.views.includes(task.observation.view)||!contract.TASK_CAPABILITIES.products.includes(task.observation.product)||!contract.TASK_CAPABILITIES.timeframes.includes(task.observation.timeframe)||task.observation.view==='orderflow'&&!contract.TASK_CAPABILITIES.orderflowTimeframes.includes(task.observation.timeframe)))fail('任务观察范围或周期不合法，未导入。');
    if(!Array.isArray(value.run.receipts)||!value.reports||typeof value.reports!=='object'||Array.isArray(value.reports)||!row.accepted||typeof row.accepted!=='object'||Array.isArray(row.accepted))fail('任务包缺少原始依据或岗位索引，未导入。');
    const receiptIds=new Set(),receiptVersions=new Map();for(const receipt of value.run.receipts){const prior=receiptVersions.get(receipt?.id);if(!receipt||typeof receipt.id!=='string'||prior&&(prior.contentHash!==receipt.contentHash||prior.rawHash!==receipt.rawHash||prior.asOf!==receipt.asOf)||receipt.contextId&&receipt.contextId!==task.contextId&&!receipt.historicalBaseline)fail('依据身份冲突或上下文不一致，未导入。');receiptIds.add(receipt.id);receiptVersions.set(receipt.id,receipt);}
    for(const [role,id]of Object.entries(row.accepted)){if(!['chief',...Object.keys(contract.ROLES)].includes(role)||value.reports[id]?.role!==role)fail('任务包缺少已接受岗位的原报告，未导入。');}
    if(row.commits!==undefined&&!Array.isArray(row.commits))fail('任务封存版本索引损坏，未导入。');const commits=row.commits||Object.entries(row.accepted).map(([role,id])=>({role,id})),lastCommits={},commitIds=new Set();
    for(const commit of commits){if(!commit||commitIds.has(commit.id)||!value.reports[commit.id]||value.reports[commit.id].role!==commit.role)fail('任务包缺少封存版本或身份重复，未导入。');commitIds.add(commit.id);lastCommits[commit.role]=commit.id;}
    if(Object.keys(lastCommits).some(role=>row.accepted[role]!==lastCommits[role])||Object.keys(row.accepted).some(role=>lastCommits[role]!==row.accepted[role]))fail('最后封存版本与已接受岗位指针不一致，未导入。');
    for(const [id,record]of Object.entries(value.reports)){if(!commitIds.has(id)||record?.id!==id||record.cycleId!==row.id||record.task?.contextId!==task.contextId||BitContentIdentity.contentId(record.task)!==BitContentIdentity.contentId(task)||record.asOf!==row.asOf||!finiteDate(record.generatedAt)||!['chief',...Object.keys(contract.ROLES)].includes(record.role))fail('报告身份、版本或上下文与任务不一致，未导入。');try{contract.validateReport(record.report,value.run.receipts,record.role==='chief'?contract.CHIEF_SCHEMA:contract.REPORT_SCHEMA);}catch{fail('报告结构、引用数值或单位不符合封存协议，未导入。');}for(const claim of record.report.claims){if(claim.evidenceIds.some(id=>!receiptIds.has(id)))fail('报告引用的原始依据缺失，未导入。');}}
    for(const [role,record]of Object.entries(value.run.baselines||{})){if(record&&(record.role!==role||typeof record.id!=='string'||!record.report||!finiteDate(record.asOf)||record.task&&record.task.contextId!==task.contextId||value.reports[record.id]&&BitContentIdentity.contentId(value.reports[record.id])!==BitContentIdentity.contentId(record)))fail('封存基线报告身份不一致，未导入。');if(record)try{const schema=structuredClone(role==='chief'?contract.CHIEF_SCHEMA:contract.REPORT_SCHEMA);if(/^bitdesk\.agent-team\.2026-10-02\.1\.prompts\.[23]$/.test(record.promptVersion||''))schema.properties.claims.items.required=schema.properties.claims.items.required.filter(key=>!['scope','baselineReportIds'].includes(key));contract.validateSchema(record.report,schema);}catch{fail('封存历史基线结构损坏或格式未支持，未导入；历史依据缺件保持未知。');}}
    if(!value.run.roles||typeof value.run.roles!=='object'||Array.isArray(value.run.roles))fail('任务岗位结果索引缺失，未导入。');for(const [role,result]of Object.entries(value.run.roles)){if(!['chief',...Object.keys(contract.ROLES)].includes(role)||!result||result.status==='accepted'&&(result.id!==row.accepted[role]||!value.reports[result.id]||result.report&&BitContentIdentity.contentId(result.report)!==BitContentIdentity.contentId(value.reports[result.id].report))||result.status==='unchanged'&&(!value.run.baselines?.[role]||result.id!==value.run.baselines[role].id||result.report&&BitContentIdentity.contentId(result.report)!==BitContentIdentity.contentId(value.run.baselines[role].report)))fail('岗位状态与已接受版本或封存基线不一致，未导入。');}
    return value;
  }
  async function importedRows(failures=[]){
    try{const saved=JSON.parse(localStorage.getItem(IMPORT_KEY)||'[]');if(!Array.isArray(saved)||saved.length>MAX_IMPORTS||byteSize(saved)>MAX_STORED_BYTES)throw Error('invalid_import_index');let damaged=0;for(const item of saved){try{await validateImport(item.bundle);if(!imports.has(item.bundle.contentHash))imports.set(item.bundle.contentHash,{...item,persisted:true});}catch{damaged++;}}if(damaged)failures.push('本机导入任务有 '+damaged+' 条损坏或身份不符，未展示');}catch{failures.push('本机导入任务索引损坏或无法读取，原存储未改动');}
    return [...imports.values()].map(({bundle,persisted})=>({key:'import-task:'+bundle.contentHash,id:bundle.run.row.id,kind:'session',dateLabel:bundle.run.row.terminal==='interrupted'?'中断确认':undefined,title:bundle.run.row.question||'导入任务',date:bundle.run.row.endedAt||null,cutoff:bundle.run.row.task.dataCutoff,task:bundle.run.row.task,status:bundle.run.row.terminal,source:'导入 · '+({current:'当前市场',window:'窗口问题',narrative:'事件问题'}[bundle.run.row.task.taskMode])+' · 来源未认证 · '+(persisted?'本机保存':'仅本次会话'),href:'#/team-record?source=import&importId='+encodeURIComponent(bundle.contentHash)}));
  }
  async function importBundle(value){
    await validateImport(value);await importedRows();if(!imports.has(value.contentHash)&&imports.size>=MAX_IMPORTS)throw Error('最多保留8个导入任务；未替换已有原件，请保留导出文件。');
    const item={bundle:value,importedAt:new Date().toISOString(),persisted:false};imports.set(value.contentHash,item);
    try{const saved=JSON.parse(localStorage.getItem(IMPORT_KEY)||'[]');if(!Array.isArray(saved))throw Error('invalid_index');const next=[{bundle:value,importedAt:item.importedAt},...saved.filter(x=>x.bundle?.contentHash!==value.contentHash)];if(next.length>MAX_IMPORTS||byteSize(next)>MAX_STORED_BYTES)throw Error('capacity');localStorage.setItem(IMPORT_KEY,JSON.stringify(next));item.persisted=true;return '已导入并保存在本机；来源未认证，哈希只证明内容一致。';}catch{return '已在本次会话打开；本机持久总额4MiB或浏览器容量不足，未长期保存，请保留导出文件。';}
  }
  function teamRows(runs){const tasks={current:'当前市场',window:'窗口专题',narrative:'事件专题'};return runs.map(cycle=>{const mode=cycle.task?.taskMode||cycle.taskMode||'current';return {key:'team-task:'+cycle.id,id:cycle.id,kind:'team',dateLabel:cycle.endedAt?'完成/保存':'完成时间未知',title:cycle.readingTitle||(mode==='current'&&!cycle.accepted?.chief?'市场更新 · 首席尚未完成':cycle.question||tasks[mode]),date:cycle.endedAt||null,cutoff:cycle.asOf,task:cycle.task,taskMode:mode,observation:cycle.observation,status:cycle.status||cycle.terminal,accepted:cycle.accepted,hasChief:!!cycle.accepted?.chief,source:'研究服务 · '+(tasks[mode]||'研究任务'),href:'#/records?selected='+encodeURIComponent(cycle.id)};});}
  async function readTeamPage(offset=0,{signal,query}={}){const params=new URLSearchParams({offset,limit:PAGE_SIZE});if(query){params.set('query','1');for(const [key,value]of Object.entries(query))if(value!==null&&value!==undefined)params.set(key,value);}const response=await fetch('/api/local-agent-team/runs?'+params,{signal:signal?AbortSignal.any([signal,AbortSignal.timeout(12000)]):AbortSignal.timeout(12000)});const data=await response.json();if(!response.ok||data.error)throw Error(data.error==='history_query_expired'?'查询快照已过期，请刷新后重新查询。':data.error==='invalid_history_query'?'查询条件无效，请核对日期与类型。':'本地研究索引读取失败；不能判断是否无匹配。');if(!Array.isArray(data.runs)||data.runs.length>PAGE_SIZE||data.offset!==offset||!Number.isSafeInteger(data.total)||data.total<0||data.nextOffset!==null&&(!Number.isSafeInteger(data.nextOffset)||data.nextOffset!==offset+data.runs.length||!data.runs.length)||new Set(data.runs.map(row=>row?.id)).size!==data.runs.length||data.runs.some(row=>!row||typeof row.id!=='string'||!row.id||!row.accepted||typeof row.accepted!=='object'||Array.isArray(row.accepted))||query&&(!data.snapshot||data.coverage?.complete!==true))throw Error('本地研究索引分页响应缺件或身份重复，查询覆盖未确认。');return {...data,rows:teamRows(data.runs),count:data.runs.length,pageSize:PAGE_SIZE};}
  async function read({signal,includeTeam=true,source='all'}={}){
    const failures=[],rows=[...(['all','local'].includes(source)?[...localReports(failures),...await localSessions(failures)]:[]),...(['all','import'].includes(source)?await importedRows(failures):[])];let teamPage=null;
    if(['all','cloud'].includes(source))await Promise.all(kinds.map(async kind=>{try{const result=await DataEngine.fetchYuqingReportHistory(kind,365,{signal});for(const item of result?.items||[])rows.push({key:'cloud-report:'+kind+':'+item.id,id:item.id,kind,title:item.title||'未命名报告',date:item.generatedAt,cutoff:item.asOf,observation:item.observation,notice:'覆盖与旧格式资格见原件',source:'云端',href:'#/'+(kind==='daily_event'?'news':'news-analysis')+'?source=cloud&reportId='+encodeURIComponent(item.id)});}catch(error){if(!signal?.aborted)failures.push(labels[kind]+'历史暂时无法读取');}}));
    // The local research bridge exists only on the user's host. Never replace remote history with it.
    if(['localhost','127.0.0.1'].includes(location.hostname)){
      if(['all','local'].includes(source))try{const response=await fetch('/api/local-research/runs',{signal:signal?AbortSignal.any([signal,AbortSignal.timeout(4000)]):AbortSignal.timeout(4000)});if(!response.ok)throw Error('历史读取失败（'+response.status+'）');const data=await response.json();if(data.error||!Array.isArray(data.runs))throw Error('历史响应不完整');for(const item of data.runs)rows.push({key:'host-session:'+item.runId,id:item.runId,kind:'session',title:item.question||'旧窗口研究',date:item.completedAt||item.createdAt,cutoff:item.asOf,observation:item.observation,notice:'旧窗口原件 · 覆盖限制见原件',source:'旧研究服务 · 旧窗口研究',href:'#/research?view=window&source=host&runId='+encodeURIComponent(item.runId)});}catch(error){if(!signal?.aborted)failures.push('旧研究服务历史暂时无法读取：'+error.message);}
      if(includeTeam)try{teamPage=await readTeamPage(0,{signal});rows.push(...teamPage.rows);}catch(error){if(!signal?.aborted)failures.push(error.message);}
    }
    return {rows:sortRows(rows),failures,teamPage};
  }
  function sortRows(rows){return [...new Map(rows.map(row=>[row.key,row])).values()].sort((a,b)=>(Date.parse(b.date)||0)-(Date.parse(a.date)||0));}
  function renderRows(rows){return rows.map(row=>`<a class="user-record-row" href="${esc(row.href)}" data-record-key="${esc(row.key)}"><strong title="${esc(row.title)}">${esc(row.title.length>64?row.title.slice(0,64)+'…':row.title)}</strong><span>${labels[row.kind]} · ${esc(row.dateLabel||'完成/保存')} ${esc(ResearchDesk.time(row.date))} · ${esc(row.source)}</span><span class="user-record-scope">${esc(recordMeta(row))}</span></a>`).join('')||ResearchDesk.empty('没有匹配记录','调整筛选，或打开其他已保存记录。');}
  return {scopeLabel,read,readTeamPage,renderRows,sortRows,localReports,localSessions,importBundle,validateImport,importedRows,getImport:id=>imports.get(id)?.bundle,MAX_IMPORT_BYTES};
})();
let researchRecordsCleanup=null;
let researchLibraryGeneration=0;
function pageResearchRecords(){return '<div id="research-library">正在读取研究目录…</div>';}
function initResearchRecords(){const generation=++researchLibraryGeneration;void import('../research-library.mjs').then(async module=>{if(generation!==researchLibraryGeneration)return;const cleanup=await module.mountLibrary(document.getElementById('research-library'),ResearchRecords);if(generation!==researchLibraryGeneration)cleanup?.();else researchRecordsCleanup=cleanup;}).catch(error=>{const root=document.getElementById('research-library');if(root)root.textContent='研究目录读取失败：'+error.message;});}
function disposeResearchRecords(){++researchLibraryGeneration;researchRecordsCleanup?.();researchRecordsCleanup=null;}

let teamRecordCleanup=null,teamRecordGeneration=0;
function pageTeamRecord(){return '<div id="saved-record">正在读取指定原件…</div>';}
function initTeamRecord(){const generation=++teamRecordGeneration;void import('../research-library.mjs').then(module=>{if(generation!==teamRecordGeneration)return;teamRecordCleanup=module.mountSavedRecord(document.getElementById('saved-record'),ResearchRecords);}).catch(error=>{const root=document.getElementById('saved-record');if(root)root.textContent='指定原件读取失败：'+error.message;});}
function disposeTeamRecord(){++teamRecordGeneration;teamRecordCleanup?.();teamRecordCleanup=null;}
