/* A read facade over existing records; no migration, overwrite or remote writes. */
const ResearchRecords = (() => {
  const kinds=['daily_event','sentiment_analysis'];
  const labels={daily_event:'事件',sentiment_analysis:'叙事',session:'研究任务与旧窗口',team:'岗位研究'};
  const esc=UserWorkspace.esc;
  const IMPORT_KEY='bitdesk-agent-imports-v1',MAX_IMPORT_BYTES=16*1024*1024,MAX_BUNDLE_BYTES=12*1024*1024,MAX_STORED_BYTES=4*1024*1024,MAX_IMPORTS=8,PAGE_SIZE=50;
  const imports=new Map();
  const byteSize=value=>new TextEncoder().encode(typeof value==='string'?value:JSON.stringify(value)).length;
  const finiteDate=value=>typeof value==='string'&&Number.isFinite(Date.parse(value));
  function scopeLabel(row){
    const observation=row.observation||row.task?.observation,mode=row.taskMode||row.task?.taskMode;
    if(observation){
      const market=[observation.exchange==='binance'?'Binance':observation.exchange,observation.symbol,observation.product==='perpetual'?'永续':observation.product==='spot'?'现货':null].filter(Boolean).join(' '),period=observation.timeframe||observation.interval;
      const ranged=Number.isSafeInteger(observation.from)&&Number.isSafeInteger(observation.to)&&observation.from<=observation.to&&Number.isFinite(new Date(observation.from).valueOf())&&Number.isFinite(new Date(observation.to).valueOf());
      const clock=value=>new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',...(value%1000?{fractionalSecondDigits:3}:{})});
      return (market||'市场身份未随索引提供')+(period?' · '+period:' · 周期未随索引提供')+' · '+(ranged?'观察窗 '+clock(observation.from)+' — '+clock(observation.to)+' 北京时间，起止均包含':'观察窗未随索引提供，请核对原件');
    }
    if(mode==='current')return '当前市场 · 各源原生范围，无统一观察窗';
    if(mode==='narrative'&&(row.observation===null||row.task?.observation===null))return '事件问题 · 未限定统一市场窗口，市场身份见原件';
    return '市场身份与观察范围未随索引提供，请核对原件';
  }
  function recordMeta(row){const states={complete:'已完成',limited:'覆盖有限',insufficient:'材料不足',failed:'本轮未完成',cancelled:'已取消',interrupted:'服务中断',checked:'已核对无变化',running:'研究中',skipped_busy:'忙时跳过',cleanup_uncertain:'清理待确认',storage_failed:'保存失败'},parentStates={complete:'所属轮已完成',limited:'所属轮覆盖有限',insufficient:'所属轮材料不足',failed:'所属轮未完成',cancelled:'所属轮已取消',interrupted:'所属轮服务中断',checked:'所属轮已核对无变化',running:'所属轮研究中',cleanup_uncertain:'所属轮清理待确认',storage_failed:'所属轮保存失败'};return scopeLabel(row)+' · '+(row.cutoff?'资料截至 '+ResearchDesk.time(row.cutoff):'资料截止未随索引提供，请核对原件')+' · '+(row.acceptedReport?'报告已接受 · '+(parentStates[row.status]||'所属轮状态见原件'):states[row.status]||row.notice||'覆盖与报告格式请核对原件');}
  function localReports(failures=[]){
    return kinds.flatMap(kind=>{try{const saved=JSON.parse(localStorage.getItem('bitdesk-local-reports-'+kind)||'[]');if(!Array.isArray(saved))throw Error('invalid_index');let damaged=0;const rows=saved.flatMap(x=>{if(x?.row?.kind!==kind||ResearchProtocol.validate(x.row).length||x.id!=='local:'+BitContentIdentity.contentId(x.row)){damaged++;return [];}return [{key:'local-report:'+kind+':'+x.id,id:x.id,kind,title:x.row.report.title,date:x.row.generatedAt,cutoff:x.row.report.asOf,notice:'人工报告 · 覆盖限制见原件',source:'本机',href:'#/'+(kind==='daily_event'?'news':'news-analysis')+'?source=local&reportId='+encodeURIComponent(x.id)}];});if(damaged)failures.push('本机'+labels[kind]+'有 '+damaged+' 条损坏或身份不符，未展示');return rows;}catch{failures.push('本机'+labels[kind]+'索引损坏或无法读取，原存储未改动');return [];}});
  }
  async function localSessions(failures=[]){
    const {restoreSession}=await import('../research-v2/index.mjs');
    let stored=[];try{stored=JSON.parse(localStorage.getItem('bitdesk-research-sessions-v2')||'[]');if(!Array.isArray(stored))throw Error('invalid_index');}catch{stored=[];failures.push('本机窗口研究索引损坏或无法读取，原存储未改动');}
    const live=UserWorkspace.getReaderSession();
    let damaged=0;const rows=stored.flatMap(row=>{try{return [restoreSession(row)];}catch{damaged++;return [];}});if(damaged)failures.push('本机窗口研究有 '+damaged+' 条损坏，未展示');
    if(live&&!rows.some(row=>row.runId===live.runId))rows.unshift(live);
    return rows.map(row=>({key:'local-session:'+row.runId,id:row.runId,kind:'session',title:row.snapshot.question,date:row.completedAt||row.createdAt,cutoff:row.snapshot.bundle?.knowledgeCutoff||row.snapshot.asOf,notice:'旧窗口原件 · 各源范围见原件',source:'本机 · 旧窗口研究',href:'#/research?view=window&source=local&runId='+encodeURIComponent(row.runId)}));
  }
  async function validateImport(value){
    const fail=message=>{throw Error(message);};
    if(!value||typeof value!=='object'||Array.isArray(value)||byteSize(value)>MAX_BUNDLE_BYTES)fail('完整任务内容超过12MiB或不是有效对象。');
    const {contentHash,...body}=value;
    if(!/^sha256:[a-f0-9]{64}$/.test(contentHash||'')||BitContentIdentity.contentId(body)!==contentHash)fail('任务包内容哈希不一致，未导入。');
    const contract=await import('../agent-team/contract.mjs'),row=value.run?.row,task=row?.task;
    if(value.source!=='local-agent-team'||!/^bitdesk\.agent-team\.\d{4}-\d{2}-\d{2}\.\d+$/.test(value.version||'')||!row||!/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/.test(row.id||'')||task?.schemaVersion!==contract.TASK_VERSION||!['current','window','narrative'].includes(task.taskMode)||!finiteDate(task.dataCutoff)||!finiteDate(row.asOf))fail('不支持的完整任务包协议或资料时间，未导入。');
    if(task.contextId!==(task.taskMode==='current'?'current':'task:'+row.id)||task.dataCutoff!==row.asOf||typeof row.requestHash!=='string'||!row.requestHash||row.requestHash!==task.requestHash)fail('任务上下文、请求摘要或资料截止与研究身份不一致，未导入。');
    try{const normalized=contract.normalizeTaskRequest({requestId:row.requestId,question:row.question||'',taskMode:task.taskMode,observation:task.observation,materialRefs:task.materialRefs||[],providedMaterials:task.providedMaterials||[],clientObservedAt:task.clientObservedAt??undefined});if(BitContentIdentity.contentId(normalized)!==row.requestHash)fail('请求摘要与封存问题或范围不一致，未导入。');}catch(error){fail(error.message==='请求摘要与封存问题或范围不一致，未导入。'?error.message:'任务材料、范围或请求身份不符合协议，未导入。');}
    if(task.taskMode==='window'&&!task.observation||task.observation&&(task.observation.exchange!=='binance'||task.observation.symbol!=='BTCUSDT'||!Number.isSafeInteger(task.observation.from)||!Number.isSafeInteger(task.observation.to)||task.observation.from>task.observation.to||task.observation.to-task.observation.from>2160*3600000||!contract.TASK_CAPABILITIES.views.includes(task.observation.view)||!contract.TASK_CAPABILITIES.products.includes(task.observation.product)||!contract.TASK_CAPABILITIES.timeframes.includes(task.observation.timeframe)||task.observation.view==='orderflow'&&!contract.TASK_CAPABILITIES.orderflowTimeframes.includes(task.observation.timeframe)))fail('任务观察范围或周期不合法，未导入。');
    if(!Array.isArray(value.run.receipts)||!value.reports||typeof value.reports!=='object'||Array.isArray(value.reports)||!row.accepted||typeof row.accepted!=='object'||Array.isArray(row.accepted))fail('任务包缺少原始依据或岗位索引，未导入。');
    const receiptIds=new Set(),receiptVersions=new Map();for(const receipt of value.run.receipts){const prior=receiptVersions.get(receipt?.id);if(!receipt||typeof receipt.id!=='string'||prior&&(prior.contentHash!==receipt.contentHash||prior.rawHash!==receipt.rawHash||prior.asOf!==receipt.asOf)||receipt.contextId&&receipt.contextId!==task.contextId&&!receipt.historicalBaseline)fail('依据身份冲突或上下文不一致，未导入。');receiptIds.add(receipt.id);receiptVersions.set(receipt.id,receipt);}
    for(const [role,id]of Object.entries(row.accepted)){if(!['chief',...Object.keys(contract.ROLES)].includes(role)||value.reports[id]?.role!==role)fail('任务包缺少已接受岗位的原报告，未导入。');}
    if(row.commits!==undefined&&!Array.isArray(row.commits))fail('任务封存版本索引损坏，未导入。');const commits=row.commits||Object.entries(row.accepted).map(([role,id])=>({role,id})),lastCommits={},commitIds=new Set();
    for(const commit of commits){if(!commit||commitIds.has(commit.id)||!value.reports[commit.id]||value.reports[commit.id].role!==commit.role)fail('任务包缺少封存版本或身份重复，未导入。');commitIds.add(commit.id);lastCommits[commit.role]=commit.id;}
    if(Object.keys(lastCommits).some(role=>row.accepted[role]!==lastCommits[role])||Object.keys(row.accepted).some(role=>lastCommits[role]!==row.accepted[role]))fail('最后封存版本与已接受岗位指针不一致，未导入。');
    for(const [id,record]of Object.entries(value.reports)){if(!commitIds.has(id)||record?.id!==id||record.cycleId!==row.id||record.task?.contextId!==task.contextId||BitContentIdentity.contentId(record.task)!==BitContentIdentity.contentId(task)||record.asOf!==row.asOf||!finiteDate(record.generatedAt)||!['chief',...Object.keys(contract.ROLES)].includes(record.role))fail('报告身份、版本或上下文与任务不一致，未导入。');try{contract.validateReport(record.report,value.run.receipts,record.role==='chief'?contract.CHIEF_SCHEMA:contract.REPORT_SCHEMA);}catch{fail('报告结构、引用数值或单位不符合封存协议，未导入。');}for(const claim of record.report.claims){if(claim.evidenceIds.some(id=>!receiptIds.has(id)))fail('报告引用的原始依据缺失，未导入。');}}
    for(const [role,record]of Object.entries(value.run.baselines||{})){if(record&&(record.role!==role||typeof record.id!=='string'||!record.report||!finiteDate(record.asOf)||record.task&&record.task.contextId!==task.contextId||value.reports[record.id]&&BitContentIdentity.contentId(value.reports[record.id])!==BitContentIdentity.contentId(record)))fail('封存基线报告身份不一致，未导入。');if(record)try{const schema=structuredClone(role==='chief'?contract.CHIEF_SCHEMA:contract.REPORT_SCHEMA);if(/^bitdesk\.agent-team\.2026-10-02\.1\.prompts\.[23]$/.test(record.promptVersion||''))schema.properties.claims.items.required=schema.properties.claims.items.required.filter(key=>!['scope','baselineReportIds'].includes(key));contract.validateSchema(record.report,schema);}catch{fail('封存历史基线结构损坏或格式未支持，未导入；历史依据缺件保持未知。');}}
    if(!value.run.roles||typeof value.run.roles!=='object'||Array.isArray(value.run.roles))fail('任务岗位结果索引缺失，未导入。');for(const [role,result]of Object.entries(value.run.roles)){if(!['chief',...Object.keys(contract.ROLES)].includes(role)||!result||result.status==='accepted'&&(result.id!==row.accepted[role]||!value.reports[result.id]||result.report&&BitContentIdentity.contentId(result.report)!==BitContentIdentity.contentId(value.reports[result.id].report))||result.status==='unchanged'&&(!value.run.baselines?.[role]||result.id!==value.run.baselines[role].id||result.report&&BitContentIdentity.contentId(result.report)!==BitContentIdentity.contentId(value.run.baselines[role].report)))fail('岗位状态与已接受版本或封存基线不一致，未导入。');}
    return value;
  }
  async function importedRows(failures=[]){
    try{const saved=JSON.parse(localStorage.getItem(IMPORT_KEY)||'[]');if(!Array.isArray(saved)||saved.length>MAX_IMPORTS||byteSize(saved)>MAX_STORED_BYTES)throw Error('invalid_import_index');let damaged=0;for(const item of saved){try{await validateImport(item.bundle);if(!imports.has(item.bundle.contentHash))imports.set(item.bundle.contentHash,{...item,persisted:true});}catch{damaged++;}}if(damaged)failures.push('本机导入任务有 '+damaged+' 条损坏或身份不符，未展示');}catch{failures.push('本机导入任务索引损坏或无法读取，原存储未改动');}
    return [...imports.values()].map(({bundle,persisted})=>({key:'import-task:'+bundle.contentHash,id:bundle.run.row.id,kind:'session',dateLabel:bundle.run.row.terminal==='interrupted'?'中断确认':undefined,title:bundle.run.row.question||'导入任务',date:bundle.run.row.endedAt||bundle.run.row.startedAt||bundle.run.row.asOf,cutoff:bundle.run.row.task.dataCutoff,task:bundle.run.row.task,status:bundle.run.row.terminal,source:'导入 · '+({current:'当前市场',window:'窗口问题',narrative:'事件问题'}[bundle.run.row.task.taskMode])+' · 来源未认证 · '+(persisted?'本机保存':'仅本次会话'),href:'#/team-record?source=import&importId='+encodeURIComponent(bundle.contentHash)}));
  }
  async function importBundle(value){
    await validateImport(value);await importedRows();if(!imports.has(value.contentHash)&&imports.size>=MAX_IMPORTS)throw Error('最多保留8个导入任务；未替换已有原件，请保留导出文件。');
    const item={bundle:value,importedAt:new Date().toISOString(),persisted:false};imports.set(value.contentHash,item);
    try{const saved=JSON.parse(localStorage.getItem(IMPORT_KEY)||'[]');if(!Array.isArray(saved))throw Error('invalid_index');const next=[{bundle:value,importedAt:item.importedAt},...saved.filter(x=>x.bundle?.contentHash!==value.contentHash)];if(next.length>MAX_IMPORTS||byteSize(next)>MAX_STORED_BYTES)throw Error('capacity');localStorage.setItem(IMPORT_KEY,JSON.stringify(next));item.persisted=true;return '已导入并保存在本机；来源未认证，哈希只证明内容一致。';}catch{return '已在本次会话打开；本机持久总额4MiB或浏览器容量不足，未长期保存，请保留导出文件。';}
  }
  function teamRows(runs){const names={chief:'首席解读',env:'价格与结构',flow:'盘口流动性',deriv:'衍生品',macro:'宏观',events:'事件与叙事'},tasks={current:'当前市场',window:'窗口问题',narrative:'事件问题'};return runs.flatMap(cycle=>{const mode=cycle.task?.taskMode||cycle.taskMode||'current',rows=[];rows.push({key:'team-task:'+cycle.id,id:cycle.id,kind:'session',dateLabel:(cycle.status||cycle.terminal)==='interrupted'?'中断确认':undefined,title:cycle.question||tasks[mode],date:cycle.endedAt||cycle.asOf,cutoff:cycle.asOf,task:cycle.task,taskMode:mode,observation:cycle.observation,status:cycle.status||cycle.terminal,source:'研究服务 · '+(tasks[mode]||'研究任务'),href:'#/research?view=window&taskId='+encodeURIComponent(cycle.id)});for(const [role,id]of Object.entries(cycle.accepted||{}))rows.push({key:'team-report:'+id,id,kind:'team',acceptedReport:true,dateLabel:(cycle.status||cycle.terminal)==='interrupted'?'所属研究轮中断确认':cycle.endedAt?'所属研究轮完成/保存':'所属研究轮索引时点',title:(names[role]||'岗位研究')+' · '+(tasks[mode]||'当前市场')+' · '+ResearchDesk.time(cycle.asOf),date:cycle.endedAt||cycle.asOf,cutoff:cycle.asOf,task:cycle.task,taskMode:mode,observation:cycle.observation,status:cycle.status||cycle.terminal,source:'研究服务',href:'#/team-record?reportId='+encodeURIComponent(id)});return rows;});}
  async function readTeamPage(offset=0,{signal}={}){const response=await fetch('/api/local-agent-team/runs?offset='+offset+'&limit='+PAGE_SIZE,{signal:signal?AbortSignal.any([signal,AbortSignal.timeout(4000)]):AbortSignal.timeout(4000)});if(!response.ok)throw Error('岗位研究历史读取失败（'+response.status+'）');const data=await response.json();if(data.error||!Array.isArray(data.runs)||data.runs.length>PAGE_SIZE||data.offset!==offset||!Number.isSafeInteger(data.total)||data.total<0||data.nextOffset!==null&&(!Number.isSafeInteger(data.nextOffset)||data.nextOffset!==offset+data.runs.length||!data.runs.length)||new Set(data.runs.map(row=>row?.id)).size!==data.runs.length||data.runs.some(row=>!row||typeof row.id!=='string'||!row.id||!row.accepted||typeof row.accepted!=='object'||Array.isArray(row.accepted)))throw Error('岗位研究历史分页响应缺件或身份重复');return {rows:teamRows(data.runs),total:data.total,nextOffset:data.nextOffset,offset,count:data.runs.length,pageSize:PAGE_SIZE};}
  async function read({signal}={}){
    const failures=[],rows=[...localReports(failures),...await localSessions(failures),...await importedRows(failures)];let teamPage=null;
    await Promise.all(kinds.map(async kind=>{try{const result=await DataEngine.fetchYuqingReportHistory(kind,365,{signal});for(const item of result?.items||[])rows.push({key:'cloud-report:'+kind+':'+item.id,id:item.id,kind,title:item.title||'未命名报告',date:item.generatedAt,cutoff:item.asOf,observation:item.observation,notice:'覆盖与旧格式资格见原件',source:'云端',href:'#/'+(kind==='daily_event'?'news':'news-analysis')+'?source=cloud&reportId='+encodeURIComponent(item.id)});}catch(error){if(!signal?.aborted)failures.push(labels[kind]+'历史暂时无法读取');}}));
    // The local research bridge exists only on the user's host. Never replace remote history with it.
    if(['localhost','127.0.0.1'].includes(location.hostname)){
      try{const response=await fetch('/api/local-research/runs',{signal:signal?AbortSignal.any([signal,AbortSignal.timeout(4000)]):AbortSignal.timeout(4000)});if(!response.ok)throw Error('历史读取失败（'+response.status+'）');const data=await response.json();if(data.error||!Array.isArray(data.runs))throw Error('历史响应不完整');for(const item of data.runs)rows.push({key:'host-session:'+item.runId,id:item.runId,kind:'session',title:item.question||'旧窗口研究',date:item.completedAt||item.createdAt,cutoff:item.asOf,observation:item.observation,notice:'旧窗口原件 · 覆盖限制见原件',source:'旧研究服务 · 旧窗口研究',href:'#/research?view=window&source=host&runId='+encodeURIComponent(item.runId)});}catch(error){if(!signal?.aborted)failures.push('旧研究服务历史暂时无法读取：'+error.message);}
      try{teamPage=await readTeamPage(0,{signal});rows.push(...teamPage.rows);}catch(error){if(!signal?.aborted)failures.push(error.message);}
    }
    return {rows:sortRows(rows),failures,teamPage};
  }
  function sortRows(rows){return [...new Map(rows.map(row=>[row.key,row])).values()].sort((a,b)=>(Date.parse(b.date)||0)-(Date.parse(a.date)||0));}
  function renderRows(rows){return rows.map(row=>`<a class="user-record-row" href="${esc(row.href)}" data-record-key="${esc(row.key)}"><strong title="${esc(row.title)}">${esc(row.title.length>64?row.title.slice(0,64)+'…':row.title)}</strong><span>${labels[row.kind]} · ${esc(row.dateLabel||'完成/保存')} ${esc(ResearchDesk.time(row.date))} · ${esc(row.source)}</span><span class="user-record-scope">${esc(recordMeta(row))}</span></a>`).join('')||ResearchDesk.empty('没有匹配记录','调整筛选，或打开其他已保存记录。');}
  return {read,readTeamPage,renderRows,sortRows,localReports,localSessions,importBundle,validateImport,importedRows,getImport:id=>imports.get(id)?.bundle,MAX_IMPORT_BYTES};
})();
let researchRecordsCleanup=null;
function pageResearchRecords(){return `<header class="rd-page-head"><div><h1>资料与旧记录</h1><p>回看当时的资料、判断和失效条件。</p></div><a class="btn primary" href="#/research">进入首席决策台 →</a></header><section class="rd-panel"><div class="user-record-controls"><label>问题或标题<input id="records-search" type="search" placeholder="检索记录"></label><label>类型<select id="records-kind"><option value="all">全部记录</option><option value="session">研究任务与旧窗口</option><option value="team">岗位研究</option><option value="daily_event">事件</option><option value="sentiment_analysis">叙事</option></select></label><label>起始日期<input type="date" id="records-from"></label><label>结束日期<input type="date" id="records-to"></label><button class="btn" id="records-refresh">刷新</button><button class="btn" id="records-import-open" type="button">导入完整任务原件</button><input id="records-import" type="file" aria-label="完整任务原件" accept="application/json,.json" hidden></div><p class="muted">日期按完成或保存时间（北京时间）筛选，含结束日；日期未知的记录仅在未设日期时显示。搜索、类型与日期仅筛选已加载页和本机资料；云端事件与叙事索引读取近365天。</p><p class="muted">导入文件最多16MiB，完整任务内容最多12MiB。本机持久总额最多4MiB、8个任务；容量不足时仅保留本次会话，请自行保存导出原件。</p><p id="records-feedback" role="status">正在读取记录…</p><p id="records-import-feedback" role="status"></p><div id="records-list"></div><p id="records-page-status" class="muted"></p><div class="at-toolbar"><button class="btn" id="records-latest" hidden>最新一页</button><button class="btn" id="records-previous" hidden>上一页</button><button class="btn" id="records-more" hidden>更早一页</button></div></section>`;}
function initResearchRecords(){
  researchRecordsCleanup?.();const ctrl=new AbortController();let rows=[],serial=0,teamPage=null,failures=[],busy=false;
  const elements=['records-search','records-kind','records-from','records-to'].map(id=>document.getElementById(id));
  const more=document.getElementById('records-more'),previous=document.getElementById('records-previous'),latest=document.getElementById('records-latest'),feedback=document.getElementById('records-feedback');
  function paint(){const [q,kind,from,to]=elements.map(el=>el.value),invalid=from&&to&&from>to;const filtered=invalid?[]:rows.filter(row=>(kind==='all'||kind===row.kind)&&String(row.title).toLowerCase().includes(q.toLowerCase())&&(!from||Date.parse(row.date)>=Date.parse(from+'T00:00:00+08:00'))&&(!to||Date.parse(row.date)<Date.parse(to+'T00:00:00+08:00')+86400000));document.getElementById('records-list').innerHTML=ResearchRecords.renderRows(filtered);feedback.textContent=(invalid?'起始日期晚于结束日期，请调整。':rows.length+' 条本页及本机记录 · 匹配 '+filtered.length+' 条')+(failures.length?' · '+failures.join('；'):'');more.hidden=!teamPage||teamPage.nextOffset===null;previous.hidden=latest.hidden=!teamPage||teamPage.offset===0;for(const button of [more,previous,latest])button.disabled=busy;document.getElementById('records-page-status').textContent=teamPage?'研究服务第 '+(teamPage.count?teamPage.offset+1:0)+'—'+(teamPage.offset+teamPage.count)+' / '+teamPage.total+' 轮；每页最多50轮，仅保留当前页'+(teamPage.nextOffset!==null?'；尚有更早记录。':'；已到最早一页。'):'';}
  async function refresh(){if(busy)return;const ticket=++serial,button=document.getElementById('records-refresh');busy=true;button.disabled=true;more.disabled=true;try{const result=await ResearchRecords.read({signal:ctrl.signal});if(ctrl.signal.aborted||ticket!==serial)return;rows=result.rows;failures=result.failures;teamPage=result.teamPage;paint();}catch(error){if(!ctrl.signal.aborted)feedback.textContent='记录读取失败，请重试。';}finally{if(!ctrl.signal.aborted&&ticket===serial){busy=false;button.disabled=false;more.disabled=false;}}}
  async function loadPage(offset){if(busy||!teamPage||offset===null)return;const ticket=++serial;busy=true;for(const button of [more,previous,latest])button.disabled=true;try{const next=await ResearchRecords.readTeamPage(offset,{signal:ctrl.signal});if(ctrl.signal.aborted||ticket!==serial)return;rows=ResearchRecords.sortRows([...rows.filter(row=>!row.key.startsWith('team-task:')&&!row.key.startsWith('team-report:')),...next.rows]);teamPage=next;paint();}catch(error){if(!ctrl.signal.aborted&&ticket===serial)feedback.textContent='本页读取失败，已读取原记录保留：'+error.message;}finally{if(!ctrl.signal.aborted&&ticket===serial){busy=false;for(const button of [more,previous,latest])button.disabled=false;}}}
  more.addEventListener('click',()=>loadPage(teamPage?.nextOffset),{signal:ctrl.signal});previous.addEventListener('click',()=>loadPage(Math.max(0,teamPage.offset-teamPage.pageSize)),{signal:ctrl.signal});latest.addEventListener('click',()=>loadPage(0),{signal:ctrl.signal});
  document.getElementById('records-import-open').addEventListener('click',()=>document.getElementById('records-import').click(),{signal:ctrl.signal});
  document.getElementById('records-import').addEventListener('change',async event=>{const file=event.target.files?.[0],out=document.getElementById('records-import-feedback');if(!file)return;const ticket=serial;try{if(file.size>ResearchRecords.MAX_IMPORT_BYTES)throw Error('文件超过16MiB，未读取或导入，请保留原文件。');const value=JSON.parse(await file.text());if(ctrl.signal.aborted||ticket!==serial)return;const message=await ResearchRecords.importBundle(value);if(ctrl.signal.aborted||ticket!==serial)return;out.textContent=message;rows=ResearchRecords.sortRows([...rows.filter(row=>!row.key.startsWith('import-task:')),...await ResearchRecords.importedRows()]);paint();}catch(error){if(!ctrl.signal.aborted&&ticket===serial)out.textContent='无法恢复：'+error.message;}finally{event.target.value='';}},{signal:ctrl.signal});
  elements.forEach(el=>el.addEventListener('input',paint,{signal:ctrl.signal}));document.getElementById('records-refresh').addEventListener('click',refresh,{signal:ctrl.signal});researchRecordsCleanup=()=>{ctrl.abort();++serial;};void refresh();
}
function disposeResearchRecords(){researchRecordsCleanup?.();researchRecordsCleanup=null;}

let teamRecordCleanup=null;
function pageTeamRecord(){return `<header class="rd-page-head"><div><h1>${UserWorkspace.query().get('source')==='import'?'导入任务记录':'岗位研究记录'}</h1><p>阅读当时保存的观点与引用依据。</p></div><a class="btn" href="#/records">返回记录 →</a></header><p id="team-record-feedback" role="status">正在读取指定记录…</p><div id="team-record-body"></div><dialog class="rd-dialog" id="team-record-dialog"><button class="btn" id="team-record-close">关闭</button><div id="team-record-evidence"></div></dialog>`;}
function initTeamRecord(){
  teamRecordCleanup?.();const ctrl=new AbortController(),body=document.getElementById('team-record-body'),feedback=document.getElementById('team-record-feedback'),dialog=document.getElementById('team-record-dialog');let record=null,renderer=null,serial=0,bundle=null;dialog.addEventListener('cancel',()=>{++serial;},{signal:ctrl.signal});
  const request=async url=>{if(bundle){const [kind,encoded]=url.split('/'),id=decodeURIComponent(encoded||'');const value=kind==='reports'?(bundle.reports[id]||Object.values(bundle.run.baselines||{}).find(record=>record?.id===id)):kind==='runs'&&id===bundle.run.row.id?bundle.run:null;if(!value)throw Error('导入包中缺少这份历史原件；未从研究服务或最新观点替换。');return value;}const response=await fetch('/api/local-agent-team/'+url,{signal:AbortSignal.any([ctrl.signal,AbortSignal.timeout(20000)])});if(!response.ok)throw Error('指定研究记录暂时无法读取，请重试。');const data=await response.json();if(data.error)throw Error(data.error);return data;};
  async function load(){try{renderer=await import('../agent-team/ui.mjs');if(UserWorkspace.query().get('source')==='import'){await ResearchRecords.importedRows();if(ctrl.signal.aborted)return;bundle=ResearchRecords.getImport(UserWorkspace.query().get('importId'));if(!bundle)throw Error('指定导入原件不存在或已经损坏；请重新导入原文件。');await ResearchRecords.validateImport(bundle);if(ctrl.signal.aborted)return;record=bundle;const acceptedChief=bundle.reports[bundle.run.row.accepted.chief],chief=acceptedChief||bundle.run.baselines?.chief;body.innerHTML=(chief?(!acceptedChief?'<p class="at-warning">本轮没有新首席报告；以下为封存的上一版首席基线，保留原时间。</p>':'')+renderer.reportCard(chief,{chief:true,historical:true}):'')+renderer.runCard(bundle.run)+'<button class="btn" id="team-record-export">导出完整导入原件</button>';feedback.textContent='只读导入原件 · 来源未认证；哈希只证明内容一致。保留原范围、资料截止和完成时间，不更新团队当前观点。';body.querySelector('#team-record-export').onclick=()=>ResearchDesk.download(bundle,'BTC-import-'+bundle.run.row.id+'.json');return;}const id=UserWorkspace.query().get('reportId');if(!id)throw Error('没有指定研究记录。');const received=await request('reports/'+encodeURIComponent(id));if(ctrl.signal.aborted)return;if(received.id!==id||!received.report)throw Error('返回记录与所选版本不一致。');record=received;body.innerHTML=renderer.reportCard(record,{chief:record.role==='chief',historical:true})+'<button class="btn" id="team-record-export">导出此报告</button>';feedback.textContent='已打开指定记录，保留当时版本、来源声明与原有资料时间。';body.querySelector('#team-record-export').onclick=()=>ResearchDesk.download(record,'BTC-role-'+id+'.json');}catch(error){if(!ctrl.signal.aborted)feedback.textContent=error.message;}}
  document.getElementById('outlet').addEventListener('click',async event=>{const button=event.target.closest('[data-evidence],[data-previous],[data-disposition],[data-report]');if(!button||!record||!renderer)return;const ticket=++serial;try{let html;
    if(button.dataset.previous||button.dataset.report){const previous=await request('reports/'+encodeURIComponent(button.dataset.previous||button.dataset.report));html=renderer.reportCard(previous,{chief:previous.role==='chief',historical:true});}
    else if(bundle&&button.dataset.evidence){const receipt=bundle.run.receipts.find(item=>item.id===button.dataset.evidence&&(button.dataset.cycle===bundle.run.row.id||item.historicalBaseline&&item.originCycleId===button.dataset.cycle));if(!receipt)throw Error('导入包中缺少这个历史版本的原始依据；未从研究服务替换。');html=renderer.receiptCard(receipt);}
    else {const cycle=await request('runs/'+encodeURIComponent(button.dataset.cycle));if(ctrl.signal.aborted||ticket!==serial)return;if(button.dataset.disposition){const id=cycle.roles?.[button.dataset.disposition]?.id;if(!id)throw Error('该岗当时没有已接受报告，缺口保留在本轮记录中。');html=renderer.reportCard(await request('reports/'+encodeURIComponent(id)),{historical:true});}else {const receipt=cycle.receipts?.find(item=>item.id===button.dataset.evidence);if(!receipt)throw Error('原记录中没有这项依据；未替换为最新资料。');html=renderer.receiptCard(receipt);}}
    if(ctrl.signal.aborted||ticket!==serial)return;document.getElementById('team-record-evidence').innerHTML=html;if(!dialog.open)dialog.showModal();
  }catch(error){if(!ctrl.signal.aborted&&ticket===serial)feedback.textContent=error.message;}},{signal:ctrl.signal});document.getElementById('team-record-close').onclick=()=>{++serial;dialog.close();};teamRecordCleanup=()=>{++serial;ctrl.abort();dialog.close();};void load();
}
function disposeTeamRecord(){teamRecordCleanup?.();teamRecordCleanup=null;}
